apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-postgres-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30" # 30 seconds
  fromBackup: ""
  baseImage: ""
  fsType: "ext4"
  # diskSelector: "nvme"
  dataLocality: "strict-local"
  recurringJobSelector: '[
    {
    "name":"postgres-replica-storage",
    "isGroup":true
    }
    ]'
