apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardrail-ui
spec:
  template:
    spec:
      containers:
        - name: guardrail-ui
          env:
            - name: ORIGIN
              value: "https://crashes-dev.workrave.org"
