apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardrail-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guardrail-api
  template:
    metadata:
      labels:
        app: guardrail-api
    spec:
      containers:
        - name: guardrail-api
          image: ghcr.io/rcaelers/guardrail-api:latest
          command: ["/app/api"]
          args: ["-C", "/config"]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: secretKey
          volumeMounts:
            - name: config-volume
              mountPath: /config/01-config.yaml
              subPath: 01-config.yaml
            - name: secret-volume
              mountPath: /config/02-secret.yaml
              subPath: secrets
          livenessProbe:
            httpGet:
              path: /api/live
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/ready
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: guardrail-config
        - name: secret-volume
          secret:
            secretName: guardrail-secrets
