apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - schema-rollout-start-job.yaml
  - schema-rollout-complete-job.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - service-account.yaml
  - role.yaml
  - network-policy.yaml