apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: guardrail-api-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["guardrail-config"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["guardrail-secrets", "minio-secrets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["guardrail-initial-admin-token"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
  resourceNames: ["guardrail-api-*"]  # Allow access only to guardrail-api pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guardrail-api-rolebinding
subjects:
- kind: ServiceAccount
  name: guardrail-api-sa
  # The namespace will be set in each overlay
  namespace: default
roleRef:
  kind: Role
  name: guardrail-api-role
  apiGroup: rbac.authorization.k8s.io
