apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-db-secrets
spec:
  secretTemplates:
    - name: postgresql-superuser-secrets
      stringData:
        GUARDRAIL_PASSWORD: ENC[AES256_GCM,data:1GeqAvSiSeiBPxKSqszFI2J5S29AsgxI,iv:jOhX0RgwBsPFgrIGZVQVl2s17iOczxxbvG5HcCNZTzs=,tag:7bHPfbbEDsgUuuJjqrsYkw==,type:str]
        AUTHENTICATOR_PASSWORD: ENC[AES256_GCM,data:kzpxYBKkW9dpRsbb188ba4ptvQ3ICOoJ,iv:MlaBL1okNzzKuB6NRk7RY4CGEsvaaCgtwGfNqfV0hQI=,tag:QML9i16PyPkzrugfBhTi4Q==,type:str]
        WEBUSER_PASSWORD: ENC[AES256_GCM,data:EHbBtxljc1gDWob+BP2DXTNoVIsdxGqK,iv:6jg0cxkU8r3RMvQYaynmhntp0TeZNyqviBmGUX86o6c=,tag:TPxmKjRDmIcR+lSGStIlXA==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Vjk2RUp5UDNHbXF2SXQr
        bHd4djVQc2lhc0tZdGJXZ2hBWVBaU2UvbkdvCkFOYzdmY2xoR1VUbmwzQm9mVk5q
        SmoyWXhldDFPKzVibjR3ZnpKZjNIdWMKLS0tIG55ZENrZzRQVmNVUGdCa3hpYUVt
        aHJqMXJOVHpFSm5nbXFFcHM2bWZGS1EK1QmcVyaszbeuRBv1DVfs9lG+UWxSZi73
        DfKq177BmydzzbzdmfrPhWYZ/qeb3lCcb+WEX9hhfuxpQxmPcEfktw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYXRoZzlBQzNHeWw5REtG
        UUFNTkFPMnFaTlNteEdSaktFenRXd3JlSlZnCjZISFBuVEd5aWpJN3E4QVFoUFlx
        OWszUmRHTWc2M05KbkdpZ3B1TGRGNFEKLS0tIDkwMVdHVjlyRUEvRi80M1VQNWJI
        K3NJcDE1RDl6dUtvWDlwa1BGclRsK0EKiz/6VDLNlaicVXTFqJC6EPf/CRnHP+ov
        i+tLaTVdCzh2Dn3A3gnbrkZ3ZUHBGbED1WrcX8+u5txah2nvDHEZKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T17:21:53Z"
  mac: ENC[AES256_GCM,data:+FdFatUpYc35JtrBRu6oYVCBRso0LLsy4KNutAuCX1DAy8mA0jjBZcLrA8Jb3kDH1BwnYOCPDtF1nurDe25gZ2nt9mhfMdxwqYjYl97ApdE1R29nttarK2iNB/kVWALdketVbeOywfxqbEcDmxuIUsUmVWafbr0nTQ591SwG2Z0=,iv:J7Mj85ig55bZdFEtlOCg9d5tQOXmMe2B5OqS0vOcNFc=,tag:Yg4nuPYpGeaTsuOl8TS6Ww==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
