apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: postgresql-superuser-secrets
spec:
    secretTemplates:
        - name: postgresql-superuser-secrets
          stringData:
            username: ENC[AES256_GCM,data:nm0mvGOOG6M=,iv:Y3AnQiwN5r6fN8pfUT/qBvkd76iCExz+3nywdFCmyd4=,tag:F6vD/GLvg4N9+WCtea3Szw==,type:str]
            password: ENC[AES256_GCM,data:wPhiGPvF9ZDI4FSJNOXMfWtb/Dousfuk,iv:XpWo72uf9QvR6a/BaDMt0Q3MDA/9ca2VK2pRsDtBCNY=,tag:pedrihkEk407iAoXYs90hg==,type:str]
sops:
    age:
        - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdDl5dzBtNll0UzBSaUtR
            SlQ1RnJVMVRtSkE2ZldzamducUI2VjdRNkJnCjY3V0hraFZ2S29oY1kyQTVrV2xa
            NjJDVE1vRDdpcUhWQU5JQjVhV3BCRFUKLS0tIExJbXgxZnpBOGVVdlhONjF2UjVr
            VElqTExWSGxTWmNBN3RnZXFoc2ZoQ1EK0g2O9VVfwZzJDUhUXHawG8UjTcEcHiEx
            cUXHczXhJFJB8ZU5+88xNL9ZcnvdfGCPA92i6LUGkhoejKONMzwJkA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OEE1ZzNmVlNZR3lXNE5v
            TWFzdmx0akhrMXRMR1BFa1dXbEZJM29OdDE0CmRaYTVPTHVXRFlVbitSVXFUYVpL
            VWY3Q055T2o0UzN1TmxiY1RudmRoQjQKLS0tIGQvZTZSWWhzdk9tMHNDaHFBZ2l5
            ZUlMQUl6eHdBZEFwRjVGbFRlQmZ6UTQKSXh3kbbMTC9YCqCe0dzBxZzPn/6btELI
            nXSYOaUdVO1CYm5KAz8UKPMuA22bfrVsgOaDd3qRgpulv/8Lo+zjbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-01T11:54:30Z"
    mac: ENC[AES256_GCM,data:Nksjx4REBHQYegBZdTwczAllEwJxE+8V6x9ZnfOi90Th94Q+cRcZah6zxW++7wgKEMKpEAVrdEzGv37sfrJlPZabtkfKgr5GORNS55cH2SrwlOu3kX21xBvhdt5Fx24c9aFGVjP1eW8s8hZQS8Yc2wl38691dwGHkFt0ogHBA+0=,iv:0Dv/ULLqT3zZMlcFDSXePAMstoTFoTUOJNAigiD8frc=,tag:KIbyYokGIGm29kJwObGyjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
