apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: postgresql-superuser-secrets
spec:
  secretTemplates:
    - name: postgresql-superuser-secrets
      stringData:
        username: ENC[AES256_GCM,data:oOcEDbI3F+o=,iv:CPL9Cu1NOLJ+RjFa796/qMdH8BbwVL/d/HXwmRBo9ko=,tag:xG+L6sk8YyKGgNg6Y4/Bhw==,type:str]
        password: ENC[AES256_GCM,data:4r8wr0llvqez7mLU6KFPcvwoN3DMdSVe,iv:00qV9DdWidETXDqzdvd2kQGI2xjn0cKcTcxxwwNmfSQ=,tag:o0TI/F5IVGhaV7wCygfm8Q==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RlVWemtrYzNFRTIwZzMv
        YjRhSk5EdVBSRVVBZTlpdXhaSHZvanJWQVJBCkhPMWh0bnB0emNKaVFOaTlaMmhn
        NnluUkIrRE1XYTZtdTZyUVFLOElQUDQKLS0tIEkzeGIxMFU4ZzF4RlNiaDRtMUxO
        MFUvNEpMMnB1TUpCTmczNWpjcTZnckkK/0YSU8ZXFTKBbMlSrd+GcFlRDGjHuRA4
        lXVNsCH7rZMNeXFqh6LQceLKYBceGEqV8ibo2kXJ9sDNqvJn1tNfVg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZndRNHVXbmZGSElXam9w
        S3c1MWdVOEcyRFlIM0krWDZOU09wT1hSRmlBCnNYbUx6NmZteDV1enR0MzBWRXM2
        T2pnWmh4VHFwYS9BR0ZoYkhpa0ZIRWsKLS0tIFI0VXcxLzdRNnlwWTJPcE9WNnlN
        ckZsbnpRN3BNRG9xaVhUU1hkVXJKLzQKIo/h8kdHZYa62Lag2XO8Gb4ilVoOfGt5
        tDUUjRCUGYY90GpYF6QhMkHog3TJM8sqPT1yjlo5hV9xzpqb+lXNtQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T17:21:53Z"
  mac: ENC[AES256_GCM,data:AmU3s1WxHXFiMRi31WGrvIRBWg+iLq6PwQamwhjoSzgUQjmW4Qmhtp6JOs6ntIniPbTasYSOiF/q/iCKL1dhquyMDfGB19s6PRv7Do2OCVVFFQdP5OoUzF93y24uRq6pzboN7Rjd0wLXJ/G4/XR6A+HbSBNjo+gpVTY2HVW5mFQ=,iv:JGBxNLWyBBwEAv6wYvbMMwICWFeb4ADYyprpLJaSDHA=,tag:n9v14sFkcCWH6MrF8F8vbQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
