ingress:
  port: 80
  base_url: https://crashes.workrave.org
processor:
  maximum_frame_count: 10
  delimiter: "|"
  skip_patterns: []
  end_patterns:
    - "WinMainCRTStartup"
    - "mainCRTStartup"
    - "main()"
database:
  endpoint: ws://surrealdb:8000
  namespace: guardrail
  database: guardrail
object_storage:
  region: us-east-1
  bucket: guardrail
  endpoint: http://garage:3900
  allow_http: true
jwk:
  token_validity_in_minutes: 30
  public_key: |
    -----BEGIN PUBLIC KEY-----
    %JWK_PUBLIC_KEY_B64%
    -----END PUBLIC KEY-----
oidc:
  issuer_url: https://auth.workrave.org
  internal_issuer_url: http://pocket-id
  client_id: guardrail
  callback_url: https://crashes.workrave.org/auth/oidc/callback
  logout_callback_url: https://crashes.workrave.org/
  launch_url: https://crashes.workrave.org/
  self_service_url: https://auth.workrave.org
  pkce: true
provisioner:
  pocket_id:
    api_url: http://pocket-id
    public_url: https://auth.workrave.org
