web_server:
  port: 80
api_server:
  port: 80
job_server:
  port: 80
object_storage:
  region: us-east-1
  bucket: guardrail
  endpoint: http://minio:9000
  allow_http: true
auth:
  id: guardrail.workrave.org
  origin: https://guardrail.workrave.org/
  name: Guardrail
  jwk:
    token_validity_in_minutes: 30
    public_key:  |
      -----BEGIN PUBLIC KEY-----
      MCowBQYDK2VwAyEA+kw52Fhenb9GDfSq/LaV7RgxPv6f2M5RBB5vuoR6I4k=
      -----END PUBLIC KEY-----
