apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-secrets
spec:
  secretTemplates:
    - name: guardrail-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:pt460XTqtDoj6pBqEjuKf3U9L0nAULFhI3vR9mCA8y+ZuHiBXknIUhnuq4rzB+nWPL3dj5jmBQLdolUMlqM/xdjIPzjFhrIaxwVsVfi9J27oRlTr1tMfc1lzv0lOBj55ywuNQCixm4ZvE+t8VxEc+iFF9U2Bh3yREXvRTkczSBYDciwu7bqW8qKogssIpVjZrK1vIdLl37vng0TTOkalhxqYonhrqyVP8cEwGRGFebrwOYa0UACtBW7aG1orjpTJZ2rMDIkatF2ZgXgUDc9Tl8s8+PjlwTbf5nNazVp772dZDAOYzQRWW7tYU+ha60o4d+2I6SqVCorsZmcfubfjDxDuu11QVEMoGVdNw5q4JbqyrY3+67uueSqVCZerzspJAtvTp8DTigswVSk+Scc06wwaBTHl6EILp37kFB92/8yTWHZcBKWCY4LLNyc5+DMa9bTkAX8Ocd/IU2XyXGecJl2hKmmFSRTnKb3+uFWuL3vuVSzsfUdSjGegMITu7hzpBhYJt6lD9EbiL3vx9H2LNaB/U2XfmEJThbC9Smkf5Cpn+8XFQg6Zu26OoX7T/zfN2zsCVW667+jJgD2J1gcDmWt9hKGphUimrvbuIEyNdbP7u2LagztBNA==,iv:dvCaH2GrnuDBjg8HSWx3z9E9Na6JZvZiFpa6hZaJ0no=,tag:8o++EXQYYdXSDpbwRfpupg==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUUQ0T2JhNmpwVXJuV0wr
        VVJzeVdwRkdSN3dPRmFqRHlKWnpqeXo4L2xnCjM4azBIMzBHNnIrREJITlVad0ZQ
        YVhDYlhVUjdMdTRPanN2bHVrYlNYWVUKLS0tIFNRU3ZwTTh6NnJ5ZCtBUmpydVNi
        Z25Ea0NlSHYzcnN5WGtpUnlleWxZNEEKBxCluKxvje4HqNKt5rDCU2+cPum/zK4r
        D6xWVVp86A9WIYV+EYFEZIWrq9FNoOMPdKXHiQQJvawsYfzfiSPMdw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTd1YvYzU2aUVaVkVnc3px
        UDRJSDkxbDVjbjQzS1lNV01KZnc1UXU0MVE4CktBaDlGekZ2OUxvVFdWc00yY2hL
        dWVyMlNSUUkxZHRLWDlYM0QzMW5DdzQKLS0tIGd1QzMyb0dyek02N0pac2F0bW1D
        WWlIZTg0TVVuMmtBZDVyamJQVXNYVVkKu3ui5qOw9Z2oiMwiIISbOcc2GSamgsWB
        DNUYO9wl0ZLBy1ZwwTXZxrP2eYmlXUShOLFj/T2zVkW/bEVgC9ShJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-08T18:30:52Z"
  mac: ENC[AES256_GCM,data:1/W3Y3a+U2elyo7jFgvHhysNl5i0VEtiwVZQFChuu/GYEa9pGenLGFJHtVsEFRaoXPiA3CWeU8+YiU+tAQ6tsBUy2fdoyQUw8/yLT0AHYX2lDTE+O14G0RibhAD+yks3tFZZLveB7ddcmNEM5SytHXsieSaaOVKVzP4V+lVvMhc=,iv:hebiHjbUgWFRxwsAOJ1EQtHDPlvrRNu+QujsIODAGGw=,tag:fbb/ENrtvBHkoE9FZKyzpA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
