apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-secrets
spec:
  secretTemplates:
    - name: guardrail-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:AY/uqIduugPptDm1THYjal7FQSEkK+yg5v/BTwBps/tzt4afING19JN4KSYVNYVz8aq5lMM/fy2MJ5j3aactkjiQnVSSPemzwsRbR8mJlHuwn+7RsFOoToIsF8kZal0PdQMWmLMa/BMsETgmmHv1ClsRDwQHWJucyXDERimePlyxBr0S/IMbs7T7ATWC93dlPld73q10NhFLsMSBn+zcj6RRarCSHD1wfyY08fTqqCTtK/LMWsiae+7x6psPce5aeAhvJ1Ge4ZwjcPN7p0HhTfDP1y4SHn9rrhOywhG7DTFYUyKaRMO8iznFvdMTRgINdOqyoKuvm7UwwKETvn2TeaRa1YuisR3rBhpluY1xF3DtyFRMg5ta3dBvI94PIENucs9rUsG46yRdLtr/0qZ7oHnGA5Podd0YtpOVboSWx1Zk0132C7qX3SrR351TXQNyXQPwRSzqbBh6Fow1wxxTFkP2PXWpNUsaFiAdJSBk8gtmrxt6RFkoVc5nrGvb741nQs+wzTPqfjUGmXRtFghnSk2Dcz6dGFV/mp9DmFKLwfywh9C0FbpnJ7c6enKzmywmR7L4JoCotTC+2pXGH8xfgd84V8s0k9f/xc0h7gg5HbGD1EHEUw==,iv:SNnSbjpZGLqbgvUV8QPjpX/7LYLzcRMrEiMIaMpzAH8=,tag:cZtrCynOoMmBpwglgx6Hpw==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3di9JU2oxWnh3TElTUXFQ
        ZGxzK2crN1BZeHU1MC9GakRVNWNva2pqOVJFCnYxZWh3cjA4WW1sSGticlRPRGho
        R3VlVjBjcVpCd3d2WVVKelJCWjhkdFEKLS0tIGhNaFNQMFltL3ZQczRENXpuV0wv
        UjhGcmRuaG9jMWpYN1FUTkxkK1VBQzgKEshoFZ1ub/FvYY+x2x0ZneUDvwukQEb9
        x8tBb/RjwhLy1EFeQlSVI8WyMj6YFAe343x/0yrrNQKwWykU51By+g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhKytzd2dIMmwyZjl3K0ti
        TVVrdHA4ZWN4aHQvNkQyOTRWUlIwem01UUJzCnNRbWREV21YTCtRZzdLYUZhb3RV
        WXVOajhNbGZOT3VITytKbjF1K2xFVWcKLS0tIE5PMEdEanNLcDJqK3pRenRXb0RW
        b2NlWnJReWxZcEl6Y3RBTHpscDJHQ1EKkByRujWAIfp8R9NqDBEQbGuHretoqVgq
        9Gk/j89xiHy6y0JQFRasPWIoe2REFJlv9qTepSXm3fXdUd71nimO2A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T17:21:53Z"
  mac: ENC[AES256_GCM,data:oqgGzkfmJ6JwFTl6mfHrVZwbNIkjaR/b1wDpPkOKiTOj72E0Xs2LYVF3c6dhuX+hR4hidGssHATx+eyB31WbwT7vbu623UkCAT8wjNP3HbEJ5zFRQK+HUN7kqlr4UIFsU7/IBON7QC/y2NIf8kMmps02UOYDXo/qwZDeONdM7V0=,iv:eInnho3ehZNSgnVfTUoxqkpOZyyTtI1zcNK+KPUE8+w=,tag:FqPiqxnMGZs0d/0zY++GHw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
