apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-secrets
spec:
  secretTemplates:
    - name: guardrail-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:EZdgobjKtGcLp+KDSJC6PF0qkTM5JDqGWN5QQDPBFiynljN/aheYLjfV8xBjlhzls1BaqOREvGplx4N2pTLdNXE++xOQUXJWaQ8fV7AhrbHqhRSGwmJEeseSEyf2WX1H1Ef5C3OOfitsTK5Bilf/BcWRHYz4Q2dCgNHZAlX6VvKUkaM+ktFGUuWTEq7MtuEmMobbfzAaHz1B2o84C2VEbBOW/vEyqfalWdp1ndFFlTMq423eb5hZQIPrfnTDlrKMJX7BRM5ZOQbrHWpp8s+PdIA84CBZTcFHoMZVQlYqj4sQi3jXQF3FnnQTpiAXdV/iZ5zTycQye5p6nzGoapRWLA7ZcIW/CwPW6t3J2JEue4wu/4hYDoUMKKhmylrR+zklT63BcyqFuv6FRhRNt5OuJ41/s+4HKDSGizzNPAPcP0oz0LHIwRKkOWsCh6qYCqv+VibI5Ai+iaE1EmAq1OYszCx3I4IkazkiQqa7wvHsWb8S4yl+GFbPCoG7IKa5F+NOwUig7aXxeMl/M8Lq5NKApX94QZydqtevy6gu2AJxdY/hCG9xSw3X9qwl6u2YA0E=,iv:sSetvD+/XrTs+zFKs7lyXI+L9pPYDLMIbijlU8ilJhs=,tag:hyuXlt3WNkm5vhtZnTBVPA==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOUZlVXowNXhkbHVMUnFz
        VUU4bEU0U1J1ZEVrY2JReXdjNGV5ZFJjNFE0CnRSYUdmUG1xMytXRklVVHZnS0xN
        SjlncjhLYkhwOUEySStISGFLTTdkRDAKLS0tIGNidEU5d2JiaStxeUhVTENnUzBv
        NkZMNWVKbTZLSC9JbkR6dGJiOVBsWTgK6Tysd/U4hmyNI4JP2JDpEuT2uelx6pn1
        AsyEee3fpev/3jUvXotYEXQY8fJpzXsEBgnHRuFkO7iObpivhwZdww==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcHVDd29JK2tTbEtnRjlh
        NTU0UXpFV0FwWm1xaXIrc3NLMlpEM3A2ekdVCis3Qm5rN3QwbUo1VW9FYlovbGlw
        L0cweUVxNks4RlFhK3NybmEzY0dRd00KLS0tIDFPU3o0RnhYNTZuNWRseEpDQzFY
        OVRKTGFFNmZKODcwbloxcFFBTk9ZRlkK+GwLCFxE6wJvXhXjtI9YZ7oRQW+MA+fZ
        tiJ9ZKMdT7Sh2VcGis/qWoSFVOcnnD782WVoROJg9QKSksOTNLIV5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T15:29:49Z"
  mac: ENC[AES256_GCM,data:xdkN8y47C5A0QvNRgQGwF94D0Mw/NxUlCxsSxSqmMVR+9qPwVUCMBddBom2djciZFvWWpezsgpsYkH7YCAOb/EJwtzTLpHUpYXqW1BxT5YUSXPWEGnMdzbdAzHulxkHnpBwQEnihYDqhh707ZSXk30Dslu94/koWg44DYL5JEGI=,iv:eCT/AaJYais/ayeRCErPXxwwTI1LOvsKCsZeGwsLqpo=,tag:gKJoD7H291aFEbqKl9eYDA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
