apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-secrets
spec:
  secretTemplates:
    - name: guardrail-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:kbXdUVfAibCvLwRXAebPu/kKl/bLhL6yH3Lc6rUePZsvmnot706RvTEcDp1UUMc24JMHZWPOd3wnbr+XeFu53W+AmAtWywKRQ2z1dVKnlv0r7pFiJV36rBMBm4nNt2idlNsoOlEP7XfkC8CvuJFJsUhHTRasFAjcMTw6VcllxYCKWOWVRjj0c0xTWahiy8zNvbGU2ibnfshizmJecPocrcLRDBfeiTcsi9WXFzOSOqMkeFBxLVORVmAkiq4F/QKQi1lH4QcjuyB+IgG23I09IOToAzNEtw6nyI/zbimHRAg466CbEnFH4wZvBH3RYKDObyd5idzqDSoa9SpkIO8zkIOObyV6Pn62y+Cih4jr/4XoVi3l4MDoT7qlBF7JTKuCzdGazmE3ocq4UK+VxYhaP9T+x7HsQ4nSGr/Fjsb/gJPvkouVCJ0hXrDH5MOa4s71qP4MzR/6BwAOE16CYep0InVJlJYLVDHWk++ITdJsbXzk3qxWQyatf6vSOrrSoMVPbDLc2L8sdUwbfPqLg4Px5nVHrypO9NDn3Be38uS/wV4cFc0I9YnE0Jetq2vzeT9QWPd22+d+XoN50e2W52Hg1A8zJeWrRIiVdy5u,iv:GSF7pQ532j8JlGZiurHFWql90hzZCgthrbJj1ciyGXA=,tag:ezl23lc2gUyBLbX0Jha/zQ==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTGF2dmdKYkJGSVpkWXgy
        Ni84NVlFaU9WV2NZZC9sM0tJMnJZUjZmTlNBCllQUlBBbU51VjBmbGVKd2NOU1hK
        dVFkYmFOOE1sODllQVBoR2F1R1BtR0EKLS0tIGtxSWxVem1WOTVZUVlMUUpUREhp
        T1VLTHlrTmZuSXFJekdTa3Vqa3hqem8Kc8d0D2VJdkERH7JV50VT0aLILfp5aUyC
        TSOqMbr3kDSRt3P5OE/L5Rr6tTcQF5/N6NJonwPh6e/BqOK/puDpsA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YXVBVnYwenFFMGdta25S
        YUxmazNXQ2NBa013aU40cC9sYnRvRS85ZUcwCmo1Y0ZKV1k2VXpETS9PRm9HNmFy
        SzdidUM1Q2t1T3FHTGIyZVdXUEpIZzgKLS0tIFBxeFZHMU9KVytmS2ZId2Y5SGpl
        MjE4R0tMZlBHQXQ0UDI0N2JzampzclUKTBxQzbNhQqbYV/KP4T1DIUyBE/KFqAOE
        te2RtJ25eTvgtSD64oWPnmW9IztBxvLwA7BvGHL+FF4DtlU3iCBenw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T22:15:11Z"
  mac: ENC[AES256_GCM,data:X5icpv9Zcfvf25L6flGTfBlFE0b0dNHgEgxWvqVyRKWQHMdUWFYW421RRKozKwgUi/K8IofHaZeBmGqN6ImqB15DYW8Opx708Kf6UTNMPZJuPbfN81Jumk8z8B1/qKhVX7lDk0sn2qs/FdVZxwIp46/bbk6cx7brbkOY6Dcf/WE=,iv:6tJhxlM0lELymCgolVgbrosO0FHputvp+xW/mcVL+jU=,tag:C29jfRrDNtCk+mdzGJ7XbA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
