apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guardrail-prd
resources:
  - ../../base
  - 02-secrets.yaml
  - guardrail-setup-secrets.yaml
configMapGenerator:
  - name: guardrail-config
    files:
      - 01-config.yaml
    options:
      disableNameSuffixHash: true
  - name: guardrail-setup-config
    literals:
      - WORKRAVE_PRODUCT_ID=17638AE6-CAC9-43E2-BFDE-8E2150896740
    options:
      disableNameSuffixHash: true