apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crashes-workrave-org
  namespace: envoy-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  secretName: crashes-workrave-org-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - crashes.workrave.org
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-workrave-org
  namespace: envoy-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  secretName: auth-workrave-org-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - auth.workrave.org
