apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guardrail-dev
resources:
  - ../../base
configMapGenerator:
  - name: guardrail-auth-config
    options:
      disableNameSuffixHash: true
    envs:
      - config.env
