apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: flux-webhook-sop-secrets
spec:
  secretTemplates:
    - name: flux-webhook-token
      stringData:
        token: ENC[AES256_GCM,data:mXMaQGC62QVI8zWP5DOsUm9pwuXFQYiEXtjH2nN3ErMmogw4kg65f5BP7QSYbqfz/goS/aHxGPKVWV/NS4L38Q==,iv:ql6ljL156cZjVQG2o2mwKyinSdOnAMnP0xYom0W31LU=,tag:Xabfm6wMOORmFzkscuheJw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cFNLb1Mzc3hSZEljak9R
        YUdva3VvWWp2djhmYUw0bFoySHBpYi9QcnlNCmZ5ZTY4SzBSTUdMcmM3ODErR2dK
        dHZUdkk2SUNYRUJqUkV3QzZZZ2dQZFEKLS0tIFFXa1lObkIzc0VURlFKWm00K2FR
        ZFFxREdIdGdvWGZrL0ZUazQ1WWVVdUkKy7e7vvWD3A8xVWsn1ypI7RX4q8DtPw3Q
        221Z418mH836PZRTAGUMjiRgWSzdVhCCWWUDkfruyjkWZBM176+0bQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Vmk3NG16WWttYTNtMHZl
        aTQ3MXd0Y1ptcndxQ0xWcGcyQlEwU2QvMkZ3Ckh1d2pOOGFBVWhjQ01IRVNId1pm
        Sm5JT2Q2VkFJSW52WUhWaENWUHRJL1EKLS0tIExQeEwzSFJ2bFJVRGtUM09GKy9l
        Yyswb2s1VmtpZmg0dXBnZ2VVTnBNL1UK7gNOrDte5ZCtp2vSc1vnV0yKcCkHvdX6
        e/TE1qsGkSj7GDa82ivQJEX0hPXuEJlfJmV3XJNnwYIdspG5Zhy9SQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-02T20:40:44Z"
  mac: ENC[AES256_GCM,data:KcHRlkT7iv59ONRw3+r+XsGdsFYZPGDLif7lnulOwW+y7H+Zub3WkZH8uwEXD/IOIzw3WgVCo446HI5P35+W8MXw333IP8+iKDl4LnEugXSECxXA0SDio8JSYcESNfGPMZjJHx1RmopHBwvGaQ47aZHUWdL6KmSyKKap+OxfuRg=,iv:VJHhrNKJtTrAZdve6WmiCQnGi1L+VZF9L0kfuh0GU3E=,tag:Tkvj6FTvs0pyrvmNThJHEw==,type:str]
  version: 3.13.3
