apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-provisioner-secrets
spec:
  secretTemplates:
    - name: guardrail-provisioner-secrets
      stringData:
        secrets: |
          provisioner:
            rauthy:
              api_key: "guardrail$%RAUTHY_BOOTSTRAP_API_KEY_SECRET%"
