apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-provisioner-secrets
spec:
  secretTemplates:
    - name: guardrail-provisioner-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:itVaLJsTwvhFwp74ZVgJEl4xMkdX0naRQE9UlVIkHepheJfZWakDnx+A8qQxdQoPqwHjMItXE/zVcqZgmxXpU1FBu3tgFT0Yz7SP7bkqso7gYGLUXqBZ6Z4x7mVLKZjFhtEg52lbAIXFHogAVlSrWKc=,iv:Uzr5qMcFac7tmZhkabE60gAjQ7czkvFFryfV3LlLecI=,tag:3N7ra9pvrZCbr/GaPUuaoQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMWZwNmE1SGJsSXVYODgz
        eHdwK2VHRUF6aWtwTWtxQ1FKOHNiUWhZaW1rClBaNngvZDBLTEtaSzdhWlZUeWx0
        eWxNa2ltbnNBZ1VjWk1lb2RRR1pFOFUKLS0tIGdVVUphZFJwNzRMMTl2OUhHenZy
        bS9WT2EvRUdYVUNCN3ZycGRYRm0wYncKix4l6uYHnW12gdr5XUku3+79z8wYH4Ry
        cPS8TxWO7Hc67H7pFK9PnqYrdaK/6xMNHYUiNB1uizLTxtZ1mwWwog==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZmpsdnR5dWI4N2tDc05L
        d1RFaFQ5TENXa2ZMME5BclUxNC9tSWcwR0JjCi9QSXhJZDVOOXJYQm9wL2daMUgw
        RVFtN0J3QWUvVHBPQ0dCS2xpS204dUEKLS0tIFAzdzZQMUJrSjFNT051QzV6dlFP
        S2tiM2JZT0pjOFBZMERGSlhvRC9wRW8KuoJkxm07wcbNT5PcZDvlwhR6nTMlg1qF
        58M2guetrneW4+7af4jTgcUaKkamam9MDkp9b3NI4lHY4q5A7oe+qg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T17:48:54Z"
  mac: ENC[AES256_GCM,data:gKCFOlig082DwGWc+sCXRWEoMxXcSqDM0+kNJLi+iZl+zTFJZDWN4LWQY7etbsFB6IS1MHOtRGrxq3jEUOUt3K6dwuYc8/eLIN4hIYdtmujgBF3mbKD5dzkRGZzdq/qXVM2UDow8rbM2c+w918biqP2Flu0sFciTizc9/dExsHY=,iv:YltnGV66djaxBwLgP0Ye6QDS7o43bc0/Y2YCn5+xVjE=,tag:1zmgYNUknkjbIekYULlgEg==,type:str]
  version: 3.13.1
