apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guardrail

resources:
  - ../../base
  # 05-provisioner-rauthy-secrets.yaml disabled: rauthy provisioner removed from guardrail

configMapGenerator:
  - name: guardrail-config
    behavior: merge
    files:
      - 01-ingress.yaml
      - 01-web.yaml
