apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: rolebinding-patch.yaml
namespace: guardrail-dev
images:
- name: ghcr.io/rcaelers/guardrail-processor
  newTag: cb46543
