apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardrail-processor
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: guardrail-processor
  template:
    metadata:
      labels:
        app: guardrail-processor
    spec:
      serviceAccountName: guardrail-processor-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: guardrail-processor
          image: ghcr.io/rcaelers/guardrail-processor:latest
          command: ["/app/processor"]
          args: ["-C", "/config"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: secretKey
          volumeMounts:
            - name: config-volume
              mountPath: /config/01-config.yaml
              subPath: 01-config.yaml
            - name: secret-volume
              mountPath: /config/02-secret.yaml
              subPath: secrets
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: config-volume
          configMap:
            name: guardrail-config
        - name: secret-volume
          secret:
            secretName: guardrail-secrets
        - name: tmp-volume
          emptyDir: {}
