apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - deployment.yaml
  - network-policy.yaml
  - service-account.yaml
  - role.yaml
patches:
  - path: rolebinding-patch.yaml
images:
  - name: ghcr.io/rcaelers/guardrail-server
    newTag: "db6f9f0"
