apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: surrealdb-sop-secrets
spec:
  secretTemplates:
    - name: surrealdb-secrets
      stringData:
        rootUser: ENC[AES256_GCM,data:auNr/Ww=,iv:/ATem79PjoRyA7uzqUQcurIto74WUBf/Lk8VPOTcfFo=,tag:XdtUspI3nHhnfp8nBZsPWg==,type:str]
        rootPassword: ENC[AES256_GCM,data:FKp4wK+cfSU4nvsl/ZL/rj2trSDA3OM6,iv:zFwoaBaEeBGq5Z7miFrZbZ/qcvJFGTcIKyQB1a0+Tgk=,tag:mG/gtjYC2YvG+qBSO21YdA==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRnE1RXYxOFpiUGlpVEFO
        T0RZZU1nWndCWlpXWjNwVTNjLzFJRTE2dkYwCitOS29BZnZkS1Q1cUhyZUp6dDFQ
        b2tQdTBjU0RFbkZMclNTelRGRm9lMGcKLS0tIFBLejNUY3grQ25zSFhGQzJXN0V0
        TjFNbnVjMFlhVlFBU3ZMbnJMZGhEQjAKYDQHra0Yyjbd0eOGDkATIu66h9h/SycE
        6DIJYflHxDcwcGdYWeM1nrRhSKAn6i2uueNNSfAaSTfNTZAKE0b62Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTHlHaGo5LzYwYk56ZFBo
        WmlIcWQ1YVVqdjZnUGlST3IyVEhCWDdCQkFJClpyay9LUVNQQTZrUWUycWUwRmpH
        bzlhTjBETSt4L1hzMCttSzhXODhFWmMKLS0tIEh2MXF6a2F6NmVtUGJxMGZGN28y
        djdPaGdsMVJpOWpqc3pPMThxR21TRHMKOh9d+bLPkriqMENYB47DlFOOAGf9tAzV
        3cHsTpgE4nyGUrxe6QN7enzNYIdNU67s4qzRznVFOwq8gR2CoMnfxw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-09T18:15:21Z"
  mac: ENC[AES256_GCM,data:bLU81a6MJSd2AZaOGzqLNCKQFvUMJBj2NugU7Fr4AeJkxMqr3/H/TviA5wjZ1cdLy5W2w7oee7aGG5pIqCgsZbeYRMwKSU6ga8X7P5jDNWVxURtOEFRQ7cSxnnSqQbHZKYA485JZkHX0g5KS+AtszJcRZNW69izEY/+/CGXSbkc=,iv:UoJ6/peALfvIAMG2Hee65x7Skzz99uFf56TCxfqgAUI=,tag:GPmOWxc7NGXUMXSrIrblSA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
