apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: surrealdb-tailnet
  annotations:
    tailscale.com/proxy-group: tailnet-ingress
    tailscale.com/tags: tag:shared-surrealdb-dev
spec:
  defaultBackend:
    service:
      name: surrealdb
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
        - surrealdb-dev
