apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-db-secrets
spec:
  secretTemplates:
    - name: postgresql-superuser-secrets
      stringData:
        GUARDRAIL_PASSWORD: ENC[AES256_GCM,data:TU3NGCrx8NcWi34P3CV/xUhsOyMFZdtj,iv:fNib24Q2Mp4ssOz5Qu1p5v6UpudCX1Z0pW/JgLql+8w=,tag:C6CUwSPHeI5FCcuRIrsmWQ==,type:str]
        AUTHENTICATOR_PASSWORD: ENC[AES256_GCM,data:SMZ/Hmke1rz3VJT+21QgKQqu4CHnyuj1,iv:7yJVPCagjHoFQLfPh6ASGHEoAUEbWwp9Elaa3epuUW0=,tag:a+VQ5/acEnfAYsFjOA8fmA==,type:str]
        WEBUSER_PASSWORD: ENC[AES256_GCM,data:56Aua02bShnBg94Azpj7vmSdLwGFu8Vl,iv:SM5AJ2yYtd2ww4gkutpcX2xQ1QlDwW2BEe/6NCzIJQw=,tag:1RZYQmQwMuzTXpoMM7m+wg==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTW51RngyU2VNQzVUdmNF
        SFNzekNhcE5ZcnVYNSt0cjE5T0xMQVIrMEMwCk1hSnBIb2JOdFFDaWFHdzNWeFJw
        Mm94OTdNbmVLcEFDc1pMMVVKQVl6ODQKLS0tIGkvenF2ZjgwbHA1SnpXNkt2V0Nk
        L2R4Kzl1cmtkQUlhYzlvdUlTZnZvWEEKt55WEH/Vghb65Gbu3RURvdq4h8YBxm5B
        5McgRlWUoe6KB4ch70F+e9jyHQLHSt/rhGvPjx1UOFa3q5q6ti2e5A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOTdOSnBOd0E3bDhiRjVS
        VHJUZmdTMTBVUytDYktJb2x3OWdvMzlKSEZZClVxOWo1SnU2UkJmSzBiWHBIUldU
        ME1OckgxQ3dkaFp3ek1CRE1uQnBJNWMKLS0tIHIyYVJtK2Nvamh3MFFiY2ZZRCtk
        Znd0LzlEbkp6NkVNdkNOOXBZeUcrajgKGvQL6c+tcYmyLueHmEMCt+mBH4zuEBfF
        ltc3zDIiWESlYk4JGBgGFWJP6GUiqtVjPzLNea9E2WdcS6jl9vH7/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T22:15:11Z"
  mac: ENC[AES256_GCM,data:WNEzBVyq8Ib6QhNoz4Sm3OkEo80QItqaMnoGnlJNCdArgiCtqoOattqCwS+lTULvA788p8dzUEQD1z/9prZmdoEt1Gw7uGPPKKTfFoPTCc80t6R38zt6G3LndbmjHTInoxW2ak/fscsOoikJZj+7yHlLB+kez+nIqfuIV+vJfwM=,iv:Ju0o+CNE0eMqEB2jrgn1EkQUCvmi+tixTOq5BihX0is=,tag:zySxbWqAZ9CNjqv6ZWBIEg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
