apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: postgresql-superuser-secrets
spec:
  secretTemplates:
    - name: postgresql-superuser-secrets
      stringData:
        username: ENC[AES256_GCM,data:mIsm/NggE+E=,iv:vsvqgekaw0Fl9o4scqT+CuK8rKbXvtThIpDRQ/+6Y2g=,tag:4zms9Q3aC5l5d4GJh+59nw==,type:str]
        password: ENC[AES256_GCM,data:LE47rzKasGdZAjmCnTajLBNlfggbrBSv,iv:ua0jpU3bVF8vfYZDL//753tQ2g8WSjGx9SL2NlxZKlA=,tag:5cRfyM/dTXakaX2fnDjODw==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNXMyWWEwNE1YRlJjb1Ex
        QStlR1JiQ0hmQXJ2bDlPOUJPQ1BULzNyWUZzClNrbjNBYzdkWHZIZHc3dDd4bVZu
        dmhSenRMby95UW9yYUdBcUFtUmFpM2cKLS0tIFVMMS93REJTTEljcitYR1hFT0JL
        RXJFOGxGT3VjZndwaXlaTjcyMHkrVzQK8bhhCjIZ+hFFcQsVd5VR7fkvVGvH78T5
        RrO64JsL4LKl2gehSKdcFfqJrKSzOmyDvXDQEdkjvu2EGW1atwhv0g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVmR0KzlCcDhHS00rSXZo
        ZXljc3RvSFBlVm8zaEhhMENSY2ZIdERDMzJRCnllWDAyUnFiVWJ1SjRJYjdBNXpj
        YnBrU0Q0N2ZVdmNmZUxUYTNEN1Fac3cKLS0tIGNyY05UMUFDdFk0T2dCd0RNYzR2
        QlhUM2pVSEFxV0MxR1FyRmkzSU50VUUKrn39q2sAa3Zv+OQxmY7F7hSP0xlwKceK
        qG3VqG4ffbCuKhib4T5HY5fGFf3Zus1PAT/srMzZ6lFcFc3ienUbSw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T22:15:11Z"
  mac: ENC[AES256_GCM,data:cSqZuXGRmIyOuvicO/DRz63XbsOGQXwkawqEqYO6MbuhDdMGUE2IkR7j+bKUgwCK9USeygEGwqDC+haKfPyBOqOHC8JcFsF0zT1kMJeMaqQ0OUr3GhS34MMk/mUwTAV31NYsiV1lYrOOPqZ48uaSB/nygZjQj3YSZba1sTxnEwQ=,iv:kh8KVQ4QFYwlOPiBoqQd/zhgrjm2u+u1ck5L99OGyKo=,tag:jlp84pXwQaWk/A31qSV+6g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
