apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guardrail

resources:
  - ../../base
  - rauthy-secrets.yaml

patches:
  - path: ingress-host-patch.json
    target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: rauthy

configMapGenerator:
  - name: rauthy-config
    options:
      disableNameSuffixHash: true
    envs:
      - config.env
