apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: rauthy-sops-secrets
spec:
  secretTemplates:
    - name: rauthy-secrets
      stringData:
        ENC_KEYS: "%RAUTHY_ENC_KEYS%"
        ENC_KEY_ACTIVE: "%RAUTHY_ENC_KEY_ID%"
        HQL_SECRET_RAFT: "%RAUTHY_HQL_SECRET_RAFT%"
        HQL_SECRET_API: "%RAUTHY_HQL_SECRET_API%"
        BOOTSTRAP_API_KEY: "%RAUTHY_BOOTSTRAP_API_KEY%"
        BOOTSTRAP_API_KEY_SECRET: "%RAUTHY_BOOTSTRAP_API_KEY_SECRET%"
        BOOTSTRAP_ADMIN_PASSWORD_PLAIN: "%RAUTHY_ADMIN_PASSWORD%"
