apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: rauthy-sops-secrets
spec:
  secretTemplates:
    - name: rauthy-secrets
      stringData:
        ENC_KEYS: ENC[AES256_GCM,data:K1gXMAklGfJB4Il8Qm5Xps7Or9lN/u2x+X+fzTmKRI7H0wJStaEURTaOy999wcict5qr/e0=,iv:tWAFIFbKcbZNQP/wN+yiSKY0RaVpDh+cPOodXzkIc3w=,tag://D0w1sxcqS6BaJcTHrwFQ==,type:str]
        ENC_KEY_ACTIVE: ENC[AES256_GCM,data:75VGXCseUQs=,iv:oG7N3nXVri0NcfL7SDMevcgkal/MqoOzsvX8F40KyNM=,tag:VPlGKQNozEqdrF0DrkESMw==,type:str]
        HQL_SECRET_RAFT: ENC[AES256_GCM,data:Jkp3a76oHuleXKeOJeSmIh69WrhzvGEtRF/gYUIV/gs=,iv:SZ71Ucvf8s8D5nPCF6Gm8XvvADPC38F6pckZ2MiPESM=,tag:KHkkxloUtrIiWYMYiF0HWg==,type:str]
        HQL_SECRET_API: ENC[AES256_GCM,data:lhLDYSShIWj8iw71grEn7rEUSybZHCBnboYj2VvHg1w=,iv:zSHjOY5vfWyIzZ7FXj15G//S6q2BUlpEEEaxtsAIhjc=,tag:HKO5t+5euNtxyAfrPcgn8Q==,type:str]
        BOOTSTRAP_API_KEY: ENC[AES256_GCM,data:AdmB8n3FratjmT8Ku2NP3tsp7nigTI/4oNbzqUDGAtF25QmPmtRJ8NgNl7SS0CBpJPUwCeRCOJE8QLIBxgvJZ/itvO3R4GStqhrHsy6xW5Q4O7p2X1GUbWDpbwa+ZnoKe1T0MIiswckwM9/EMFSxG/N5CWKaiIf+pYvlLH+l90ee/v+XFtX1rnIwPABU7vq/GTjawrMxRGGWuD+2ThSz3IT6YFgvsVUD/nS6/BYBjPvh62JKD1BbTi6fV4NuRnEFoFDFcjVIuMDoUIvHGollV3i1zfAPrU79IPAwi7vIb3iTNT8nvdZHgwkWN/aIQaY2SMMZxfOwsuG6seR1V5o7RwNFsGLIWSRMJXZj4FqTZkAA64OORh+/vGTf3zZOsgGOgKTKsnA7O+A2dJg4KvkVD7aJCS6mbnkZS7wSPg==,iv:iMzzOQkRh0TZw+Qql9mR0O6mGyaUs5NhGzRsSvNk8KM=,tag:Vu0h6cp6MEbgJD0dAaQ/8w==,type:str]
        BOOTSTRAP_API_KEY_SECRET: ENC[AES256_GCM,data:6YG2pD99m6stoguuvPUCm5j+s7X0R7SDLCFmfrSWJWFx9zPJpXpsZSOIfk6hDushtdUJxxzBU+UBwnwdY7d+pw==,iv:Ogr3mDFKiYD+EPuVRPUQbmSWCg8JbczX572jEB30W3w=,tag:1n0Lhu8iF2uVwaU3sVf9Bw==,type:str]
        BOOTSTRAP_ADMIN_PASSWORD_PLAIN: ENC[AES256_GCM,data:C+snmxeLIe5lU5hINwFSi2iNp9/CREoQT6KXkFXImIM=,iv:fGKWgACKNOPEaQA9VbdWp1Y1gUp2e9obu6TqCtfLKB4=,tag:pJMgbH+qAMwomGuhAK1XnQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWWtidVJiTExCWXlmS2Y5
        V0FrTG5LcFBZazR1M2NrdHFVTUVpR3RRWFZzCmVwU3AyMFlBTXVVbUdZUnlRV0oy
        T2U5U29QVkJnWlN2eG50UTdaRG1JS00KLS0tIC9SV1JnQVAzKyt1VkprTmVmQXVS
        Z3FrQkxmYnNHZmo3ekVoZlpDbEtXbW8Kiu57FBL4BbpKb6e24gLor0mZrK/Kox/p
        6C9V0KmCeIC7x6di3lL6h/Q8o7LApWqBd0up/3ewoVrYtqtFWCxv3g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTGlndlFzY3B5cTMxT3BD
        SGNnSWtocnhZOWRGNU1HYkpNbC80aEdTaUFNCnlVODNKZ2NFNllOdVh6d3RVWWhE
        bUtnUTkvbnBjQ25mUnZLaENoZDFtWVkKLS0tIDdZamhLQllwaUc1QlBPQjIvTnVj
        azA5V2pMTDByRXNYSkkxNTE5T3g3Z00K6cHomnx49FQTQVRYtEO1NgNAxMsPG5FI
        1mMTOCDmSzhhCWDlI+yWvxcx2P/a0j6moO0AFlb5w9zH2EFLGgehDw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T17:48:54Z"
  mac: ENC[AES256_GCM,data:0qgKatfhUdZ0gJuM5WplxSRc/YbEVwj4bTnChv1HK9w9v7xlgoArEiVxF0wrgzF9jNm96SPTp0fdNkYAOCQc8jMLsI/TN7vALbQGkdMTtBt7DvXPgwoNG58jlfkt0XfxOVTRJI0VUUFThs/7F6z/v/avrisxjBTVEyFsACYzXt4=,iv:kqllUMrEuC2xKSYdI19zCmzxanxrUxY0KcPVUm4Ha2I=,tag:S3bqXkN95qhfYyfFpPL49Q==,type:str]
  version: 3.13.1
