apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
patches:
  - path: database-env-patch.yaml
images:
  - name: ghcr.io/rcaelers/guardrail-server
    newTag: "fd72cdf"
