web_server:
  port: 80
api_server:
  port: 80
object_storage:
  region: us-east-1
  bucket: guardrail
  endpoint: http://minio:9000
  allow_http: true
auth:
  id: guardrail-dev.workrave.org
  origin: https://guardrail-dev.workrave.org/
  name: Guardrail
  jwk:
    token_validity_in_minutes: 30
    public_key:  |
      -----BEGIN PUBLIC KEY-----
      MCowBQYDK2VwAyEAUSg2FBR6AEzLffDVQMNsxwRrExjGgolGLyheQeHZDq0=
      -----END PUBLIC KEY-----
