server:
  port: 4433
  api_port: 4434
  base_path: _data
  site: https://guardrail-dev.workrave.org:4433
  store: s3://guardrail-dev/guardrail
auth:
  id: guardrail-dev.workrave.org
  origin: https://guardrail-dev.workrave.org:4433
  name: Guardrail
  jwk:
    token_validity_in_minutes: 30
    public_key:  |
      -----BEGIN PUBLIC KEY-----
      MCowBQYDK2VwAyEAUSg2FBR6AEzLffDVQMNsxwRrExjGgolGLyheQeHZDq0=
      -----END PUBLIC KEY-----
