apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sop-secrets
spec:
  secretTemplates:
    - name: guardrail-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:RLt88muh989Ik3sOW4AOJWF5axpV2UR6ILTh15XmBbNbami2arQi9ltdAqxD5O11ohHdcYP5ZZrYso0QlPITpTCG/9Ck5nHdKiNzg++lL9ToQQkHjOOyjgibo3RbKccnrpEAhbLRelc3uNK0566mS9HT8Us/9ikIe8Y7HPi9SHtln0Ecs7u+/D6rOIepSfb9s4XlCwrmgzh7uqCTWFf3qBwS9S1eJYW814bjl2byi8Bmb8R+8UwbMco6WqOUA40sXx0RhGiuCKjJfcQiMVf9xXbq/KNJHFYa+zvSbWvTl/+AmpCTUrnvYylBIP4ZbaQ9iY89mE39VcoGX3KFqqtQ0cKbHXeyoBPsmr3UP8AUIE4md/KhLsI34j0oJ6Ee7xs6owb3vicN4G7esjrmBQVbF3G0vkpCBPpVBjCUTeLrAZPToHoiUrt22E6hNj8W/wDIwyZl9kWBOzz9qH3SETb1kiCh8KPmaGZpTXZg8FAlXQMplfAJ6QV2BlPmFo8Ex/xwPRnmvPknIj/eyGiDU73xHbsV3urd1azW5IC5/GHwOyRa5GLqbb0rF2gewLhoRdT3hv9YvGsks5H2bu2cjjlFYDzZv1q6l++mD7Hni6DraXq0qnixiC6aAAveNBJI0xNNAXW+A2pIXlfpNX8=,iv:KqhwDucNutIThkIkTLCd7v+wEL61q4L+x5aXMD6LKnc=,tag:0zZHunSGTCZhhYnlg0Vkcg==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRCt3aXdXSElobTJxTEw0
        Yi8wMlV0TERYckEwZmZiTWU1WmppMnpxd2dRCldLOWlXTllXdFNHeHoxR1VWMlNa
        L0YwNlBuUE84Qys0WWNsM3ZBbkpUUFEKLS0tIEJTL2FNcTVNRzZUM0Ftc1c3Z0dR
        R3hzK1UrZ3FvazhmVlBkbGFTMFp2V2MKUNpIuPzp1+agM5aJ27SqoGzAK1P0vDjs
        Vn8WTGjsirF3M+1En0dztr0hgwvVNcr6mShFWzCE8DTC/kyvoxS3Yw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3b0hhd0hEVWwybSthYUlp
        UU51SHY0SjArOWluYnQ3ZjV6ZmppN3owV2xjClhLU1p6UDFkcXZTYUcyZXYySFAx
        OUJZKzJrYkxxS0FMNTZRMTlBRnIyeWMKLS0tIG9WNFhEaVFaOVI2c0hyYWI0WjJX
        VTN4SjV6Qis5M0lVOVRwNVFISHJkamcKO8+EjMHd3KTxEQm/zyN/JSkwEsh1yq+D
        ghJp/o1ow3iRoSnCYxhX61zypFNZLoHMHfrGWGC+dSGpsw3f5AXycg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T12:03:45Z"
  mac: ENC[AES256_GCM,data:vA3xuixB0UYmL25kym1Gn4pXYwe0LqNTpO53VT9ld5rBCkAEUDkoqS7zNBqYgfzYYk1gy9Fi9HygexLfGr7AGeg4n3A3kloRHWPE89TRC+BZhIK0Z5zjrAU/JjCuhsJnO7HJ5XY28KBPUL5GTIWPPOTAdDk/uIAd64j+Og1mm5o=,iv:FhaiVcfKNGotOrGbsYwt4QnYJ19pyYnGQWQCknvgcwg=,tag:edUx5U/O3WPxk6V3eVoCyg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
