apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sop-secrets
spec:
  secretTemplates:
    - name: guardrail-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:U0AMtMFhzuR4VlgVij0ISDHRQ2rC0QK7zUDl+JKasGId3iViDTAx2DVcdThQ+bqW4VNv1hVNKcLm+yjRBCoIYFp8to3z/TMlg8jbhufo+dxkXD/3cGr0YsT7kaTgshM87qRW/P9OQU05p2/+DWBIEYJIPvuurdL+XHT7rUJBsItmavpRGwumjhAkDIF2c6xOZU4Nx7zYw4zd/BzsPGT5g6haWgzOgKV1QNBTZoD/y7t+MsZsDqkPVUe7UehxGKRxNn7I9wd9WrtjOB/BvTAN8UeqzsDIh8dpLBkNiECFUsJmq0ywLWQsQI2faMqkQz+wBb+3gDgb0CkghR/cWMCqrM+h/83RRFwC0qYjWdjtO1fIvkpkn10nx0A74M6bSfCJA56/rC7YbX6LEDvvCrhK7Ki7+l1KEaVNAPriEDrtMuwhalx4JD1pGA0MQpBXUZcTI5HaT716IiQxk54TpRQaM89RPODT7roDtX5i60ZaECDCCTjW3dNob4psq/Pb80WH29gsxFOcEq34dy1xfKgsDgsqBtkfNnCntqkiok9flF8WrUJ+Xvq8QwrnTFGG3+xlUxCsUd6dStR3f7ihCb5A4JsDjhEvPjlQbGWX,iv:hjNQAodHx8EwhLF6grI/26jTfTxoFYLiz6G2RkRcPSU=,tag:E0IYJ8F+2/2CFACFike9nw==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTlpEeE9PTDFXLzJMNDMw
        TkVQZ21HMWE1T1FIM2xPMG4vM2F2MkhGdWc0CkNSMmFPRW56V1ZlcFB5VzJ3SlMx
        cFhnRTdQWUlHVzgwZ3lNYXUzTFNUTDAKLS0tIEMzV1Nzd3lGTWsrd01FWGZ6RjI3
        LzFrSjFlWGdoMG84VVEvY0FVT2hpWFEKNPCDtNBnsvIzPLvIQOXgQoYtZ8iU9zgX
        2xBcsM6VSuwB1GyWcA3rTUwwBZHMIoQxq3he7EEIkX9d/6CNXgleog==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTUdHN3RoajRnbHloTDdx
        bjBRQjNZc2thT3kwSVcxQTd4bFd2eTk2NUFRCjVTSXhKczRuYldQNlFNZXJoWThH
        OGNmN2Y5WE5uMzQ5b2liYUFzcHpBbTAKLS0tIHZNZlNGbEpPZFhjb3FiM1BIZTBt
        YUpSb1EyWktzLzlVU0NGRXMzM1E1VzgKwenBICD7gG2RnuZKlPLIQ1vETt1KAWfL
        Kd5HfuqTtw+mwKe6Vm0/wUWH7MgVtb3VBUJPuiCOzyU7zHdEzntrBg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T22:15:11Z"
  mac: ENC[AES256_GCM,data:pJckDQnTxDxrsFwz0cSuA8UtWRW6O/GVBBOK2hv4ZUUuXPEyVwuPgDF67aOM2c4gVsTzlL1anC6kofR1jaJv+iAhZAZgljdkyeqJp4cW6BJxfVaxVEmT9Ub3BqCXZqfppBnhIrw7evcSG3ulVgeHRhDLxrL3KwEkfJ6Eefv4Mxk=,iv:lBF7iod2KKlY5RYwL4WNq151k7TqhFopH8veb5Mh0xM=,tag:MWQRiT6adQ5wlKZ8tT9Xag==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
