apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sop-secrets
spec:
  secretTemplates:
    - name: guardrail-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:57riIBuEbMXfaaj9lJwSFvFzupH0VvUfWNcjE/dJRH8M7SIc02JdTprKii0u6ET9Xy1scTjl0BBnGnP5vV2bzhztDhDmjJ9jkdFW/4Zct0hc9U4M+6rU/eS0x87KGatiKbYFouRxPV/oFQz4hHHhgnMWayNIRBOogvhLvzomSzjNODU51oGpOoJiwLGWtSZfRxKfqdwVMSm9agYoVXRIYqx9WF1m33pxYqJxqW//9RT1PwPahsCh0U/mgrYqOFufS/pr/qBig0wM/xrUNcOjvbYfTV/IWm4lApctA2DVAjso93DIOx3iL0mbjvg1jvhMPr1JxK8jgWj7XV+TZV34EKKPuyYsnIDwJJjv6k9I5bP2TvMgFeEfjOmIHeerh2QVOGqy1xLEFJh1/HlsBhwBmPh8F9ylxSKgRUbar0LcTAAURD9azqaonnW7Xa86IV6o6VS/NSRJ6ICvg+zUfrSrm44sNIwM,iv:pb4Be6BhKSUTvP1YpwL3oees6joJQxzA52E9bXeotbA=,tag:OrjNMmzPjFMWUYu2kmybTA==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZFFieW9xZ3RkaWNYbXg5
        em93Ny9BVXRpeWlXS2R1Y0RkZURWSFZJbG5vCk1GOWJCVW82Z3pDMFBLMTVTOHB5
        RTU1UEh2amRHNGhydHdUaDNvd3o1RmMKLS0tIExJTTdTb0JudU03azY0Z1V2bjAz
        Q0I5ODBuenJYVG1YTzZNTG10SmpFRWcKyy5c0ajrihyJQDC57ggUpxt5r6G0NY8j
        hVXr/zFqiPBFZR/rINLg0M323I/KGYiAqDY5+4CA38hTvYkiAI/ZYQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bE9DRWxPYm1ReXdVTWpV
        QjhKalQxaTkyV0ZuWXhMUlpFVDhjMHJLc2o4Ci9KOUhNUE5yNDFhNVdDanFRU09q
        OFZqUHFhQ2lMSWU2UU9zSDN3ZFlCZ3cKLS0tIFgzSDQzZVRBTyt2NHNPVStYNkRO
        SS9yN3BOc0tOVVhrWVhaKzZZUzRxczgKLOrgju5h9ThiJ6Xb+PvM7v9k+lEpCb6J
        e8E7yRO/zjSj1Qtf2kWfqusZXcYH8dcGY3JJvGhVu8glnyxtI3xo0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T19:11:06Z"
  mac: ENC[AES256_GCM,data:a+kV7hPRKRCd23bY1kPQ7+NaMSys+sxO3WXgm7O29eDtbx/S7GOh9bt0iinUhoYGM8HZZESxuPhD77TQn3l/mViV/a5RG62c3YzS0J14NBZEporebq+3T4cN19kqvrKd7su7SzWpixV3udHvl/iAiHmO8VgvF4md0TNWjGbgStU=,iv:b58Mop61Ve9KEQRAJaDUPR4B2uFiI1nJNbTjImt3icI=,tag:fjbPpsHSis/fN6KkvKobOg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
