# Generate values by running: curl -sf -X POST http://guardrail-api/api/auth/token
# once per token (do this from within the cluster after first deploy), then
# encrypt this file in-place: sops --encrypt --in-place guardrail-setup-surrealdb-secrets.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-setup-surrealdb-sops-secrets
spec:
  secretTemplates:
    - name: guardrail-setup-surrealdb-secrets
      stringData:
        WORKRAVE_MINIDUMP_TOKEN: ENC[AES256_GCM,data:8r+2Ayoqnbto9VpZIBjUBhMZS8fmL40PxQcV7iUTm23ppJu2/lR/zAVTUKA5+bqMYJbdQHJoW0luvYvu0arWoNDRzoDRLdAEgyMobnPKfmzXXxnJteOrxQ==,iv:y4kNcCqawb/D7HCj2ReLdO1PFfspv2eRSrtoCKfjm3w=,tag:cg8BbYCju34ekQkpFJXDuA==,type:str]
        WORKRAVE_MINIDUMP_TOKEN_ID: ENC[AES256_GCM,data:KX9AC2VVmn1YwlThmIxLJFFn09PQvz/gSPf0dCUQh2PnGgy5,iv:3n0IfH14DzZgTE/1N65hO9TEbim503tanJ2hk3gSH0c=,tag:jyGcWQq8KMO00nvjYLMFdw==,type:str]
        WORKRAVE_MINIDUMP_TOKEN_HASH: ENC[AES256_GCM,data:I5PursMaUgiTapMujDcYrSRFtXov7TNjqzijwAuu4rUVjO3yMcXIXr1NEXl0zyZzYIRGDF2bAT+CcCOfSO579kj1TtwXWNqz3gsQLckdm5nDAfkgPfg3dnaYuSVMkQNAYg==,iv:r+qZ12FgpF2qmOWsqhkiD1MbZ2NlLxDNEbzKAMYpOTE=,tag:OZ6NUVjPDkOU1KkNId+o7Q==,type:str]
        WORKRAVE_SYMBOLS_TOKEN: ENC[AES256_GCM,data:SIyFVxmtYvs7+7ytL6jPqfjePMb3RPAS3CRYOM+31AFNjMgiiVXJ6bSCY/q8RLrXbFx+ATf+usxPKHayOiRWQA1yGuSkZN1Z14GFvn/o+VqEAjrrZ/sKvg==,iv:nwzCazBFfCiwgkYtv3qCUv6LGbkDiF1sHj99P49m+gg=,tag:dbvuIfNEMbsU8qoMQZU/wA==,type:str]
        WORKRAVE_SYMBOLS_TOKEN_ID: ENC[AES256_GCM,data:tIX+doBvw3mCQC/Bw7OjLwAwPQssn6ZyhGtx53UblJvGkBPv,iv:2iv9yQi2/P9CCQKV2etDgXHGlEWht6Si7lkyz6JHLrc=,tag:TNvSF6CJ825MT1bfBVCy+g==,type:str]
        WORKRAVE_SYMBOLS_TOKEN_HASH: ENC[AES256_GCM,data:kwWBEMhQNTqNrfJieucp6CyuOH5ehqqn54TmfQaNEi2UtKf6lS14v3oAmFvfLi4+65AOvh13Oh3ykJ2vMvc/UgS8ga54kCaqC9v76Iw1zhYEljg959Eq6YPuYgOZgvZJMg==,iv:ch9gVMIpGoInfhV1FYJRLMnCrXGMmKK4lgWO8/Unuyo=,tag:1NPmIl5k3lqctKasdCL71A==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVjNUdy9LMGM2bkg5dDlB
        NTloa2dTTUlFUUduQ3d0UmpIZytJM3NKcHc4CkoySEx4b1dMdVBMSDE0SjlOcXFW
        Titob1RKWm80VmcvdC9mNEF4aVZQa1kKLS0tIHZPcjFxd1V5SjNKZEZURFV3MkF4
        Rzd4RFZVSTc5cjUwTWpwSDRmZHhGbkEKy2mzlsi0yEe67QkG8oe4RRqWy+cPk9wH
        3TyyPrJA2m8+avOyV3++N/rC2HPk4cP8lb0ulQNX9+gW0t6O5VWjuA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaHBFMi9OUmJQa1lLSkRT
        bXU0Qkd5dXRKK2hDS3pMWTBHUzdVbms2bG1rCkhic0ZCNnFudnY1QWR1V2dKWnE2
        ZkIwVmRhWU8yb3lsWGs3S3FkRWJLU0UKLS0tIFlWc3l3OGc3MkVOQzF6NjN6Y1pk
        bGJMU08yN1VpbWNva2JoNHJEVGl4eWcKa6EKjU/Ch5z3wZYQMAJit3rNj14sbzsQ
        /xPE7Wx0FWk26RnKkxyxRBpNzSqf+pU9JBDloDYtWjEz3Xws78wSXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-22T19:04:17Z"
  mac: ENC[AES256_GCM,data:pi13/ik7YpbrHcgrX7ALKHa7jABeIeJFm1zX0h7FWzY5V05PeHa/t62JiC8DHG7HD5DGHytZI8oPWm52HF0lM1pKI08ZCRXmZWotL6C46IM4OqVko4BCdHlUfRDlgJfKNCcjpqvdood3ayLUBc4WvMVxBhvVGZCd+vSX1GmfOiI=,iv:bUnFjgCJyVABXQ5NZUI/mW/jk+iloOE3z+aP3LOqHls=,tag:EOg7hTMnaYKI0FDWZ8M2mw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
