# Generate values by running: curl -sf -X POST http://guardrail-api/api/auth/token
# once per token (do this from within the cluster after first deploy), then
# encrypt this file in-place: sops --encrypt --in-place guardrail-setup-surrealdb-seed-secrets.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-setup-surrealdb-seed-sops-secrets
spec:
  secretTemplates:
    - name: guardrail-setup-surrealdb-seed-secrets
      stringData:
        WORKRAVE_MINIDUMP_TOKEN: ENC[AES256_GCM,data:qkTxph9wd666fiuFvTQ9/nBJrdlH+9haE71a6X1BnNSftbagPR25xZHkN4NTLpxzAg5X0MDZF9ALGewDfXM1+2CZUYzmw20+jIKeNZWpKm2xCqMdxwO2Jw==,iv:Ycn34Fqq21P6NRL9990T8wNbMf9yUMKSOaTjRGgK198=,tag:I41tOEC6+ZPzP+Wfkf3+cw==,type:str]
        WORKRAVE_MINIDUMP_TOKEN_ID: ENC[AES256_GCM,data:b9+tBvnzPSiUdPQ6wxcizcc+ERxmrcpslbMisyAyS8OmChyi,iv:r1CB43mjTEJjheTCBAazDjQ9C3BzitfVv1mBOmJzq7Y=,tag:N1BuY+F5NsacNMFxPgv9rg==,type:str]
        WORKRAVE_MINIDUMP_TOKEN_HASH: ENC[AES256_GCM,data:GLy6iORBgDKrdNUJNw5j9KPSiRVznwXY4Bg+4T1G5WMfAMyPavv4oaqXSaGtP1TlRhkVBEogLqXblgJngPmbdqhK2VnmDNOYySq+5weprh0wr+xf0C1nWNjVV0+pNIyMjg==,iv:PJ0CFi4CoW8X0Osk2y4z3kPf9hj4rFcYPlecC6YyVxU=,tag:p5WWzA3TG5CBTAJPZIEzhA==,type:str]
        WORKRAVE_SYMBOLS_TOKEN: ENC[AES256_GCM,data:pMG/vvMqS6dcwAWYMfg+NyHqlWywo6dq0MWn5F4IVytsAlUHRM3pB2lzC//1hGOAyNPmc9ftvPjeVIdQASMETSoUbJn0ARsOx8eM7PiAU5KVMAYMSqXglw==,iv:1Sw0ZYeHdpIQPksqIss8weKt3SJgM9jwTuDNlIx35S4=,tag:yQQ0cW1941cyiMPouOUq0g==,type:str]
        WORKRAVE_SYMBOLS_TOKEN_ID: ENC[AES256_GCM,data:KRqWry81bHtfV4kk8UVN21ckNKMsqBeRyOj2DlxZoeiqaBjt,iv:+LRaNeA3uKSG8oaHbvkOdUmndlib93iswr0cKWDdjug=,tag:Uc57/AUyGkODB1vKaRiATw==,type:str]
        WORKRAVE_SYMBOLS_TOKEN_HASH: ENC[AES256_GCM,data:aBnOW3Zq4N0iBU3HvGcY+DQEe3osOyuI9AzwCz2bdvxW1tV4eCM9O1C0ZIM0gO2kCs7TXFKEAeEdKt9qoEKh5UDLT0fEEGGu7iao9MbFVVgZSWjVWzHs7m0gzkWLToqKHA==,iv:wYba/oo8wrRv4FEt4fIVCI5Yi7Yk8naOHgVSfhaQdVE=,tag:xN77o16IeZEIsw5n/ZD8BQ==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxM2UwTkpTNGZPQk53bnc4
        RXNqVlROWTVHNXh1RFB2NUhyVlVpZS9UNldBCk1MUStlMXRxSEpMUTArbmUvZTdS
        cFRnQ1NjZmt5eURKdkVQdFdFVUFUM1EKLS0tIFc5dXdsOWdFbVoyM0ZYZzRDV204
        eHRFWTU0bFVUaHBrbkdmblM0NEZlUW8K/QwTJDsuhcPu78RFPMftk3xkHfsfr8tI
        NQy6drnQfpauf3C2aOm+60rD6Nw/rrFpogXOTPDlqsogzca4KgEGuw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1K3NrVnV5VkIzSWNvdEdF
        T0J2ejFuNzFTeWhiNFowcG0wMGEzbkdsaFZZCjgzVlNxNmJLOXE2N240UU5GTjhn
        c2ptdnZkR0hhc3NocDdBWkR0UENNQnMKLS0tIElRK2RjbDZoZ2ltR2ZDSGtOZTJQ
        RVBVb1h0MjNKeTZVc0JoS0VhN1lia0EKvXyA7sbLOsrHJWn/dgvkLFX0hpuiLyaa
        RBozB7DmJL1gz0IzsPKV+eyNSgkbvZW8dPqh0GALoZx/B1QPu76P8Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-22T19:00:00Z"
  mac: ENC[AES256_GCM,data:r5O0bVjcauCPYeL4VGYwMXs71nhtmiHIsHV6DXu2sVFQjMa3o4Pj9lfhnmkoVgBj+HjWiLjTKLVR2rcZKyPbnIlVKD9f+T+t7Elza54a4Ormjy2oeNNgZXjWfpdq4UELxs7G0aac2K23lWJGv8Tm5ChDRrwqhWfEW2qYV4vkhsw=,iv:4sUPrZ+uAEyJDvN/XaG3k6O9Y210KdcGpqr2uLljx/w=,tag:LvNU+rlPZAgmbVYcR+KjPg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
