apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - network-policy.yaml
  - surrealdb-secrets.yaml
helmCharts:
  - name: surrealdb
    repo: https://helm.surrealdb.com
    version: 0.4.0
    releaseName: surrealdb
    valuesFile: values.yaml
patches:
  - target:
      kind: PersistentVolumeClaim
      name: surrealdb
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: local-path
  - target:
      kind: Deployment
      name: surrealdb
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value:
          secret.reloader.stakater.com/reload: "surrealdb-secrets"
