apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: surrealdb-network-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: surrealdb
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: guardrail
      podSelector:
        matchExpressions:
          - key: app
            operator: In
            values:
              - guardrail-api
              - guardrail-curator
              - guardrail-web
              - guardrail-setup-surrealdb-schema
              - guardrail-setup-surrealdb-seed
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: tailscale
    ports:
    - protocol: TCP
      port: 8000
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
