apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: surrealdb-sop-secrets
spec:
  secretTemplates:
    - name: surrealdb-secrets
      stringData:
        rootUser: ENC[AES256_GCM,data:dafEHDY=,iv:iPtIPzR9jAF1T56I1p7rk0xYn4RUkT5Zfy7PpgpVDzg=,tag:1vdnD9ZTzHCMHo2Gudz7wg==,type:str]
        rootPassword: ENC[AES256_GCM,data:gW4IycBw5hZqDeErJEQoqKhvCSRKQYdy00nW8YaZYQw=,iv:i2yLJfvZYMYuMG76MuffxeynuBE2EAbAa7OA5S744gk=,tag:dkNYjBSBZ9ff9lZI3vcYIQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbC81bkdUOVY3OGE5b1ha
        SlpYWEw4T1AxaG1pbXBzZCtwQkFGaDJwYzFjCjhJRlhpUzlrWjYxTktqZFlYeUNU
        Q2hCNHRUR0dyZ084UWRqYlI1VFp4b2MKLS0tIFRrQmt6T2c3NGFsbXgybDY0TWJs
        T3k3QTdwWi9ycC8yNExmNGZhZlRoZjgKNzJ2OwLLIdTWKwnah4U5rPCBF4rnqxok
        Orf+g0YOzijUH+ihf1q+VMngGmcLy7l83d8a20NMeTK3T9VE7nxMkg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnN3dPd3UxeTk5WEticXJC
        WW5GK3o4STUxYXVkZXdQRXhiY2NoTVR2SEJZCmFzTkpkN1RVVXBNQjdtc1lFYzFY
        Q0lIMmNwUWVIK0p0cm5iWHVQRnduTlEKLS0tICtrYWs2dDNzd29UWWtEWHJDZUdp
        blZ5NHhpd3d0OThpY2ZKTFdtcmpuTzAKB14HISdK7gYG9vnjM4rTJqykNLUqQpTT
        yS7wKxtZXMeBfHPz0Mqmk2JUFCSGwxK+Fe4M6mjBw7JQ7Fe6UUok0A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T18:25:18Z"
  mac: ENC[AES256_GCM,data:FrqmEQwGszrJ9NN94nvNDHWA9ZtsKziCO+1oTBKOftuObrT9ET096TkMS1ChiM4p2HLoYG/iXc6yrPkVC0JmCdZDb0pDOTk3giWNoTP5OSyD2a46yRYOi23Y/wWrtxN2dVx8Z+tVlap+vOGv18NaQdfe25BYtu2yaraumn5fl44=,iv:JoGPY0STZL6fXBS/4Ei8ws0/460FukGzBVO3iGZ+S5Q=,tag:/M5qiFHamqVtB3qKc4fAwg==,type:str]
  version: 3.13.0
