apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: surrealdb-sop-secrets
spec:
  secretTemplates:
    - name: surrealdb-secrets
      stringData:
        rootUser: ENC[AES256_GCM,data:mNgokDU=,iv:zYjI131jV3NwAhA7Pq0bKmHPazex1UOh69zoiQcgnuE=,tag:S+/IIpCEbPGhMDZZ+AKZFw==,type:str]
        rootPassword: ENC[AES256_GCM,data:iCTmXqFZfXJAI6hoKAoBSBuuqMCSODIe,iv:Wy+xBQhklKy5bNgwHWFhP8oaFYVKm++PSOS9BV8pjBU=,tag:Ud5NBQYxCN+T9rKI9NLIZA==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb2FMaXAvalBoMUZhdG81
        M1RxZGh2aVV0a28vdTJtVll4ZWp5RzlLdWpNCkJSZmhueVNEcGhZcHRGemcvbXkz
        QkxiMEQyeTR1ZnhVbmJBZHZCMlp5dHcKLS0tIENYT1A1Vkk0T0VFaVh1TEZKMTli
        L2xELytTTy9JcVRGakNFdnhiMW1RWE0K+aygTieHwHJ/rSR/UIO/cmnhE1bmTlc+
        I2B/GQq5jgHo3ra6kdR6/ebAwfKVd6/UiZLWAruO4uXuq2jOzJTjsQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdG1kdjgxU2l5M1FIRkNL
        OUkrTnlheEl3MWlGNTlQMmJ4cE9ySGFUTERZCnZtU21xR3Q5ZWZZcnR0MHdsWDdP
        MWJ0ZUNseXdJQjhRcnVEay9UZGphQzAKLS0tIDcwMEM0SzN4eTFEaGVPRllXS1hF
        K0M0Z3FvN1pwdHdKQ1hGOFY5TEtPL0UKkEXdXcrRISRTIOMs3uBTO6xpUg1RgdMH
        BY7yzSbezOooqwYwayV3YelDbG4Dc4iX2K8usN6isrS5ibhDaxH4dg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T19:11:06Z"
  mac: ENC[AES256_GCM,data:zLTXUpBkaIzNqvmM2UN2LyVw0CihLMZx0isnDE2YFOb83iHzbBDWlCGxZy8ar7hfOtVlT2+nLc7R31/dshuaihug9Y/YH7cJw5WOY5EVHoxaFAXSOOagmXF0bCRH7EgtQcCbwuczDBYpM7D4BqXMRkvHbhaMxgBVQ/dLAmGA2XA=,iv:7LWq/pblsElqq2PigZrQuS5xSLitVKXOqZlfPtUH+OI=,tag:TmxiZxtKAHbd8XWFcxNu4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
