apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: surrealdb-sop-secrets
spec:
  secretTemplates:
    - name: surrealdb-secrets
      stringData:
        rootUser: admin
        rootPassword: %SURREALDB_ROOT_PASSWORD%
