apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: surrealdb-sop-secrets
spec:
  secretTemplates:
    - name: surrealdb-secrets
      annotations:
        rotationid: c5b880b3feec58ee34f04509e65ad963
      stringData:
        rootUser: ENC[AES256_GCM,data:p+u8Oyo=,iv:b2fFAVcsD0BSPF0ruvQyIxfIWMNLGJZ7OblyxxcIqDc=,tag:x09otHWA0gaHZZB+OiGyQw==,type:str]
        rootPassword: ENC[AES256_GCM,data:6rScyZUZY8NXfxUgxXJ2PHMlMru3ACMAsv7nKxlEf/c=,iv:SjSZgkIaIhGhQEVIHoalOciM16eF0utLNUWxtjawRaM=,tag:BVcCRW90S0qQN00F38j0tg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UWpRMlVSR3BlVHJva3lX
        eGw1OXFIL1RRb3RQd0xGSGIzTVpNSWxMZDFjCjQ3Q0lEa2hQcHFRNWFQYXNvODNT
        VWl1N3JoMjVZMHhEOGl5S3NPWWpNSWcKLS0tIGpDVDgzeldiaWdGekxuUWRVbVNv
        ajRWR3RwVC9QWm1ieEdtamszbnc3SjAKuccNALeQL4oroqIiYqyI7dESR6F9d9z+
        5yiOSF53/lVw9MdjXWlFF2+95jMcq+FGZerKUrIZXrvuZjFNizIcFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMEJBbGR0SUtVM2Z2cEVF
        REFOM2R0aGVhbnc5REZDOU52b2JQeUU0SmtNCnJiaTdCUUVFOGNNdERJanpMaElI
        bk9mZWxJaVNkdFJyclppTS90Y0JhOTQKLS0tIGVRQnJXbFdWK0d5TWFVOHM2dlRO
        ZkpJNjl2dmxjQWZwTitNUHNrV3d0YTAKQ1Mdfl1Kt6ohPk0XfkKwrNZrZI6Ofzi7
        MbvktOm3N7JsdC1k8c8zBXZOWq55fC2q3rzZDcfJfdhVUJOV/XuQpw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-27T19:56:09Z"
  mac: ENC[AES256_GCM,data:18ukR80LXznpK2zXBQ1SRnBEjLX5J4cvjQa6h6wms1wizQq9pn1yf+KpPyBqm9i+bVj00D/GUVq1LPmNK8kPAbFMtxbqlLi1U5HVaG29IdZBWo02BQk7Fxc5daNotZT7jR3cbAM/sR3ti9ngHHonJNi7vAI/Rgz+THU4bKYsVgU=,iv:JXbiOQUCHB9nor+hsmUsgx85t4BOXxd4Af+dgaTErr0=,tag:hPp8w1QOAtg9S00UbiOkKw==,type:str]
  version: 3.13.0
