---
image:
  tag: v3.0.5

surrealdb:
  path: rocksdb:///data
  port: 8000

podExtraEnv:
  - name: SURREAL_USER
    valueFrom:
      secretKeyRef:
        name: surrealdb-secrets
        key: rootUser
  - name: SURREAL_PASS
    valueFrom:
      secretKeyRef:
        name: surrealdb-secrets
        key: rootPassword

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 512Mi

persistence:
  enabled: true
  size: 5Gi
  mountPath: /data
  accessModes:
    - ReadWriteOnce

strategy:
  type: Recreate
