apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: valkey-secrets
spec:
  secretTemplates:
    - name: valkey-secrets
      stringData:
        VALKEY_PASSWORD: ENC[AES256_GCM,data:7jOtSI5oVG2nAuH+YL/xnxE4b1BFe598,iv:DAE4oVjMv6Eh53sitZu4SkU/3fnTYrxe0is7/QEYgns=,tag:+9Npz5cF2DSRfOVVczqTUg==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dUVJdEF5TldoeUQ0ZzJP
        QmJwUWtseTRBQUVncXBWTUE2T295cVErMVVZClB3dzQyL0xYQTNZV3FpS0NPdjQ5
        alMwNFBUczlRMWE4MFFIb3ZCemFIRUUKLS0tIEJDM205RkZ5Z3lxdi8rWStqUlJr
        RWRWK05weGxRR3A3ZUNlRUV2K0sxUnMKpnaiBxZ4tCUx/KjNrOuQhJThqk7I2vCx
        4zuA5AviPTe3ZKYQm9ZgDZi7MJdORFeZF95D1cRDb4XX+V6Bph15HA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWEpsaXBwWHg3QTdYOVM2
        ODBDMFp3RlllZ3Fja1Eyb3lCbG1SQmJZR0JzCjFiUk5hNWRZbkxxOE9lNmtTSFBV
        WVUwcXcxOW0rQ3pKMlI3V0Uvay85cWMKLS0tIEl1YzZ1RUNNSC9tRUNYSGgvUTZT
        SFBtVGVDbkdoZjJjY2dtMDZvSE5PYnMK5B/UQn6ZmKf0cMSig02Lnt3qloZoIkQW
        LXpu+LsziY5g40cOnwJm68DDYwED8ALxQNW+VT5b49Djk+aeCB1anw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T22:15:11Z"
  mac: ENC[AES256_GCM,data:4eK9ib5lWifdeJCm4qsdQw99BajkfUQIFC5NpxdJCWmmXP+NsUCx4jHNueX/jmENeXPU+91y2fr3a4xyTuAkI3bKg9uikdy8ALydaNIohTPPgXvo/PZ+F3NftYLOWgphNN2i3SCVRDlEVEvj9xkZ7yscaxxJSoo6ui3off3OdQU=,iv:Blzxffp/+7MzgxWc+zJx97jW4NjLGuKBRqFrnHNnZIY=,tag:KV7hjgDfVMHIEav80naymA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
