apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: valkey-secrets
spec:
  secretTemplates:
    - name: valkey-secrets
      stringData:
        VALKEY_PASSWORD: ENC[AES256_GCM,data:R8NCi5y7AbDD5efmxzLrd9AIFQqLk3MK,iv:otKAGCO58dC7xqQPx7xN2fITUBx2twcBvBb2AXulls4=,tag:uUNcSFtSnBp6+XqDxMiVFQ==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYWp0OWdjeHBpUHpJZi9U
        MjVuSGdZeHdFZEJobEJUeWtkbklaUExDZ0UwCkE5ZHlIK0QraDBGaXZraktnWldB
        WTM5UThIYStJUWFDZE11VkVxYlBxOVkKLS0tIHc0ckhPcWFmYzVEZVcwd3hTTzdQ
        M2JaWXJDRWJzMHNiUUJsNm5BSUZkMmsKvxkZ07+C011VkyX5K44G8wox3fRgDHoC
        K0/pGslgDNwbhL5Vu8xdcMlzJvTZR64o03UctEcwqVdsHTeqXfM4zQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MGNYL0t0TmpHbEJkVlN6
        T3RQczFQeFN2R1VEZTJyamNvVWFsT3F4N0VRCmR0dnF5YWhZS0t6SFBHaGZGU3ky
        ZWYwaG1nMy9NS2JCYTFrVjQxNmlSN1EKLS0tIC8zVXRHbVQzVVArRU5MWE9wZ0dv
        bHBKTUF0aUhVRllTVnFDdlM5RGJPc1UKeDQu9FxUJnzWbRDl33PK6/V5Of5vQ13W
        XpFkol8tO4ylkUS059aHJKO6R/cO2XTdEkeoeJOg3zl/bxT4QyXS9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T17:21:54Z"
  mac: ENC[AES256_GCM,data:NSKKOeAEJWas2GSn6dO1yaNtETapbrbgcI5t0pahVjL31IRc3stm6NqncQSwzeoRDr9Jci2ahwPuXz3cybUDsiWkr3VuE7PfvK5QR69xhZc2exO3CQwyBhGAMV7Y6/N/NjTv6W/XKMQe+Qwwf1bEiIcYoLPtczKsAA85xW7NVdE=,iv:2yqtvK86aJS8zL3njhsZMRyhZeg/bOGb+Lw7zg8NEp8=,tag:5YLST+TS7ifcEEwyzTsmww==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
