fullnameOverride: valkey
auth:
  enabled: true
  usersExistingSecret: valkey-secrets
  aclUsers:
    default:
      permissions: "~* &* +@all"
      passwordKey: VALKEY_PASSWORD
dataStorage:
  enabled: true
  size: 1Gi
resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"
