apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardrail-jobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guardrail-jobs
  template:
    metadata:
      labels:
        app: guardrail-jobs
    spec:
      serviceAccountName: guardrail-jobs-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: guardrail-jobs
          image: ghcr.io/rcaelers/guardrail-jobs:latest
          command: ["/app/jobs"]
          args: ["-C", "/config"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: secretKey
          volumeMounts:
            - name: config-volume
              mountPath: /config/01-config.yaml
              subPath: 01-config.yaml
            - name: secret-volume
              mountPath: /config/02-secret.yaml
              subPath: 02-secret.yaml
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: config-volume
          configMap:
            name: guardrail-config
        - name: secret-volume
          secret:
            secretName: guardrail-secrets
        - name: tmp-volume
          emptyDir: {}
