apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardrail-jobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guardrail-jobs
  template:
    metadata:
      labels:
        app: guardrail-jobs
    spec:
      containers:
        - name: guardrail-jobs
          image: ghcr.io/rcaelers/guardrail-jobs:latest
          command: ["/app/jobs"]
          args: ["-C", "/config"]
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: secretKey
          volumeMounts:
            - name: config-volume
              mountPath: /config/01-config.yaml
              subPath: 01-config.yaml
            - name: secret-volume
              mountPath: /config/02-secret.yaml
              subPath: 02-secret.yaml
      volumes:
        - name: config-volume
          configMap:
            name: guardrail-config
        - name: secret-volume
          secret:
            secretName: guardrail-secrets
