# Generate values by running: curl -sf -X POST http://guardrail-api/api/auth/token
# once per token (do this from within the cluster after first deploy), then
# encrypt this file in-place: sops --encrypt --in-place guardrail-setup-surrealdb-seed-secrets.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-setup-surrealdb-seed-sops-secrets
spec:
  secretTemplates:
    - name: guardrail-setup-surrealdb-seed-secrets
      stringData:
        WORKRAVE_SYMBOLS_TOKEN: ENC[AES256_GCM,data:MMm7kpc0GoOefpiarJ4Ne0h4zGHC3Ayi1UybK1vgt2Xl92hTGYJN4MQUVQKOLfS+7S0uninVJJ3NGG7siZ9fssY+8gBbJWirGddbUDKMyPfkqwZZqtuQEA==,iv:7AnaxPFvCqw9W0LGbvIEnLgJG2gjVShkCa/0XfWUTaQ=,tag:O21cp6KVrcafMlE96xU/ug==,type:str]
        WORKRAVE_SYMBOLS_TOKEN_ID: ENC[AES256_GCM,data:IS65CJQTak271WG8zm56DWxRK3QjLx9jAjpOoG2QPZLRs8Fn,iv:NPfrThhoT+uBvrF6FSi1KO4I8k50l+XdwE8oJm5AlmQ=,tag:hHgBpZkptMxV1BjbWJNXTA==,type:str]
        WORKRAVE_SYMBOLS_TOKEN_HASH: ENC[AES256_GCM,data:ia75dWTawOj8NfrkK0/US1dvhe6mcFPJkJE9N6qJQ0TQN45E1ODn9sHX56/z1mNuP9dQVb5tdo8d/0xsg4E+hTL0ZmlcgsedRO03hMbt0Owh0K/fqWvJqkzJzYzBy3Inaw==,iv:aqHzvT9Ui0QtSNA4H3VVyeEx/XJPfiBdTbKBb9ywUw4=,tag:Cmk/pPZffpWnnhWlU63msA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTkFwclZjTW9hQVdsMkF0
        MDNnK3hsNm5mUlQ2Nk5RZW1hVXJOWlRuZGxRCkZWWG1vMnFOZDNsRmZsQWI0bTFu
        RWVBdXZtUUJGSldHTjRCc21GSjNtRkkKLS0tIFczdTRsbjFsc0xZZ2E5SWhmb2dX
        U01wSnVZYXlkVjhhYWxDejd2Q0hYSXcKsFEsFsuT7BY+jAIOAjCeM0klnTpvPCkv
        tCzo6G+y2jI8kIb59C68tJp6vMbyjXwuKGlfdYZIiJqJpkZkrvO5zw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cW4wcEUzUENpeWRPUGZv
        amNlRkFNNWdodmtDdEpDWmNTbVRNKzI2UVNnClZDdlFxcGZFUWFnNUx1NGt0V2xR
        ZUYrZmVoMHdKdHlnUkxUM0JVejVlT0kKLS0tIHZaUnJxbElBNi9HbllwZ3FmandD
        b1Uya3Fad3h1S3Z4cWxYMVBDS0V4eGMKezp+zd2LdqB1BFqRGb6QcS7vUWwuhrwG
        kztkD9Fghyyz/mQVAOhpPZTDx1e3ZuFRMn64J0ZBS0+vUOisevbEnQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-14T18:42:36Z"
  mac: ENC[AES256_GCM,data:+V1Eziv+moZSWIaVctRatD8p6+USquGJJiectGHVLN+KAiy3drMRKUBv5qSGGqG/6Jz3Ic+X2IrdF+sztR/A5soIQFCnL6VdBF87XCoyYjy7IbIQzu3GsPZSR8FFq5FjBOjNTs/rIoYvU2kTGJciTEawowA9UdYQQC0aTMydjDM=,iv:zIBy5mw+SnI3h1xc/FWVZwUb1dJ8CsDDI3So7RRC7/0=,tag:vjT7aqfOFQe5fgKlLUL9cQ==,type:str]
  version: 3.13.0
