# Generate values by running: curl -sf -X POST http://guardrail-api/api/auth/token
# once per token (do this from within the cluster after first deploy), then
# encrypt this file in-place: sops --encrypt --in-place guardrail-setup-surrealdb-seed-secrets.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-setup-surrealdb-seed-sops-secrets
spec:
  secretTemplates:
    - name: guardrail-setup-surrealdb-seed-secrets
      stringData:
        WORKRAVE_MINIDUMP_TOKEN: ENC[AES256_GCM,data:z3MdpLQkOCoa6LcJdDH5NOE0jaOSI8vN1EwJYtALjbGKKVka56qDNYssOXyaOj22Fld+XJIl+Et8hxD9yXeXWAuB71Ur6QBWHehTnNyf4H/dzHzD1YnFxw==,iv:KqZ77DGGSeXbQfv45PF8JVDigBe6vwgofena3VX9lLk=,tag:YPyg4C0hcet/cRU1Pmo1WA==,type:str]
        WORKRAVE_MINIDUMP_TOKEN_ID: ENC[AES256_GCM,data:XzZF122nQVTk5WUvbQ+txsW3x5BJpKcvwS914WVMJS7k6Zdi,iv:54cHbD6S+T+hioynsUlu/fBTWPIOMf6e4keUO7gCno8=,tag:QhiKyscJJc0Gb8iPAua1Cg==,type:str]
        WORKRAVE_MINIDUMP_TOKEN_HASH: ENC[AES256_GCM,data:0PXmMylhtuzaBifctIBNaM5PvjAuOKGXs1qjdHqxR1H/ymnf8ArAUH2du46Ur7Y/+JQ8R84dMUeeFF0+15wGzXeuzc0WuB5UTj8gC/zUeXJbm6Ux8yIln5204OE0+/irPg==,iv:7j0pQ2cBRi0W2Pl+x38Tn3J0UK2fEt5snLhw2pzp+FM=,tag:WU/MlzV9xPXvY4MTkcYn5w==,type:str]
        WORKRAVE_SYMBOLS_TOKEN: ENC[AES256_GCM,data:lSQiaI7FeBA2pM1fOx/VxDJubn8ZlDk8aX+3C+r4LOayogh94mfPo68zVZcxkKwYh70TgAkUyssrLKZiLV2aJ5JTn7jPujTkCjQDkU/CXaikXAbLzWcX2A==,iv:1/79Q7rjx223RWj0N2JA6MkUAlRYIJq2VPTQiaqI5N4=,tag:JDmyCxlD9IKZZyt7KV/7YA==,type:str]
        WORKRAVE_SYMBOLS_TOKEN_ID: ENC[AES256_GCM,data:qr+HTw5MsHJbIuInPn/vMV3xIj29WhTKaR+RJGmzpUFbXrvt,iv:rgzrwbwn60bvp00Mxmxc0MsTsJsLEGNajDNQzHb9R4Q=,tag:yvPkC/sZUCxJzmqPgHmGrg==,type:str]
        WORKRAVE_SYMBOLS_TOKEN_HASH: ENC[AES256_GCM,data:30SXGrjMQwr6TEK/IV5sRu7/GtDNoPnWrMRULvWlYqDilVteg4pNAa4RB8nUIwOeeGF7Gw6YMNc71ZKX1mTZjZ0gNH4xGT0/E5AmSVHwRRnOFDgUSNtQerRYVp0qE/4YvA==,iv:Gwt/O35S1KX/fgvmi+HlznDmtlJ7qiur9X9IsDBT7lA=,tag:wY2oW79RDPNifC9TAQbyew==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OE1Bc2c0MXBKSTdyS1hT
        VlY2UXExeWVkS2x3VVNQOGErR2JBVUNuYlNnCnNJOUYyRnFueFV5NzM4TDRyZURG
        OE9mdHJrKzk5S1JTRWhqd1VSc1VTN1UKLS0tIHlSQ0JJSThma1UvdVFUd0RYL3BD
        OVJRRi9ZOXVXc0t6UmUzRHdDcFZONFUK8p50PE3tCmIjsDZ+EP9L4zKfYQEGyvFB
        UL0T9T9TlOFz05aj7xJ9qLFVxLw6OUuD5/AKSxvbxo9OoTCjfopwiQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWlowTnlla2NHbnpXcm5j
        Nnlmc1E0dXczZUgyRkhSZ2NDSzZxa3RqUEdVCm5aOWxHbkVweVlCSUxjUFNodzhH
        Qis1VUdvSlI5dVNmRXVPSGNPTXFTcnMKLS0tIHUwSDBycGlPRFNFTVpTM0NPcHhR
        UE1Tc0xCNDhuVEZXV3NiMm9TbXB5aTAKo6WAHqZRbeE7Re2Ufd/30RtKrgEvXQYR
        ZPQKyc5k9oDgwXAxeE7SH5vzMu81wzPH5s+q8DtJaa4mPgjQmkhGhA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-13T20:39:48Z"
  mac: ENC[AES256_GCM,data:6CsgN9W1ReldEoYjYBKj2B934GAO1eiJ48Ci5nF5En9Vef4/RMdp/rAJXhwbWG9ivJ4wA6WP/9BOy0OxFT/mb9CxfyEPmjHkWH3w2vNPzn9GIBJFAxPR7v0C8SGxP0IKSoa3eA7J9fNTFiwINGlkdeyBRIiQ9jOqABHlMgZAi2E=,iv:mXkQI45hHhS/EKxP4KJhbV8zggw6oZR9X8+mWWaOMOo=,tag:F6PtVgLUTOPE3Y1A7NXhIA==,type:str]
  version: 3.13.0
