apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: letsencrypt-prod-dns01-patch.json
    target:
      group: cert-manager.io
      version: v1
      kind: ClusterIssuer
      name: letsencrypt-prod
