apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardrail-processor
spec:
  template:
    spec:
      containers:
        - name: guardrail-processor
          image: ghcr.io/rcaelers/guardrail-processor:production
