apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guardrail-processor-rolebinding
subjects:
- kind: ServiceAccount
  name: guardrail-processor-sa
  namespace: guardrail-prd
