apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: postgrest-sop-secrets
spec:
  secretTemplates:
    - name: postgrest-secrets
      stringData:
        jwk: ENC[AES256_GCM,data:PbmonfvsFUwuzoB+9NDpVQHWISE/RbGCGjbkgMeJVXSeKgd0JZFpwOOHJHSuFn+3/+wiinzszCo8rf21Ef4bJLiCQ6hKMecqj05zbA9uew+AfEQuKb9LARTfsTe6WhMmls6RU1Qr2/LB6brOFQw7t0Ad/Xht1QQdLl3PpcM6EX7ZZR1NTuhMQk2TAjBJU8OGHSj2ldyq2Cl37vTOCT/MGlkXEdorsXL0QyfDCG/ecUmbu8ZQucIy,iv:6ms2H1sZ5gt8SGX6Yh1IiymhxGpdKF9VeIdkSK9B+AQ=,tag:FBVLPD2Mnq5JuMWWtZLNdQ==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVUdybEUzL3ZsOTIvWVk3
        MU5oNTVxK0c3U3orUWpjclZ3NlBveitLTFVVClF6RWtYTUx3Zm9YYjkvbThvRjBt
        aE11VndnNmdiMlM1cnM1ejE2NGRrZDAKLS0tIEJpSHdTcXhoQmd4ZDFhcHFVK2dx
        TzVpSTFIbG5kNEYrUlRPYVJ1SFpJN0UKMqiTPSz+JDqp6SuAswJabufltiSSsbCY
        Atw6MXQJwMSCK0/ZCF+FDbu2I2gbmc1VjLrmCQH36srIUZ4w9Z4T+A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3b2FQZTJ5OGRnN1Y1c1ZS
        VGhCdkFKQjhhRnhQQ2JMTk9zRHBsRUViQkhFCjRvdUtXTXJKdVBTS2YxdWl1UmR0
        WnFjdFB5Z2x1MER1MG9qR0hWangwVDQKLS0tIE5mOEFnZWxWN1FYeHgvcXA5ZDZL
        ZzVSYUNHMEFBRTdodWp1VDVVK1M0ZUkKHZdTtuH5gnL7GWBTffe+Cvmg/S3r+7cp
        39+IhJXu5kZ4Vl2hDVSk3Li7WsUZ2deHyZJN/PETQYoh3DPL5ICoSw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T22:15:12Z"
  mac: ENC[AES256_GCM,data:tBd1fxo9+IV2RqeUTzWRFAenfApaGqksAjrJSaCMo5diCehwEyIHwtemjyJtgnZ1DPKOyM3W+/p54ujs+pgh8Qu5PBrrUTDRuCdM0mCvaNdWKtmSE01Psn6oDoAVuhd+3zPHqhXsLV9fU60Jn408TNkFm/wosOhZamW/Mohz9W4=,iv:XDQzIVslUdNvc02iW87ai4imCK4roAKRCMafhlZbcKc=,tag:66pqn51icjp3RGQ9zO4xwA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
