apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: postgrest-sop-secrets
spec:
  secretTemplates:
    - name: postgrest-secrets
      stringData:
        jwk: ENC[AES256_GCM,data:pdu7bJJUhOwJ5vPgpsaW0kDCiOvUGBAxPSoSRSHKYu++VeLjUv0DLwnp8WxONsm8PFVeQrN2uwaHL4wrU0bw/IZR6tR/L6H4YdtQE05Pr5FDVWcj5FEuDY8Ee43TZ6aCRznTzz6di+SvgZkBQo4oZeJq7YiUsPOa6gz37O8+EnCCUfUa3GtmmcMMDXnf+N2CQrD8lyyxk013/4pP2kKoGvhXDzlURt4RfHVrjiUQ54b12OKlaEs=,iv:kwbLHBIDZvU0YaLiFwl8HwYkenOcbSfDUzSFDj4Xes0=,tag:eM+gYV9hSlO8fgO4IqIGRw==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaHlNRE01NG1XeWw3amVX
        ZGlLQnVjOTZRaFd0R2hNOUpMNXpnMnlSaGo0CklNVnZxMGM0RXJHTVZNbkJYSHJ2
        aDhJRVhXaG5ncTlxUTlrUmh1emNuWU0KLS0tIGJwemRCc3EwZDU3azJmSXNwUS8y
        RVRxMy9VOEdFUXlrYWY5WHpUdDRHVGcK3LQEtuqxEBXwUzyhEYp1TbvDkCQbCY04
        zhKhWnA76b0KgJQwH67J0pbZUtT2GEGz6wxH6IhNuCYGJqTYyZLN9w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSERpOEhPalRUS3k1Wldm
        a1dmaVFNM3dmQ1E2aUEyNll4eFJ4SEsrUGpZCkxuWllCaWJCK2hRbkp0b0ZBbzE1
        K1FZWVFOQnl3djVXYTJYN290b3dCMGsKLS0tIEMrZTJPSVU2ZllZalNaWEh2clpo
        UmIyTnFaZzlGbVdVR3BxZE11RmlBb3MK5EW0ou5/oqI5E91szaR4U3kbowyEB9r2
        gO9l6pKF5sxKZlWIpmRwxN9SxgYrNnLycqX5mPqxj0YS7PIAr90FAA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T22:15:12Z"
  mac: ENC[AES256_GCM,data:DDUyZrS3cOJwkI7kC8xB30/SI+VBsmLd+dAP5/Yaeuh5jgr4lRE7b5saxCRFD+G1suHFuOSbcfPjTwoOY14cixwC2NWccHHf+SqT2cyRJEw+s5nbDrAAGZitD0KpwVIZ1Nk3rLNZ6++WltvG3bGjBu0fri8mECPJN+QFpmvnGr4=,iv:lI3/J5cD+zg+TCQF8t/4JbX4XyL6gwu5HvZTbTEPagI=,tag:0Q6VIhXFX40HMeLKT5LQ9Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
