apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: quardrail-db-dev
  namespace: postgres-dev
spec:
  storage:
    storageClass: longhorn
  superuserSecret:
    name: postgresql-superuser-secret
