apiVersion: v1
kind: Secret
metadata:
    name: guardrail-db-password
    namespace: postgres-prd
stringData:
    GUARDRAIL_PASSWORD: ENC[AES256_GCM,data:ltclGflhrfbMQk+4zM1aXKKKLY+ZYbNE,iv:kDclSUeovdhnAMAQvG8hZSAlIPSoLKd3GND1gqLCoyw=,tag:vva1u9ixz3EvIHdhbLioeg==,type:str]
    AUTHENTICATOR_PASSWORD: ENC[AES256_GCM,data:drcYFqZ3a0ALGk7vDzbIhOlQevtIgghS,iv:wmLPpeBysHwLxJCzLl8nmX4w/4KutEvpCiMZg8I5eR4=,tag:TyEvjP+M9CtNvD/ef6YlCA==,type:str]
    WEBUSER_PASSWORD: ENC[AES256_GCM,data:hdtpf1o2Qn1CxHVMRLNT+lON+4U7SyLb,iv:P+TtxfGoq2xQ79rcHADW4YCBHj6e2Lt0g+o89PODBbg=,tag:W38j9ilvgKCrqCgZif5p2g==,type:str]
sops:
    age:
        - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaDZZdmIxYWFoZnhZQ3Vz
            L3h6eStsZVpmWk5sdElJYkpPcThoM1dMUmlBCjR0UnUxTmR5a3Q4ck9GT2JHaWl0
            SmJwL3pHQ3NveDVOb253UjRwdnFiZFkKLS0tIDNiWUdtNU0vQVF1eGRkejIzWlNU
            eG41V2EyU3FESllwTUNuRG9EZENNWHcKJRMmfIpP5CjjlSnJ7YwfBbeo4LpFwpat
            krufeasVYcuMqZRIbuq9iYITV1mg0A4VYi/R9erPmTqmNm1v3i2j+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONml3Tm9TMmRFSWlMMG54
            VlVxSFVaOG12a3lxK1VHWVhKaWxlbjhsWHhVCkFGcTFHVmdYcGNndUtSVjFtWjln
            bDN1MnBjQlVjbTh3SnZ2eDZyKzZyQjAKLS0tIHNJYTRVYlFtaFNhaFNmc3FXajVT
            U1phVFNGWDlLdXNUTUJnZzBrMXdCd3MKe92RC4TFT2aEB2S7xyQM/WY8ohGhl8Zi
            ZZe7VghOhADcOgxfTzWwGbLu2oDNXaMj4/fZkgUfPAxeaHHNODekKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T18:02:41Z"
    mac: ENC[AES256_GCM,data:qBg3c1YN7o9iA7D7Aue3ERbP9ZRQa4IlkesMp1D/hIXbeYGUx110oqtm8SbY0+vSV1lSSG5ZOUlH/vOWRb9TfsjeQkwSk5G5NrarCqnY1V1stCvQjKd8FMQ+L5TJ2In+1GIH0T2rYE/lTacM4iI4Y4U2Zs3iKr/RKwFhdn0z8FI=,iv:UNZ3OxCwucmi1DyMtO+EWWR65UoYOieqMzo1Q9fng60=,tag:e9cLj14Y23tFfFpEGEz9kg==,type:str]
    encrypted_regex: ^( data|stringData)$
    version: 3.10.2
