apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: surrealdb-sop-secrets
spec:
  secretTemplates:
    - name: surrealdb-secrets
      stringData:
        rootUser: ENC[AES256_GCM,data:dn4gIgA=,iv:tO370FA7jion73bl79llDxxbXTLy5c9Tfnt90189DZA=,tag:PbZ6Vc7xEmSzroN4Eg828A==,type:str]
        rootPassword: ENC[AES256_GCM,data:Nhe3cUytwksIwNnKtLjQoCv1P59ytSuy,iv:3vCGubvP66svysrf5QJJ0U8iZNsBIXJd6wpASuorSaE=,tag:9NOoj8uhPtSkHyAyKnQXVQ==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEakM5QzM4Ym9va2dyeWVp
        UjBWNzY5bVpoS2VXNndTZkxBSm5mY0pIa3l3Cm9JeUo2OE4vK3dHZHo5dHZHQmIz
        UmVtbTNXUDRyQlZkakxoSyt2dlB5NFkKLS0tIFg2NkR1ODdVSUN4elBPTUVHeWtX
        MkxaQjBDcWQ0VEQ5ODlOR1N6SlNsSGsKm0IqRslTZp9e6t/qYdqMNqIEyWmz4DSF
        /++pLiipxYMlss0u3/ZmXH85XRRdRcX9BQ/bEkOfVy1wnAMJv2n53Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cVpFd3J0bU1Bdmxrc20v
        SGQxQmlkWG5kVi9jRkc5QmYzdXpNSmJsRlFFCkVNek9qVTZ1TllWcjdLOEYvTmZU
        SXJaWmExMWV4Wk5TT092MG1CLzBjQzgKLS0tIGdDVU5JcVViMUxHeUtjeEswenZE
        NlQzZXlua0pjNVdVajNQZ0FlNWZwaWsKU49MtWOTIZCnSKGye7dDx1XIfTzej8as
        AkHiizYm0kT/qTPb+jXNaLl9uN9Vw0kaOKDvK31gni9j+JZ1svNCeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T19:11:06Z"
  mac: ENC[AES256_GCM,data:mlHnr3A0gTrPcQeKv6krelTFBbtthGdC7c9HPN9JJZ+EZr5f+9x7SIbJgkZfO1OPkVABcdX2aopmJ2HwVWMju3pKXz3xJOh21+B6gm3/bH6njPpy6JaPKVdy4CkmZeVRgQ7RKSArIcNhPpRdMxiGD1ayH3pWKc6clzYQbTJjIpM=,iv:Gb7HH7PY3eJcXyLnx3QmtqEHt+UA/0Y4dEf5+KsRb2s=,tag:XHNM6WNdbnuMGQ8150/8hg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
