apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: surrealdb-sop-secrets
spec:
  secretTemplates:
    - name: surrealdb-secrets
      stringData:
        rootUser: ENC[AES256_GCM,data:i3SLeDo=,iv:nGJZLnOynW909wxV2JSXlQqCF/0uhPqI1G9wmX7LDeE=,tag:VDx9eychrq57022lgIuvmA==,type:str]
        rootPassword: ENC[AES256_GCM,data:2KI9MbC0CaXTBEaIdvB6dCVGVmj32R9c,iv:C58AxDqZPhhcuxhVIXftKKsTTvipgOMPPsjnrpu7RiI=,tag:t3gZWSj90xaMhs3V8V6XIA==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WlIvMHlCWUxNRTRmcE1s
        WlRiZ2dmZDJpYXFadnE2Q1VkeFJEY0kyZEEwCkRPWEdjQjFtclBZWjMwRjVsTDdM
        MnYrWStSQXlYZURTbFlPSGl4bWR6dlEKLS0tICtudERtTGt1UjJkRHZkeGNiMU9I
        a25QaHZLWitueWJsbStOcjFReS9RVmMKS/o3KyABkfGoNTFYlrZeM2cid0p4sGqQ
        awFiopSYbChAgG5Y1rqDa8t92Mek7hzVaCRleMaSUnekCWF+8b2NvQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqc0xLeHJ3OHpJWmF2Ti9H
        RnRPaGFIeDlxWGxBRS9GeWg5bDhmb3hrWXpJCnprL0NmV1lXWlJ0WmtXR0tvblZ4
        c0dxNm5UYkpTRUpmL1o2VUYzZjBiOG8KLS0tIHdIMGVVQ0d0MVNFamx6WFVEazBD
        ZjlWcmVCVUlublNqczM1NzBUOXJDUWMKVI3i9Dd14TTbPi4DlMUfzbikIm1aj/S3
        MfhjnWFe5fA3Hj2LRVCoZeLLCSvY+XZbx9LK+4CGUgKEvZ6YltUeHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-09T18:15:32Z"
  mac: ENC[AES256_GCM,data:lUnTaxdzTOcU2AcOyCkByDQvPjkAQspEiVG0NalF/Y2cub7f2UHBb/Uk8BsyKju4yxrfGjS4BTHUSUSfs8zXvShRrwTd0gBTVOuGDcqJAsCwF3GWCkndjAkAVZraioDBcjOcMMcCTDPHDGjHAIvRXT8wOuWKuJYKZqDM+9nuUUY=,iv:ijxm8+UH2Av+apECg6MHs61kp3oTHeQT3aWd7x16J+8=,tag:wEbpDprrmbxJs7LDOGjfpQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
