apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: postgrest-sop-secrets
spec:
  secretTemplates:
    - name: postgrest-secrets
      stringData:
        jwk: ENC[AES256_GCM,data:RJeOwZoDA4OriVtJqZ6MFbYZtI2rtVfHeIPjVK0zvY2cXJEN5PuhXr94fwzS2lQVvIyBPmr8vRzV4335gIMjOPhlk1S/L90qD5hfmj3RRqVHNVpQe4ohnK/pmwjLxTcd3gqLqMSy7BJJle8VQoTd/Nx2436IO8u0GeTSezuX72XqBYgWpWo8oNNrkWAEuMIR4au6XZLIpNO11erz7VmN0ByF2BM5xdAnv+m7KQUe/KspKVpUF7o=,iv:Nf5WmSSkb0SCaXIBiv7fz/9pCnjPS7u633CEQuQjieY=,tag:V6Ua5Ts+4Edich2B3M117g==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSitSY2RwZFRDQ0hBVjZE
        YitwVUZtdW05dUZTTXlOdXN6dktpeFZNQkVVCmVGMlkzUXA2SEJZN1VDMzFGV0pI
        Nm1hTmgxSTBNcjZ3bDJvSGlvUFJoOHcKLS0tIFVyZXFlb2Fwd1plbEc2K3pHM3Nj
        T2NMZHhFa2dVRTBtRnlqNk5oRWdpcEUKJbONskQ8opRqHherEvCXWx4vVv1nPKJi
        MaL6XB8PzvjHBm0dB+dgVOSeu3HVb1kMPcCbk3GV5rzy2/XlrkGVCA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUWVFTUIvZXdGMm50MEEr
        KzZrSG8rVG1PYkJ3QzhpWitYSXdpdkozS0FNCjlsVzBObk1mR3k1bEJQVlRPZG5m
        U1d3dnFwalg1aFU3dTJtNXllaDUwMDAKLS0tIHJLUFZEVDNVSnRHeENYTmIvTExs
        emxGZDRXS1ZhTmd0THliUGVCV3RBeG8Ktxl5rUB+wxpLzEZR2qpytAQJOnvnd59V
        ZrX/nP6k+U1dJ6v3PWg/McYME2+YSVaCH6TayGdsaOtu0+xFJBnFfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T17:21:54Z"
  mac: ENC[AES256_GCM,data:SCsQ0nzaV45GCeEYtvSIkV8Oz91QBxHAdLL+BOqE1pELWoR5fsulIVPVgRQP67PTYI+mVex+obLprRLiCmM9hgR25OntfsPmigVPzamSp7NMEqCUhqpeo2QsvsJBDfSxEuUxgcfhEBWIORkolsqUyMNK9QMtGWybBp30WOncKPk=,iv:x8MEnWCh4NshXhVUrtQWIh4TEFKW/dQNfxU5YMultEo=,tag:FO5lssLXdb/K6Bhafq32vw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
