apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guardrail-prd
resources:
  - valkey-secrets.yaml
  - network-policy.yaml
helmCharts:
  - name: valkey
    repo: https://valkey.io/valkey-helm/
    version: 0.9.3
    releaseName: valkey
    valuesFile: values.yaml
