apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: valkey-secrets
spec:
  secretTemplates:
    - name: valkey-secrets
      stringData:
        VALKEY_PASSWORD: ENC[AES256_GCM,data:k5tsGNYb/RVXJGZf0LAFMd7tynMPQ7Vm,iv:kuZN9YpEXjeHit+OiDWKr5x7d684AzHqqe5brjjLavQ=,tag:svCGigHJC+b2zoemZ/f/Jg==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwU2hYVDRuMFN2RFFFcVpS
        MnZlUlhndVl1MkxjSFpRM1hHVEo2K3ZoTUNBCndGUCtHM0tIVG1OUG9PZ055SDJ3
        TithWGZrSDVuMDUrbm5HRFNsUlpuNlEKLS0tIEpMMHEvZWgyUGVHQTRXMkJOK0hZ
        ZkRpcUQxWjBFTVZxaCtlSVF5WW5XclUK5mLqWmWMyfk1ryrPJP/ralZiO/YcJJsB
        goypswJMLshvKXShp1igk0W3mW5U/0IyLk38/nEFhHNrrvaR5AdwaQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBud3RZQ2ljU1FWZGl5Q2g5
        YVUvQXkzWFF2Yk1yZFhEbDZMZTg5cEtDb0c4CitiZlRJMjFBTHdMUGxKQjBudHJK
        dURDMUx4MU42S2JTYkxycjBtZDNhY2cKLS0tIFBIVVoxUzJFZ0RzRnM5amt4L1B6
        Nnl6SUMyRmk5TVRQSVRiMi9RaXJDQ0UKUZgKomV2pFCVXozU7WtGPHchVFnkXKN3
        k7jdbtozfbzzixxbU4TNWFit+kb6OLTTBYjsC0U+C2U41tGkf9gLFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T22:15:11Z"
  mac: ENC[AES256_GCM,data:yayop9sPHqIdevObhJPS9OUg1ZvXKh28OxNH8IpBjLA3Oe/Z4U76pri7zNF0eWrkx4s/2vR8RC/evO1y2gCwFErPxEXcgF4bne/0AD9y4D2gTqgShyeg9Xp3jT1eQWv2tV6fhiH7GmbiQ8dDdtTeaozgQ7x76LpZTz8gBnmGoUk=,iv:1yZ54zld7X6/sUCagIF3SNRp9+eU8aFhQS11zKoadvo=,tag:ZzXIYKv068NU3oRCSVeiUQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
