apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: valkey-sop-secrets
spec:
  secretTemplates:
    - name: valkey-secrets
      stringData:
        VALKEY_PASSWORD: ENC[AES256_GCM,data:Q42qLfhLY8bwGmX9M4sQ4H7wBm89VuI3,iv:9mfBUHFQQuBBmyIfptBb+TsdYAeKW7uXQqOV/Pow0T8=,tag:dN6q5fSBRUsBiLbFB4qx+g==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMWgzdE5NMTBIZTJxQko3
        OVhyMnFtNStsNkNNNzRKbGdEWGdOOVhqam44Cjg1c3ZYTlhZVE4rNThPQUtDNmlW
        ZnV4bm1pOXBPZi9VdjBoQzB1aVBkaTgKLS0tIDllQklRRXFsVEN0YVRHR1ltc3Rx
        S2dzYlhjdGhOa0xJRzI5VTFHamFpeGsKPF/YaKUhzYq7dVWyR+o7uFZGGLzDZPv0
        DauvK65tIYRWwo15qxRTXbXXLEm8P1TPqve47D1Pcy3Ay5pzy4LVAg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdGhnNDRYc010SjBvOE4z
        THV3cDVXaUhXZEFUVDA5bkNhUDVOdzZNQlNVCmlkVTRseHN0ZWR5TlF3V1BiSTk2
        c0RENEprWGNhc1BSZ0pEdG40eFc5R0kKLS0tIEdRZk5VRStORmp0b2lEZXFwQjRK
        QXdwcGU2cDlCeTlVendpWDZhU3d3VUUKdBzDudY7wetMittOurlODjQNak+51Lq1
        syorGaf1OgY2lyuUWIK/pU5fNYQ3TVOyAty4Ee3vO+0BvAHG0b/8eA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T17:21:54Z"
  mac: ENC[AES256_GCM,data:Bh9aHHAC6ArsGTbjLLfBmfazRcjhM6NtCFE3gXFva3u6yanVscOep4+b9vmKaosRH2Fz0ST3JgOfdfm+/ozxUY55QrwJgtnpekF7gLWVT+EWQ6mOD0PQIfygLtz/e5lDvTJdE2m2px0zqa/rOTIKeFBE3NW8kEw1y8IGEJu1oqY=,iv:FpjisFEKE1NsGHbqOQU/8cojAWiARZRwLx5Rmly/ptI=,tag:Dh/XMbtgbQc9MzcTV6zHXA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
