apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: garage-secrets
spec:
  secretTemplates:
    - name: garage-secrets
      stringData:
        accessKey: ENC[AES256_GCM,data:uRTryATwDwFVCHtduTmAAt1F1xM=,iv:6M0AW9ewyEIHXwprvrjPQ7TbssiRmdH+j7/X0CzJYZQ=,tag:nT5yzHgFccra4HE5Nwfkcg==,type:str]
        secretKey: ENC[AES256_GCM,data:BIk4EOznN/M521PXs4eA6mOzkcmweEr4WQgdkv7flFnHO3n4h4559w==,iv:Q2fUKIw36PLZZN94oLrnR1xfkg6s3DEX9W3PfWrbS3w=,tag:G6QezssUva81YK5hTGX0Rg==,type:str]
        rpcSecret: ENC[AES256_GCM,data:UN46DPzwO5SxLe07Jr0Jx4/rWcbqmuSJz00+bM/ibOZ4pEU1NKdc25AohHj8MfhjZHIP2pXUUpn2UPKCjL3ebQ==,iv:t2nVKneXkFkr+CPt38WSsrla3fc/oGRo7b8zPDusCGc=,tag:j1MAaJnRPsOaUDvGehbcTA==,type:str]
        adminToken: ENC[AES256_GCM,data:/DjsCfrIKdelo/dOrzSc45No49iywLels9U18h3ZAgzm/vQFqn9+8V+9gcA=,iv:BKynDyf2nit3gnCbGmbdnVBCKia4k6xekbJYd+UjGng=,tag:WBVKcqAYCvUDoaNricfyCg==,type:str]
        metricsToken: ENC[AES256_GCM,data:ElLcE/pGaQQWA4gQf9Vg8hffLcHYoVFgwApJ2vo/XWWZraTbCBeNXYOy/jg=,iv:CoZnBxopfD/pGaJdy4LaG/KR4yfGlJBqkMLeLiHrJEc=,tag:W6HJH2+X7CO7qvh5nOwdZg==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWkFia3BBRUxPRFFEZVhG
        SDUrM1BWd1RuOTRWeDZoWDJyZWFtek4vdWk0CmY0TWg3SWVBNDJLSUpPMldnMlBw
        RDdPQ3hqRUJZa3NoTGs0ZnhBKy9MWVUKLS0tIG9PQkhkNjdyWkJQS2lhME9YTG1S
        QlVaS1VJUzBGem8rblA1aFB3TXFhVHMKHHMP5/JON4KVlWfJUIsCXPfW8dohoINt
        QnmtwEAnOs1kGIoht4/or9X+HfMCU3kYWiOHdgt7cigsPT83bMzc7Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQVJvNjdzZ2I0RERZOCt4
        QnB2TXJ3amlqV045cFJCSWtteUZPSWtqczE4Cm1uL2hkTis3R0taV09adWlhYWV3
        bDhEa3VVOVlrOFpIU0pEckp4aFhUMnMKLS0tIHRZZ1k5eCs2eHBXaXVSUkRJZlJ1
        djZPMzNibHBXV0lsT2ZyNkt6RnpPOHMKoJsqCQ8yvbRPKwf5uY8eWh0LIzva3i9s
        VtMk763fNkRf0G8cVDs/VA56GG/og+whsIASzUxQbDD7y284ZCuaPw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-29T20:43:11Z"
  mac: ENC[AES256_GCM,data:MYOdFK9cfNt4d2VVljqE55S76QA8oZDefDVIMljNj5F5o8Q/k6HLeWFB8V7GMpNekO/3G3GbDzNIFVVy3LQbVY5noX1XcRleCDdLubwDoDF8JFq7btzImFV7Syf7gxE8jIwrxkn7Nf8FAkMJl5Nl9N4Uo6e36Ai/Dw3t7vwOFwY=,iv:eK5uSRKTWwLy2TeGAqCyMwPg0dOco05oRlHzv7bSYgE=,tag:pYvL1EtMgjsmEbG15NZsNA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
