apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardrail-curator
spec:
  template:
    spec:
      containers:
        - name: guardrail-curator
          image: ghcr.io/rcaelers/guardrail-curator:production
