apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guardrail-prd
resources:
  - ../../base
  - minio-secrets.yaml
helmCharts:
  - name: minio
    repo: https://charts.min.io/
    version: 5.4.0
    releaseName: minio
    valuesFile: values.yaml
