apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: minio-secrets
spec:
  secretTemplates:
    - name: minio-secrets
      stringData:
        rootUser: ENC[AES256_GCM,data:fTsI3gY=,iv:O5bWrMOtcRBdJz/zlm3mlY4+Ra5a2l4FTwAyTAQFRsI=,tag:S/w9yl0VVcujtcUz5UCmNg==,type:str]
        rootPassword: ENC[AES256_GCM,data:bewzG4YycsoQ5OQKi3xUI3rr6Y0=,iv:+mkPrsyqgLkbUeDr+DWHb9Oh09dHBqz6/iMzc0fbLDk=,tag:XKCT0RAhawfwXC5sb6I9QA==,type:str]
        accessKey: ENC[AES256_GCM,data:X1Yxe/FWHy/Ji4vfkbBPoQzrDvM=,iv:CfhdvF8t4J9JtRQ4v7+PMX2BIHNmb1C2KqKX/TsLUtw=,tag:vYXjD3UXvh8bKfbKTpGXKg==,type:str]
        secretKey: ENC[AES256_GCM,data:tCGb9lOKYz11u8dbzgm1mP8FhrJft6DsJRAAv2zeWNrRZHIow7mGOg==,iv:QEY51hGUQbL662gc/ho+OvRIeQ27JK8TvvPXcLY0o9w=,tag:02CkSzm3HTvtAtUW4eEsaA==,type:str]
        adminSecretKey: ENC[AES256_GCM,data:Z4IA2aODVWzdRB04SbIDVcwbmVBUp/r1QqPiAKaBmtrI8112Ru8CRg==,iv:e0xkTARyDNYDuT5nqernc6PUEQh4W6zZRYxvt9D/ons=,tag:GRs3NZJTr+uXZAa3jSkNkA==,type:str]
        guardrailSecretKey: ENC[AES256_GCM,data:Vp5s6rlzBSdd+/Ke5aYeBy5/NuEzWQoLGgLt/EINBTuF0gwDEfYL8g==,iv:vjZxQjOtBRT/BUY19J1O10xZ8ygROIVARBakUsOQF/I=,tag:JyHlhocAatQVLZq6x+5n2A==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcHNGMmlyeGNkbU5sMWNQ
        K0xhODZEYXpUM0E0RXlueFJ2Mlp0cFoyZFZrCnpkdlYreDhLRVhnTThoTDJEOW95
        VGxmOVpiMzJzcmswTEgwZGFrUjhMcUEKLS0tIEZKcmFzN29sbHZ4d1hVTTJ2cnVC
        QWsyRTY2Yzc3cU9vQUE1SHRYWTBCaHcKjQQ5kjr1xRxa41P9GYCrLk0mpy4RZE3W
        PJrdr9K4xXIzvzYiq9+vL2aTbhcUDEUKJYnMgzpofkXso6TfjjXSUA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVzlzTnJLRG5DUDVMUmVI
        UTcxL2RVRHo1V2NUNzNFZUVEOFU0S25ISmlBCnhjaG5FUXBnU3I4R0RsTUVlajN1
        TjZFVWdkRFhxSlI1UzJWVllTOTc4VU0KLS0tIFlGS1ExcUdBeXNTTVk5ckhZQmJE
        aHBWbkxtb2JZakJlRVNhTXo3dHA2UkkKVgAAx/0rj00MNRU2R474w2g69jY5eruf
        XlzDlwTt5zIof/A23nwq68f7B+PSKrQE9pcXeKZcm40CaAIhu/EIOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T17:21:54Z"
  mac: ENC[AES256_GCM,data:zKNeOm/XNLcY6Pd4kOykY5+NGMyRDeytZmffpiP/Crp24DLU0i1mhiFn7ukTB/EFLM0uxLWu1DUcvQf/MwV5KqgPYOXBqwX70SvLkySrNjYNkF7f47P7g44nWhCjcCMqwmJQEJrrDneM6tgE3cFUEWVBX1sbMaYt4gsu7dOSxtQ=,iv:BCr5+7ZrtPlqSq+ecat2JnRfesfHYT0zkLxJT8QiXrY=,tag:605OkfQpGqDHCFT4HG1xgw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
