apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: minio-secrets
spec:
  secretTemplates:
    - name: minio-secrets
      stringData:
        rootUser: ENC[AES256_GCM,data:dn1NhI8=,iv:AhqCH39nrwzi6ha5CY9bFHLmiQpSvTxBPHqF9FnP0Qk=,tag:LUtxpmW/QcPQwnQxvS/Tfw==,type:str]
        rootPassword: ENC[AES256_GCM,data:Z/R+yUHuxeyeEs9NWIUGjAGqLUo=,iv:VcybPofTma2FX35w2Q520w+XmL3pJbe3i1Ccu9zxqbI=,tag:WjXsTfWu++6RkxWKmdPixQ==,type:str]
        accessKey: ENC[AES256_GCM,data:hkG5h/OuRIxxseMNW8F6UmVttCg=,iv:hdp8Kpj/McfPEoj2cRIXkXM1O3aDcp0F+uwV1f/2eBw=,tag:iZ9pQvFI7jWe8AFtSL8UYQ==,type:str]
        secretKey: ENC[AES256_GCM,data:gB5MNfygQe8a+aSiiw34qjl26k7EiSrfok62kq/3gmIHV6FsQUltBw==,iv:lI7b3ZMyQeMZZK63DKSe0bQ5aD5BMgm47SiiWoBxWoc=,tag:abqR/GlOI54Cc3k7/1s+bQ==,type:str]
        adminSecretKey: ENC[AES256_GCM,data:TOT+Vyi1roGDAG6AG39SKa8YqTaymw8o0IiK+FaUVQgB3qlIftfJ0Q==,iv:QeQppnGFdIxKTkYvj7QbugEcraFIhv9miWj4oeSFMWc=,tag:7/LG8Z5DYGBUM664IUst1Q==,type:str]
        guardrailSecretKey: ENC[AES256_GCM,data:AvSd57DtsLJgmiH1PZ6mUe+6oX0mqDbmbNemZTYICDUc55HPbn80nA==,iv:GvD5IohRvc4C6aNnTi2q3RNymHXS0K1vm56IZ07jobU=,tag:bpfBExY7m4sCUE4pg5FsCA==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxd3BvYU1IVWE1UmFrY1hM
        ZC9PU1VkbVZLYW1yakM3RFhYNmNrbnlJZWh3CkxXeHloaXBYRnFuejFoUW1ZWlYy
        Tm02U2wzN3VXVTNSeDZPRkhScjMyN1EKLS0tIGhYdnFERTJ1TzNLWEpINkRLblhN
        UG4yRFN1WHhoTi96MG1oZGltRWhTWlEKZEMCvtjzu9oLPunPKoovcP8R5yXuEgT+
        kpio5T9yHwGovvkWJlXcPqypFQRRaEjEjS8akrtQllSDrxZSKED11g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNzVvVi82d3BvRms2RmdU
        U3BlNFBTbzBmOXRHTzg1cWNNQzZhelRickRFCmE5YjZaVHJyZ29nRDJBR2ZZOFdN
        ZXRZQUh5QzlZY2lqTDQ2NlU0a1Z2ZDAKLS0tIDlnSnZXZGlncW5UUmJlaFE1UGZH
        WFlKaFZ5ZkVMb3V3WlZBdmpQVUNWY2sKbDmBwJlfJHaKCphMFh2gaWeUj9+O4Rpk
        L6MPWB4Z86dc/coK4u+PgRiRP1RuaPb+Yk0K3JNyK4PQMOmCx9oSaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T22:15:11Z"
  mac: ENC[AES256_GCM,data:mGiT+2BUQ008XfE2BfTXlUjdQ5Yx9c87HSDsjSfog+K2TbTzu62HJsutvJMlAhp63bQlUw/QCmcVaObeMj2hI4SUi3HFvcRIJBZNK3coZAgldIIAYH12O4J3/yaXTB+QSdBnog1LOwPABj/w4fmF8pkxVYO9Bzap0L0MO9q6IzM=,iv:sQ7eAwG626wmMQA9CWs0WmR2nut+60FLQCmD1g4SDB4=,tag:8PPQFo4hD2kif3wHM7b0kw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
