---
mode: standalone

image:
  tag: RELEASE.2025-04-22T22-12-26Z

existingSecret: minio-secrets

persistence:
  size: 5Gi
  existingClaim: ""  # Clear any existing claim to force a new PVC creation

resources:
  requests:
    memory: 256Mi
    cpu: 50m
  limits:
    memory: 512Mi
    cpu: 200m
 
policies:
  - name: guardrail-readwrite
    statements:
      - resources:
          - "arn:aws:s3:::guardrail"
          - "arn:aws:s3:::guardrail/*"
        actions:
          - "s3:*"
        effect: Allow

users:
  - accessKey: guardrail
    existingSecret: minio-secrets
    existingSecretKey: guardrailSecretKey
    policy: guardrail-readwrite

buckets:
  - name: guardrail
    policy: none
    purge: false
    versioning: false

consoleIngress:
  enabled: true
  ingressClassName: nginx
  path: /
  hosts:
    - minio.workrave.org
  tls:
    - hosts:
        - minio.workrave.org
      secretName: minio-prd-tls
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

