apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardrail-web
spec:
  template:
    metadata:
      annotations:
        secret.reloader.stakater.com/reload: "guardrail-database-secrets,guardrail-valkey-secrets,guardrail-object-storage-secrets,guardrail-oidc-secrets,guardrail-jwk-secrets,guardrail-email-secrets,guardrail-provisioner-secrets,guardrail-rauthy-oidc-secret"
    spec:
      containers:
        - name: guardrail-web
          volumeMounts:
            - name: rauthy-oidc-secret-volume
              mountPath: /config/04-rauthy-oidc-secret.yaml
              subPath: 04-rauthy-oidc-secret.yaml
      volumes:
        - name: rauthy-oidc-secret-volume
          secret:
            secretName: guardrail-rauthy-oidc-secret
