apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: garage-s3-host-network
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: garage
      app.kubernetes.io/instance: garage
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              svccontroller.k3s.cattle.io/svcname: garage-s3
              svccontroller.k3s.cattle.io/svcnamespace: guardrail
      ports:
        - protocol: TCP
          port: 3900
