apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: ingress-host-patch.json
    target:
      group: networking.k8s.io
      kind: Ingress
      name: guardrail-web
      version: v1
images:
- name: ghcr.io/rcaelers/guardrail-web
  newTag: 1f7b5c6
