apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: pocket-id-sop-secrets
spec:
  secretTemplates:
    - name: pocket-id-secrets
      stringData:
        ENCRYPTION_KEY: ENC[AES256_GCM,data:q4E7Vdy3XrZCmZ3u197aI5hiak2J1SwYqlx4uUsE7MHpE9i+7LorhAYn3P0=,iv:JQM4qJhJsNUyiuKFUle64BOFP4+Jm47RhSQwsoXNeVU=,tag:ahS6ZMd1DDGSp40PXHpptA==,type:str]
        STATIC_API_KEY: ENC[AES256_GCM,data:7NI4mRoWk1GVEae74C3PGVHqInPQdg0QccEJio0ubXs=,iv:SMRgVtI+EDZN4lG3V4R3OlZGiJHlaEZj4PplRqKwOqo=,tag:iX4zXvL6Ffml8YACxh/lGw==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SEVvQUg1amFsR0NDZnRI
        K2svUGY5TW51ZS9pN0ZkbkZWTEhBQzhYNUh3CmlvYkdNaEhOSjJ3bHRONFl0c1ZV
        Q1FtK2p6VEswTy9UaGNsUitVTTdBOFkKLS0tIFZnOGJvbE5PRzZwR0xncVhiMG15
        R1hnREVpRm9ySkIrYlpvMDN1azBXTVEKsbgiD0cIsMc1+QIeEeL3A31arH/v9nVg
        RyxGQJgyjQM6m68TIfFr45V0vPPcL+WHnR5TGXUbbgnPmBSTNLqADQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVERCOUV3NmtGSDA3MTlz
        MXhmRUhLUk5tcDAxamkvRjNXNGlCd3NQNFRZCnJJRVNPVUI5RUp0c3pESWM2MHRC
        YnRPVm1JYTFqVmxvamNWdWNpUk0yV0UKLS0tIDhVdDdpSHlld2IvVmJjTmsrKzRz
        eTQwdHFGSXAwNlJ4eDczLzQvZmJ3OVEKEAbX3JhOkSU+DSKX54Kzs6O6c/wk95vD
        wHOcpaL8JY04Zy7HhPd1FhfikrlaPyK4Qpws9QaqC5jx9ElW0f1myw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T13:48:44Z"
  mac: ENC[AES256_GCM,data:vL+dBa5J6mVdMGmmiQER6q755ftEn2VACOL+OVjY2+7CKmrLjLqvnZrTUas4V86Fs0qRza96gKBNSO/d6wKSj4ewgc/P47d4msp6jWLbSQHs9k8opiegAXi0UZltBo8HZxgh/kbFDgj2IarT86S0wRB4goCFB32o1uBSVXVHNsM=,iv:+Iblm7L+HkYtk3qf764zQJGV3V3L01Qmgvm5hKKQSuE=,tag:rjgMA0MUApPbOtE/ZS2cmQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
