apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: pocket-id-sop-secrets
spec:
  secretTemplates:
    - name: pocket-id-secrets
      stringData:
        ENCRYPTION_KEY: ENC[AES256_GCM,data:Dp7o+zEeweFCc4XV3+zYhwcLGykskz20FY3skuzEi9rC5n4Etv4waeOfMw8=,iv:Y4MVhBKZJnKzVoL8172rTiCN3A7izsxhlXmhiEN6Dig=,tag:UD10BMSBQO13tsTGxq/SRg==,type:str]
        STATIC_API_KEY: ENC[AES256_GCM,data:hHRbLFcydOWFocwD61X4t6XXrFzUoX7GbzRpvCVUyW8=,iv:aRch6U9QzyegzbJZ2oiIpLFVaxdlWrRF9TIm+5w+uEM=,tag:O5d6o8LOM4RY5x+0sgYHnA==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUnV0OVoyT29ZaG1nU1dG
        K29SSlZJeFdUQ0Zoa2p2azA5S3BjMEdJM1NNClNqaTVqVlo2Z09LbDl6RDloOEdl
        QjlmTFVQd2RYdm9rd1ErR0M5cnBaRVUKLS0tIFNsaEprN2tETGtKUENqZ0E3Szdx
        S1lWWjJwQm41RCtYZjY1dkFGRWNzYWsKrymaJkw8BJczbmmF7oU2oOFgyvriupXq
        Sx1Jc+gilT9CZ+OlBCqoTn+mBaS/avcucpzrUfLccM+nN/ZlhBF1pQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRb05kNUtOVm1JdEF6YnZr
        THNQelRVMTRqb0F4alVLMDdzT2loYkNob2xvCnZwUDNGcnVCMWx0SHJtUDJoeUwz
        Y2gvSlBzU0ZXTGxHazRjQ2d1RzR0bkkKLS0tIGg5ZkVtQUUrK29RQjU0ZDJpL1g1
        THN4cW1od29qVWhHa0Fpa245RndrRjgKPUfm8z9hsQbC0NAn+4ki3MwpxJxPv4IW
        h9m/G8uUvX97C0hMjO06cEnUOxJefRq7KYwL/Nzoq9J/IMlF75EOlg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T15:29:49Z"
  mac: ENC[AES256_GCM,data:zNZG7ljeHAuxaIbHQDDhKX35upEYSifEhVsenERZQ8G9xF7USeOqPyXCWcNDvBB95xk6IzYEDNa2scUYgHwaxBF17imTgvaZcq1F9qn78CcXLz8/1sKIL5tCqQLudxQDsA9BpH+zZRGiwxC8NwvRczTZLvttb6VC7YWuS7YdixM=,iv:BgQdsG5b0hh27fzti+2egdAw9MrKao2BMsjYGzAwlbc=,tag:pA/n7KSGQeZJivG71gcd2A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
