---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  ###- garage-development-app.yaml
  ###- guardrail-config-development-app.yaml
  ###- guardrail-surrealdb-development-app.yaml
  #- guardrail-db-development-app.yaml
  #- guardrail-postgrest-development-app.yaml
  - valkey-development-app.yaml
  ###- guardrail-processor-development-app.yaml
  ###- guardrail-curator-development-app.yaml
  ###- guardrail-api-development-app.yaml
  ###- guardrail-ingestion-development-app.yaml
  - pocket-id-development-app.yaml
  - guardrail-pocket-id-config-development-app.yaml
  ###- guardrail-web-development-app.yaml
  ###- guardrail-ui-development-app.yaml
