apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - pvc.yaml
  - pocket-id-setup-configmap.yaml
  - pocket-id-setup-job.yaml
  - pocket-id-secrets.yaml
images:
  - name: ghcr.io/pocket-id/pocket-id
    newTag: v2.7.0
