apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: pocket-id-sop-secrets
spec:
  secretTemplates:
    - name: pocket-id-secrets
      annotations:
        rotationid: 65b66ba4d5e8287fd49a277116f3a924
      stringData:
        ENCRYPTION_KEY: ENC[AES256_GCM,data:KYlwiOdgfxIkyfY09wcmWFqi7zknam4PwivLJ1j+Rw7Q+wJtxQN/r6RJJqQ=,iv:ZAXesoGkNLZNcrMlL2Pww/IeAkT0hkX0QlBSM4hrs78=,tag:IuRjeF8id3L2HhatYMK8Mg==,type:str]
        STATIC_API_KEY: ENC[AES256_GCM,data:EzNH70g8pj4LcmsLLhwENWbEwe73pMlVBQU6grPjlIs=,iv:Ui9nqEinV9jgVu7PG3vlrhygfhWLOe+ZZ5kHf6jKFIg=,tag:8a/yOxVtW2I4fq9mTMK7tQ==,type:str]
        SMTP_PASSWORD: ENC[AES256_GCM,data:0nQRfO3RwZXKwfW8jRoUhkwrzu9J4VDwgd61UXDb5K6x2u5M,iv:UfYTjkIaFRFZ2BdJ5StgUG629oXY195aLL+ueNg6kMI=,tag:HM5VCJngiFLhuAEjkkogEQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0YktEMlY2aTExODFZQVds
        dXg0c01HQlQ4K3V0a2ZDMFR2YzgvOE85c0d3CkxDSmhYSFQ1ak9mS1dNcWV1ckpz
        TTYzWkNFTHdYVU5DMWsxSWF6Z1FuUHcKLS0tIG5USnd5TEhCT1FhZUVUd1RFSkx5
        OHlpeWlCczYxY3dkWVhGRUp6aERDM0kKTmi7IG75vPtM1k5Kl9tQhlhWrV8xftCo
        0bsHJ5wBgIvjbSSwQAcm/+NBP0H5cMNt583+y1vO+UEnnYDjN7zcPw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbjlSV1d6aTJybDJ5L2xp
        NGlaam50Q3JndUtlMXRybFg1cjJtczZlT0EwCmJnNVYzS1F0VHAwelIySEJPRFdk
        ZmZQT1dOT3Fpd1dQV243QXprSzJuV1kKLS0tIGpSYU1BUmxNZHFsYzhVc0cxY3hQ
        NXptMmR0U3VBQkh5NWlYOWk4cTE2UlkK0XAxqBT1h73MltKz4abuWDmuviBSZ5gs
        NGqp52OHfgmNUurRaXmCir1k31W0RKpfe8jWrqe/nkYCxsuFgFH3ng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-27T19:55:39Z"
  mac: ENC[AES256_GCM,data:J2n05jeYHzROoHiq38hmoyCj0+hRwuawLKOLsOFdnautesL6DvfpruE94Ol0wWH7mYEPQ2xy92kTJegKHiRvtFCNcQYmPtEzMrsjHhOfiV0/gDBJDvLAucLEvO1Gm2vJFc7SncuHYktfxrAC2lr9AOl21M699IvZ/NSna8pKuJo=,iv:kQVlZT8WS0XN0QF+Wn4d3szL0jEtjTL4H6Jvtgj0RoU=,tag:ogxDiD6CYxX/p5xLdqXWCQ==,type:str]
  version: 3.13.0
