apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: pocket-id-sop-secrets
spec:
  secretTemplates:
    - name: pocket-id-secrets
      stringData:
        ENCRYPTION_KEY: ENC[AES256_GCM,data:lHGjvghxey7ruxVZX55iIX4/gIdt+70MoFjF12lwI/+XHOcrW8VOgOxa02Y=,iv:37DVp93lhVssPqHfzwk1budp0Fu04a0fz20FoBoAPcQ=,tag:2eyYdBhZW+KgduC8Sz6J1w==,type:str]
        STATIC_API_KEY: ENC[AES256_GCM,data:6240O2IP2Tr9G0DIOtTL8KqhpAUQlriEZKkCjQshbmE=,iv:Ui9nqEinV9jgVu7PG3vlrhygfhWLOe+ZZ5kHf6jKFIg=,tag:sRxRZnP46gO8bKi/ffB3uQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WjFXOXhneCtSOTREVmph
        RjBCSEdWeDRCZnhhZ1VLV2VFVEh3TXJuM2swCkJpZ1QrMFNlVkFuT3AxVVNDTExN
        Zzl3emNEQ1lpaVhIaDlOOVkwRXF2Sm8KLS0tIGQ5QW9oSkl4OHdNSGtIZmNXUWIx
        Mkg0R2puR1hDSG5TUmVDWG9hZkNQdmsKkChn3vBkoDKYW7r6D3b7TkDL+utrRyn0
        o+D4Evx5V0CvQ5d6cKsnuxVGAsPr+MnstxTgPLReq/fS8LhihD1wMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZHFpalFBdGlBcUZ3amda
        Ly8xNlkwMTVWcldRNE9pa1pvcy8vaE1lU2pvClp2T3dKMHI2bnl3S2NqQXhudVdB
        UTVWU3NuZmswZUNqOXhFLzBqODNjeDgKLS0tIGc0ZWxObTliWWI4YUJwWXJTeENR
        ekloL1grMkpxN3Azc1Fkdlk1dXRqdXcKRQAPyeR7OF6UcG8Y1vit/bPRhof1xv9t
        YTTuzoUfC+PqXlp7GIqkaaYAudEU0NpnF2BKU1+yg1ARQjoAN4ONEA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T21:13:29Z"
  mac: ENC[AES256_GCM,data:Z0eqKWkMlhUdc8BUIMRmlSU+x0VRRDjFEquFk2ZaPP6Mo83opt5IN5NjPowbdU4Fr1PcUddn8aWWF2P8GfYBom/aKWOQ+CvQMENOiqj4PEcQ+yrafEJR1DB+hulhLj8TmA9DPatbTU3++sgOf3rOvA9p98mrskbLAWjUAY45OfI=,iv:kYSF+JEF13rvkCBfOehPHSWs6U1ce7JKrNLZLhTcBl0=,tag:wg+9ZRfr8k0xXEUdyOYe2Q==,type:str]
  version: 3.13.0
