apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: pocket-id-sop-secrets
spec:
  secretTemplates:
    - name: pocket-id-secrets
      annotations:
        rotationid: %POCKETID_SECRET_ROTATION_ID%
      stringData:
        ENCRYPTION_KEY: %POCKETID_ENCRYPTION_KEY%
        STATIC_API_KEY: %POCKETID_STATIC_API_KEY%
        SMTP_PASSWORD: %POCKETID_SMTP_PASSWORD%
