apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: pocket-id-sop-secrets
spec:
  secretTemplates:
    - name: pocket-id-secrets
      stringData:
        ENCRYPTION_KEY: ENC[AES256_GCM,data:dGiRx3I2IXAH3zZ91iGkcQ0PXTjxvTXO3wBVCvkrRnxEwHnSK7rX3gJaOwI=,iv:LLKPPSw9xYlqbdbN9jEEZREzJ6QJJSRj22gjh5isc5M=,tag:LO2MzmDzqCIPZXorLs33Rg==,type:str]
        STATIC_API_KEY: ENC[AES256_GCM,data:AtyyvjZ6z2ln+jc/Zb1m1iy+2HI+fMEDIYktopY8j4Q=,iv:F5JD1uyw4mN+kJnKIYPc5rwZpXtJsdJHDkajyAuoeig=,tag:DKWrFBnxYBHTPAqMI7rsjQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZnpSMVNPUTJuRFpTNVhz
        bGlhazYzL2NwTXN1WnB2NVF3YmlJZGJ6eEVNCnFSQTlWZC80TEJ2b0dmQ3hhYXRi
        SXJ5SzFoTHQyd3NoeENwd1VPTlpQdmcKLS0tIHkyaFptRm9GcWZ3WW1YelFMNk82
        R3Q5TTV6UGpuSlBMdmI1Z0N0MkgzR1UKZEKxHZuR/QMvgodm5cY6/sQuLHfRAbGe
        VZ7+1MpJNsJufPi7lJH878FU8B5Ly5Vb/hS5nZ/aIsW6fHgQgIfLHA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWlh5cUtvM1B1YUl4TEJU
        cE5jcDVOVDByT2p2d3pKNVYxQndDaGpRaTA4ClJKR0xRZXJzSnFVM0dvNk5LOVUv
        eGJxenY1VkplWmY2MXMyVlQ3dlhaSkkKLS0tIFhOS2ZmV0UwZ3RsMFJmREplMDlE
        VmxEeTduYm1tYStGdDhzeUZ1ODE2OGcK995Ij00eISZeQ3PuxSC9DyVaG2wHQLEF
        /OyKOXAlVyRYjfoMcTBBXgffYnSVRIO5v2sMPAEvqkYCOePGrr/W6A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T18:25:18Z"
  mac: ENC[AES256_GCM,data:kM01yaljc+xXcZ0pLCCjWumYsSELZcyg2pv7WPA79kyL+jg9HX4gyCjQEcjBMt8UEUf4jCXor93jUB7C9EXD+q7XCvZjOlmCgoGtyKXFTLZZrn/dRZhu0m26iBJmouxSzmGbVg4SCOipXbJoTqYQkvZSmUbry6dtRsQsQi2CS14=,iv:l/Jv2iyqgKpj/QiVjrHtfHFtbFdUYQDFDBovMnXUtWM=,tag:mVM8+IdvAHxtqKUKx6RONA==,type:str]
  version: 3.13.0
