apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: envoy-gateway-system

resources:
  - ../../base
  - certificates.yaml

patches:
  - path: gateway-listeners-patch.json
    target:
      group: gateway.networking.k8s.io
      version: v1
      kind: Gateway
      name: main-gateway
