apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-config
data:
  garage.toml: |
    replication_factor = 1
    consistency_mode = "consistent"

    metadata_dir = "/var/lib/garage/meta"
    data_dir = "/var/lib/garage/data"
    db_engine = "lmdb"
    metadata_auto_snapshot_interval = "6h"

    rpc_bind_addr = "[::]:3901"
    rpc_secret_file = "/etc/garage/secrets/rpcSecret"

    [s3_api]
    api_bind_addr = "[::]:3900"
    s3_region = "us-east-1"

    [s3_web]
    bind_addr = "[::]:3902"

    [admin]
    api_bind_addr = "[::]:3903"
    admin_token_file = "/etc/garage/secrets/adminToken"
    metrics_token_file = "/etc/garage/secrets/metricsToken"
    metrics_require_token = true
