apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: garage-secrets
spec:
  secretTemplates:
    - name: garage-secrets
      stringData:
        accessKey: %GARAGE_ACCESS_KEY%
        secretKey: %GARAGE_SECRET_KEY%
        rpcSecret: %GARAGE_RPC_SECRET%
        adminToken: %GARAGE_ADMIN_TOKEN%
        metricsToken: %GARAGE_METRICS_TOKEN%
