apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: garage-secrets
spec:
  secretTemplates:
    - name: garage-secrets
      stringData:
        accessKey: ENC[AES256_GCM,data:nQ6b9pWfeTtOqdxmhoXvdkxlJ4FsmxmwQWQ7SsQkdyfgWg==,iv:gp3rMJeUWmJ5PSyaG0oUEh8Y4FnC3b6Vwsr3Y0yqpS0=,tag:IElNDpQOsK7Cl1pyyjw9ww==,type:str]
        secretKey: ENC[AES256_GCM,data:oReCJGgrWNT0Lq+BKCXZUmoUdAlLJp1NMqBYbqUqTzl3lKR0FLbb1rADvOf5AYl1JzioOXWzyPjjwl4j62jcCw==,iv:OED9kPW8LXl8zpLn0gA/Cx0LYyAgZ8goMxkkOofagx8=,tag:h/hGTuVvqq+5XS4m3aLxnQ==,type:str]
        rpcSecret: ENC[AES256_GCM,data:ors+ojJU1ggwr1AX6hJyQnZ7RH249PNg0iacmiE7dxgpGGxP4xhYtJbcjdE1gmYY6JYbUzrlbYI8JWrzLTq0lg==,iv:VVSISSEUDF/aO7a/rq2QsmYE4sTst1CiLabJIKXsFOE=,tag:oorehY2xDwPo4oNejjF8UQ==,type:str]
        adminToken: ENC[AES256_GCM,data:vZ2bLctCcxwWaQT7joFf5SKXVVHnUj34GZuuVv9zwgMoK6MjHqLLDvMewqk=,iv:aH+f/2HHX2wfuYQWvjuHeaZ4/wu+GMtETAugF/ySjCc=,tag:rLK3qehToHOxqcWAXw70nw==,type:str]
        metricsToken: ENC[AES256_GCM,data:WXS544SRlJ7yCbKJkAeMNuetbbecPRvPSg/G4FC8rNEZfIvMqZJZ2za6/Bg=,iv:OSrc82EaeYnbbgUN+5giTg3QFVC8TynTLLojsFB/8J4=,tag:2OoLw6I5t4GuGTll3fEZHQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKa1hlMUpwaElJdU1sNnpy
        ZXp4dUV1WlhPb3FoeXVYS3VNRis3UEJHY1Q0CnRJSzY1K2ErRVBkVzRwbDZuNnB4
        VUh4dTNlbnhWY0ZEVHQ0S2NNbVphUkEKLS0tIC9MSFRlY2pSUE5Cd0s4aTJLc29o
        SEdsc2FDelI4Rm0xRlg0OXMwcHo5M2sKcGoxtSTvGnJjrXcSCDl48t+WqsRwx371
        ZggoQJPD7mnCSIWFfKe5gZm/Whbr5FIvuWd24ZtKlmxFSuA93f1wCg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraWhSSlhSNEZncDZuQU5m
        MHAveXkrOEs5NmRiVTYrRDRSOCtvQW15Y0hzCkdkYkVMUWhmS2o4ZUJkU1J3Rjhj
        RTd0SjJ3YTU0a1BvdzJTQ3ZYdmhBMFkKLS0tIExMb25ZM3NTQVBlU0ZaaUt4VG9G
        dUkreWUyMGhFSGNJSHZFYXVUdUlPY1EKQyX5UVScZuqPqhJjUjRjkB4ud87dYuse
        Smn18eTyK87fXjpdIfUCLsLll2UNOdlQo9CRdDsrjT1y0Tfzrmxilg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T18:25:18Z"
  mac: ENC[AES256_GCM,data:9+QzS/iKQdXAv/sd2cMPquhOWqmnCETq/TVa6rXUxPMibFRWM9eppXcHV2zTPEVyCtcozFSntYhC5EH1j6gZs4S+hYOEMb0DTGVZSgxA6H5rOCOqJbwg6rQ0BlxTGdgCLQ7ttksyy4BTHIUmX42TKoBc/0cLVk8qtO7q73tcloY=,iv:txP7MVj9XbZfndCBOHCYwMIrvc15ciq1dUGskeg1cDs=,tag:pN6PtsnjsVjIHLvucIkThw==,type:str]
  version: 3.13.0
