apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: garage-secrets
spec:
  secretTemplates:
    - name: garage-secrets
      stringData:
        accessKey: ENC[AES256_GCM,data:Pc7jKIB2d6v3oApS4wmkJBB+PbYAPVc9HViIyLwza+Fuhg==,iv:hMQn+wktsJZ11JEx3RHRieuungl1jLo3c2zqnhsPFuE=,tag:amB+ZyYEv3T9vwwskaIaIQ==,type:str]
        secretKey: ENC[AES256_GCM,data:uG/E4PLD9yQvTsSOwL29NVDMxXjvbi7Rypz51SWRbKKPMtr2o4zeDWjcsM54n0KWY4U1JelmobmN0IWn8XUq4g==,iv:grRNVCo+JhGGqpt7QaKana3JOCjeJ6vb93GEXl35Xuk=,tag:V4SJe+j3OMiCwP5vbBY8Aw==,type:str]
        rpcSecret: ENC[AES256_GCM,data:98VyGQn3mEL/TMHxW/nUVweZcf3dPEsF9qgQefLrsgdkO3Wk90XDK4gVVaYIfhN6ihlXb2nSovwAsuphm0SOkw==,iv:baygGKPnjGF3Cz6eneLZjHAYMfx9Ln8q6NbzKa3GQLM=,tag:+vXr7msFZQHWgbF5Se8AZQ==,type:str]
        adminToken: ENC[AES256_GCM,data:3BIJ1jSToCShgNQ692dA9v0wlbvJyXtMxh20wCyqpfhiCjf8aHQssYKqyUU=,iv:/uK7R+1q4OqNaMk8nYU+T1gmU5mCdvD4qWY2adNwKAk=,tag:YwbfNV8NbdSpC7gXSviSGQ==,type:str]
        metricsToken: ENC[AES256_GCM,data:qaCDhoG2osBG8ohEPS9T/KJ/rYfpMde8ILl6nbjZWPBMhYc6KmA/pNQjJFs=,iv:82O7W5SyWbAK8Q/joxRO1u+oj0rMXBugu3mBfnm/i6k=,tag:xB7A2oIF8ojxzQ8KgcVJmg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdEpCTjkzdllVeklDN0ti
        QURheHlIYktDeG1iRlZSNU05TzJDRFF6SEg0CklUaXRaRWhDdnpFamtxa2Q2VU1E
        VnBLeGs3T0l5S3NYd254Qm1nSWgxNzAKLS0tIHQ0Zkh1b0lyY2pabERCc29CTmhV
        MTZPNllycUtBbkU5Z0JBdnFOaFYyaHcKDEVfRjKUpy5evhoJIiR25zH1zycULaPn
        N96p4yJEJju/+0bbHTF4jKmEBYnwQ7YpoSpkyHDcsRew/jdTuc++xg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NG9OZDFvVjFSNEFsS2Y4
        MlBMUU9GUEtxM1RVbVpaWE0yaGxPM25xUDJNCnJqd3hkYnZud3BrY0lidXQzVSsy
        RDRIRHJsS3MzNHlwRElFV0pNSjY0QjAKLS0tIFhNNEt6ZXlqM0tmQWZ5Tnd1L2g3
        WjRBbTlkbnhHZGpzMGFZbm85OFZrVWcKZorTyQIYumys6ECbQTmgJ4DlMNONPgXK
        6Aecd3u8qTgUdwWfTl7CSrQWsoQ/zS12CyDAsRKl0335el2vMyUu3A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-15T20:37:03Z"
  mac: ENC[AES256_GCM,data:4ysOtPYD3GNY4QHJLSVXzz9ithLqEcbskI3MsKs2gmETVjfReCrl3N20SqdzZgWKmBHP5DQbWUH8yJx1/FHfVHJALSKljif8EVdkcqKY06KXvcCVhXlsHQtNgnmBPGMlmFt2Dj03v0+beV/vLw/Z9lqR1mtAEkQBGctWlVJMOls=,iv:PXXCwhBotiRahBdmD+zu8VhIpedo099xhzpKLq0ZGZA=,tag:PbeoXyTuEP7fEx3agpURzw==,type:str]
  version: 3.13.0
