apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: garage-secrets
spec:
  secretTemplates:
    - name: garage-secrets
      stringData:
        accessKey: ENC[AES256_GCM,data:4tR9OAMpoVimD1RkpW6E4PKBKRPAaGqufRf3Por+/pWqrA==,iv:yBDp+5rhKzaZQbr4V/abNmYles6uOCzRsr/atwKQoP0=,tag:9a5fB4uFz4xCuMWZXK3zqg==,type:str]
        secretKey: ENC[AES256_GCM,data:unmnL3tKbERLWj1QowWZdqziSFtWpYxWBCgX7NXVPWViqojL8t5lPPPXepL9+NBrFT0pDVvB6dYWE5lDQJCQuQ==,iv:ukgQCUd0JzLJL2oUBobck/iCkk/OaAjmdaffHXIosns=,tag:5OUThNiIfVmf+fCJxbD6FQ==,type:str]
        rpcSecret: ENC[AES256_GCM,data:J9lRfmcx9tznQvx3tKK0UvG71QOpzTaGrQliAsnk6k5j1V1yRrX/SghLjjX2yKa0yqUxCzK3c9kC+aFUxzOTnA==,iv:iE7GK7CMJkMRl6wBXude6ZGorujj6BwRQ1aJJShOJnM=,tag:Gi/xQde8Sfm/2PSmRm/oPQ==,type:str]
        adminToken: ENC[AES256_GCM,data:8Iugr2MayKU8gKo55pwUg08VhUOk0KX1Vfj0lg0hayaY9TQmWiXccZ6LsHc=,iv:ijGBbzral/xp4+8zLPXZmCs9Uh5eR7XibaNpzBrMlTY=,tag:Ae4wxMNtefRvSwPyD4RIhQ==,type:str]
        metricsToken: ENC[AES256_GCM,data:/tCG73pauxshOm1ormVMSP9idTyxAFqdBFIwWzgc2hcAKvdyojH7XrnnNJM=,iv:N1RlyzpdIoCEH3onHFQAm2tlC/h7X8PWuQodK09WFfE=,tag:JW2ZnadcArkbhcZpBo/8kw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZTFiT01TOFFKWmFSYnhB
        OEM3emZLT1dkalIvQWhBaGIvazRjVHZUVjA0CktkMS8wdE5FUDFVQlR4c0lKOVVq
        cVIxaE1FbzhHbWU5L2RYMVEvcUN5UWcKLS0tIDArZHJNalBZdzBwZ2Z5RmdNV3J6
        dnFNYmdHYkQ0OUo4QXVaSUsvRzRqdG8KgPFzHAumo/VD8tx0QwPqh2hVHoLbFUqH
        Q4XDNrCk/J4APswJrcXEKj9b0n6rUyGJEsko3C4zIrvLUCunmsfFlg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NFVDaHQrSnVsUlBZdEZE
        bGFqTG1oV0dTSUl0a2FoZWI1WEVnejhaNzBVCm5FVzdDQjdIQW9sSHZaTVJ1Qmcv
        WEIzZHVuNjV4OFV0WE5wTThtd2hXTGsKLS0tIHo4NUFqdWpvSmxlZWxhS1RWaEt2
        UEJBYzhjN3RnaWM3UXFlN0VpSjkrMW8KAVm6Lv3nuHl/jz1IUXU6eCHh+OPpdgWS
        BBV31z/D4TeP7Y1tv8InnxjD1buWTvuRDmJxB4I1U/7sJA4o9Ba/tw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T19:50:11Z"
  mac: ENC[AES256_GCM,data:R4ijko4MFPwgDZqMCMDAksK1vnaSQ8PxvKRW/xu0foH4AHdxMev2FzR63nQF3TKkqTX351EFTrOa2cAexeNufmAFRMMVS/GSTrR1ymF7us1vsDNC3JNagO65YnolNvgIEnpforNBO7PaVeNIf+vUvBOhqCSU9j4/RuWF3nTFra4=,iv:TmvSx1Fg5xbUO8anSOiY5ScxtbEAujECR7NY3bADZe0=,tag:QvpgQveBEgRjoddzOuClpA==,type:str]
  version: 3.13.0
