apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../base
patches:
  - path: ingress-host-patch.json
    target:
      group: networking.k8s.io
      kind: Ingress
      name: victorialogs
      version: v1
