apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: surrealdb-envoy-gateway
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: surrealdb
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: envoy-gateway-system
      ports:
        - protocol: TCP
          port: 8000
