apiVersion: v1
kind: ServiceAccount
metadata:
  name: rauthy-setup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rauthy-setup
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rauthy-setup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rauthy-setup
subjects:
  - kind: ServiceAccount
    name: rauthy-setup
