apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: postgresql-superuser-secrets
spec:
  secretTemplates:
    - name: postgresql-superuser-secrets
      stringData:
        username: ENC[AES256_GCM,data:VHlk4EjDVyM=,iv:cPppF783A19dDAMiZOUQwfaSmmFyjsEkIhyonDQ9ObM=,tag:0v97rr/RkER+C/LLl7rI3Q==,type:str]
        password: ENC[AES256_GCM,data:v30SIcqB96uXAIYRWqaA83FREspwFt9S,iv:p3cSjHeq/v4kY7yxsWpur9X13cOjY/qOAafEEhZ/T0Q=,tag:m/vjUikcOzTDE0TeYoFegg==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVW5ZWTlReW9IQkxBeGpH
        bkwzTGFzZnJjMHpsZGFqNmJtKzRTMFBvbmc0CnhCcWRJTUlaS2svcWVEamZDS1Uv
        enVSVjVSaitVbWJjclc3YUdlUHg0NXMKLS0tIEFhandGWEZxWlduZXJhZi93QXJY
        WXgvQUo3WmtuS293OFBoUVNQTTBoYm8Ka7yEsU87fwScd6mzmQwcC9AMfZGnatmn
        K6ubM3gCCoUIMyyjaG/o/89bW7AEYBDGQDCnt++NuHGfJjycUSZwsw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YVZxdkVMKytXdkx6cFlE
        bUtkOSswdytzY3dYQ1RERXYxT3NuQTNpbUFZCmcxT2p2eFkxck5leEVpYXQ3YWtU
        SEg3L1dUcDRTSWk0M1JYelNDeFAySWMKLS0tIEVJTlEyT3Z1UzU2WkRXdVhCOTV3
        SzZnQVpRbFpOSFJlY2F1QzRvdXlFam8KZcQ8M09CNsHT7g41/QWenElGgpWRS70l
        uqtjqNd0njGu7kHcrpT+U/bp6oOJjAaZBr24Eu9ojFmkoKpjG0R18Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T22:15:11Z"
  mac: ENC[AES256_GCM,data:GfGQd27fVa1qKbOljZzAPM0XHtq1szOYYHowB0YvoRhYNh6nUabwVZkoeEAIc5RjDj7wktDjZFVa2y/UHM6SqEvreqA4mG2ZCTQxqpKRIj8HMrRwSYToIqCWy3W9KRXyTIUKZddJYpESd13ISsth6Br1h7NUDXLSnOenmpOqBGs=,iv:UNAQCqGtgeBjTeMXH0HhcfG2o6ow0vuh0eGzldS7seY=,tag:PTq4m/G80VzOskYdWTVwUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
