apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: minio-secrets
spec:
  secretTemplates:
    - name: minio-secrets
      stringData:
        rootUser: ENC[AES256_GCM,data:4HMHCjw=,iv:LoY+mIcpPKn7UkMAsiHHWEyXF81FbXj16gtEKcTKlnA=,tag:lEFhK7sJoyFGsCGIRGkn8A==,type:str]
        rootPassword: ENC[AES256_GCM,data:rEqVHSacMQQnogIxUMlnaAr3/nY=,iv:m0xx9dQU7aaJjrGeFGXhmaGdH9UA2E+ZuQd0v5D5+jo=,tag:Q+jNaGZMtczIRn58CKSBMA==,type:str]
        accessKey: ENC[AES256_GCM,data:v+jLCiUuz8os7abN1NPKUBISwKA=,iv:53G/AtiDjbBRXos1we4EnJnekODzwYicYI3iaVL6uAw=,tag:t7GiUcuC7aPt7+zF4joZyA==,type:str]
        secretKey: ENC[AES256_GCM,data:UhzE76H3oPzbbxyfGz6iOCuRdO7gPLV+uNAGjKKIjKQwLwgWjBjO7Q==,iv:uoPDnzISrg4q88KWFbr0+4SPTR61/e1/kYoHfwM1CWw=,tag:pcIkhmLqmfDqUbNnZfmblw==,type:str]
        adminSecretKey: ENC[AES256_GCM,data:Uyb716pc13i+AXkWRSVu3+4g9G0Oud+9KdyCOgRLIWFoi/EIDpOLkA==,iv:WBb+PnjVkJHEtjU2fhKAN4QQuCYHjnjI0MVOm9cdkGY=,tag:AVIcQ35XQwcToEsq3unX8Q==,type:str]
        guardrailSecretKey: ENC[AES256_GCM,data:mC35qa/E/Nfc0VNiftYknvcAK5em6SI6LHCOwL46BgDk4VmLhEP+Ow==,iv:d5PLtOtN60v/19WRq1BHjd+/+lapNncghdOXZV7lrtw=,tag:+sJxSqS6IjplbUDgHDINmg==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWTMzamMzMVR1Q2NPbW1a
        aENpanl1UlRucTVwK3JLclpmdklOSXI2cUQ0CllPVnROdUFLN25CV2tqWktFVzdn
        RUQyU2JNbytyQndIVEIxaTRQUDdCdmMKLS0tIFZNOWQ2Z0JKYjhYMzRDMHFIczBp
        RVZ4NVNxSzZtaUpYZ1M4aG1GK25aR1kKS/JT2tf4k3aMymKO9cHM2jboG29uXsnX
        UJNTxOBNI2E322igDAnY09l3zZEHc5axj+rZzZwfsjXjFdTw2wvm9A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaG1FZGt5SGttaEpmN2E0
        Yzc1MncvVzVYcCtkQmo5bzdpajlabEszQlZBCmN0YmZCV1Zwc3ovdTRvUTYraHVo
        SjB0Q3pWTlkvQzlEdFIxSjZNWGg2NEEKLS0tIExtckhnTWhkWGk5b3owakhveHNq
        Z3RpQUE4eE54N0swRm1LS0pZNzBnNjQKrATt24j9syjpJXXjxIrpKn8pXuYrwFWb
        DTgYzznjgZT5fxOB5gFKvViBhFz+AaThNBahOeioj6JushUcT27VkQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T22:15:11Z"
  mac: ENC[AES256_GCM,data:oWeBG38R6cMM58eXEF/z0ksrl1yOTzuWEEKjxZ+1xNHvb2yat2XSKRltycbsktxm8wKQZD+7dImOQBz0DzGFF/bMz0Rf4okwkA0K64TuUBkdj3nqGSKdB+Huzqf/53RxSCI4WW/M9zMPrpRAEcPOpqPecmnfZcH8d/Y+NNpCv80=,iv:KDUzHB+5ZOfuVJ9MUZ2LCGfYk9ZulEDjVDOHxzn393Q=,tag:DKWzUDV4BwRNPso7SGC8mQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
