apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: minio-secrets
spec:
  secretTemplates:
    - name: minio-secrets
      stringData:
        rootUser: ENC[AES256_GCM,data:1DQRhw0=,iv:2o5xOyZ7uSEkkRSLdH0SEP1KJmGV/bkBWWr/7k8+c28=,tag:GWMfCNUhRv88AszR2BXTVQ==,type:str]
        rootPassword: ENC[AES256_GCM,data:KP7UF3uF8FxsyCp9OpLMOqfi5zI=,iv:b+Qkl5zld59zXVcsUWJ10KQt4br6DZu1jLDhf0mN5OM=,tag:rJO8x/ifrNsmLAccIjmmyQ==,type:str]
        accessKey: ENC[AES256_GCM,data:BzHSBIdXtyM+NRH71FFmW4ycEKE=,iv:haH//z+6yPwpLNv/DeCxYS6O6sRahUBoze5JckgYAhc=,tag:SgoPG8cxjpro7cbqLvesDg==,type:str]
        secretKey: ENC[AES256_GCM,data:Vt9lluPbbDXcaqbEkJaHkpF1WJR8H3cGOpuqNcwuxxuksDwOY92SiA==,iv:xUPGa4a8LR4vgnBFJLUJKB2QzhIjbu+G4QYbuEARuTI=,tag:TzQ9rifnWKcIb8yx7Ibd7w==,type:str]
        adminSecretKey: ENC[AES256_GCM,data:xTqcipuJY2ORCzeKfs/xt9ascN/EuG+Bz0vxxlDrmz+Nwrz4DHlPMw==,iv:UgGifEA+VI2QAKQ/uuA0gTxsnrXX4NIAxP9hyaKmUQc=,tag:bRq8qWnxVtHv+zxyC830Pg==,type:str]
        guardrailSecretKey: ENC[AES256_GCM,data:2pRUjcCFKVLhfofjUxjpgzlKukMmZSQpXIdDKjVpsACwJyVGboJ8PA==,iv:X5yJg/+PNANDf5HnhH7waH0+sQxJLNjrjnn9cIR7mIA=,tag:b7HRN+ijq3X6Bx8LFaOvzA==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNmhMYmh4ekxCTE10L095
        eHZpZVhxMldLZ3RFK1pqRmJEZEFiOEV5a1FNCjg2MVRDRXo0MGJ3Z3FPRzVFSTh5
        SHdhNUtUNUxDaFV4Ti9nT0xBWWRrODgKLS0tIHJySW1heXFhN2dUbGVxTnpURzUv
        VDZCV0IzckNyZklDNjIyNjJ0T1FhM1EKbJ4rz3eQnPj1lcKFtGMk4lP8ZyxbIUtO
        58/jNGNqjNvFjoEboPH3PJCF7my+8mIFCxO6SXmQRb6aOkQtLXCE/A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVFdLT0FrbVV0MkxqR1lN
        RENueThQUzVPMUk1dzJFa0g3WjBFbjFPQVE4CmN3WmxPQ3o3ODJnUTB2UXhSYy9Y
        RkZ6ZlIzTEtYdytUc08zTW1pYnhmMTgKLS0tIHhSbjVDMFRNWmVpNVFNM2tTUHFu
        aEdzUnlOSGliL2pLUDNHWjdMaVVseHMKRf9we16puVHo8ViM4FABAn1Lt2y3WsYh
        UW+P4cQx/2XIIpqgqtkjFAQg1XKRQFNdqX72aXCX+WWAquP/4w+5ug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T17:21:54Z"
  mac: ENC[AES256_GCM,data:gMZjadz20HkUAclGndqC83yCzw+YFx8tEwyLeksNVHmZlQXTud0AlpRkX2eLuhBIUlREHiSxWi2vmt03BKkqDPsy8AKR3JniYvgf6Bd58QEQ7JMowlPBdcpgd7NTPeGR6Kbn61s2ait4gLpbBylQrniFcp87Y9/lj53K5NzZ5BI=,iv:02qFjQB+48TERiZWQwkNp0k6HGFDAW5byidAb5nFEA0=,tag:VPRA4SgSm8as0QCbzN3PJQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
