apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubescape

helmCharts:
  - name: kubescape-operator
    repo: https://kubescape.github.io/helm-charts/
    version: 1.40.2
    releaseName: kubescape
    namespace: kubescape
    valuesFile: values.yaml
