apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: postgrest-sop-secrets
spec:
  secretTemplates:
    - name: postgrest-secrets
      stringData:
        jwk: ENC[AES256_GCM,data:H/3Cmer9H6KHwBRpYzqKrplzZG/j+bvBwrO8NQHxQR+plELMkuPf1nKSwiurcb42cZLIrI38WMfWietkvj9hUlxjwnyK920d0Sv3QKGGFTs1z1nKY08beAAjOq5qDXFXiIdJOJErTLcLCJh5uKC19bgQ1HKPzy+IdWnp+6yD9rPC3xX3GxVeJPYahSRFr1h5qRIDoyp6rjDKuR/Jb8H2RpwU7aESANGVqx9/XAwCf4pBjmY36EMq,iv:YFDyznEGoPW/C4c2D4bVGFXbEkJUqU1Xt085PilleNM=,tag:gZ+4lDHlN5qFZQVnAwr3mw==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudFpWWmNtY3AySTdGZ2Rn
        VHk4UHNYVTYzVFhJUjVhT3Q1Z291QTQ3VFhRCjVvVUMwdFlIYVM1MUlWclJkUDF5
        cjZ4c2c1b3Njc0VJWmRMUGxVVlZvUHMKLS0tIDd0R2J1a3FKNHd3UWwyNDYyUE1p
        cWVrOXBpaFppeTRHR0tZNFBtSDBQZVEKqRfKlYI3oX6WZizPLcgdfN/ogM94u9LL
        KkdCie5Yr7mmk3kg3HvFKBCGTQavraWZNG2Cbd5CYe9KeOEgdQOV7A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNGM3Ym40MC8rS3hlR1J3
        c3dQKzAxVXdPQlQzSzRYdGttRithbVdSeXlVCkNxT1RhLzBxV2RvOXo3RE5FQWQ5
        S0JyQ0lWTm9xUlVhSHZUSitrYWJwNlEKLS0tIFRacGhKeDVXeWpRY0pQQ3pHWXFL
        YWJQRWY3aHBRVEVwUUtSQ2pIMGx4ZzgKm3sZFYEXAzPpO+20yI4YkK3nrSHSTN7A
        1sX8KYcLoblt70VbKSSFz89SDREjihYzpHyKfuXmYztbqA/nR4In2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T17:21:54Z"
  mac: ENC[AES256_GCM,data:AZusnStEFJphIzlcK0qfQE4Xc3y6jYbNb46M6cP0l0aiDVq53Gk5vKnWTHai+QlICJy5s8+/mbeZd9gxDRykGlUP1LKC/Am5Yij0JDtIr8M6XfAeGjc1ojPnv+pon7hKnYugbjw1dB1RN8wJ2NaeNuHebbBXWlpjJxTfMKOB0uQ=,iv:6B58pN4Bx72kUd5Wpmuor0PFE5OV8ZRSuZnnfVz5MDI=,tag:GlK1PPM7RtUHnLla9BECrQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
