apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardrail-api
spec:
  template:
    spec:
      containers:
        - name: guardrail-api
          image: ghcr.io/rcaelers/guardrail-api:latest
