apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guardrail-prd
resources:
- ../../base
patches:
- path: image-patch.yaml
- path: ingress-host-patch.json
  target:
    group: networking.k8s.io
    kind: Ingress
    name: guardrail-api
    version: v1
