apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guardrail-dev
resources:
- ../../base
patches:
- path: rolebinding-patch.yaml
- path: database-env-patch.yaml
- path: ingress-host-patch.json
  target:
    group: networking.k8s.io
    kind: Ingress
    name: guardrail-api
    version: v1
images:
- name: ghcr.io/rcaelers/guardrail-api
  newTag: 1f7b5c6
- name: ghcr.io/rcaelers/guardrail-schema-sync
  newTag: 1f7b5c6
