apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: garage-secrets
spec:
  secretTemplates:
    - name: garage-secrets
      stringData:
        accessKey: ENC[AES256_GCM,data:0yc+8DASN4nM0iqRTWWic+3F6Iw=,iv:O372wZAUkzHSaPjojOHa+zSGCqY9mP1ARUrpn9fJ1AU=,tag:XWwfz1sM8Xw2HM7Ez9KIUw==,type:str]
        secretKey: ENC[AES256_GCM,data:eLm2LsJyz/GB/rOwBmXIV7GUFeiAOJWdDIcI/xHJaRDF9vYFXLz2zQ==,iv:k28nzsp2vE8sNeA80yAQxHzzh56rSu0mE7FCLIQAnSQ=,tag:+URHeN5w6WdrxiTA11+FAg==,type:str]
        rpcSecret: ENC[AES256_GCM,data:VAPu1LJ86KiVplnQoS4fwZvlee73PidpBK3HytQf1hqlPajKuJxkJ4xbYDOR2vqWWlb7XqoOciFzSmrqUPJBuw==,iv:nO8dk4XdZY69GRVsiyEQa9U63dVTrD798JSANvAmbgY=,tag:KDoJPu39Wvgt5XxXnYL+NQ==,type:str]
        adminToken: ENC[AES256_GCM,data:WkiZZGSvmXPz6gjmmt8PMUe4vIYP3NH417vXSAM+6bTngNSkNu/6p+wTIGg=,iv:s7XM58eWH0MzGsDdPGsMXv1Gg5RbR0Fa1b0NCQAJ3Bk=,tag:P4LmNEUJjP7v3+Ma2fGNVA==,type:str]
        metricsToken: ENC[AES256_GCM,data:y4Ey0eDrENbulv6ELEjSr6JlUfBvPVlRgHJPmoakuzizrEklwurtqKCkK1k=,iv:g32BRthP9ps0YjgVzyS/5Pdl3rX21OlHnn7tfF3zPk4=,tag:Qp+BgYL45Amn5zALIHg4xg==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZk9iOTdzcENFWGlRQytR
        TlZGUXRWMW9id3F3Z2duZVc0ODJ0blVYNDJRCk1mL0hUL0M5NTB0RzdaakxnelVz
        RUNzUzN5TzB3WFVrV0MyQWFvOERac0EKLS0tIFhaTmZjTi9lOU9NcEVUcEhuN3Rr
        blM2cXFNSXFPSVFKOWowSWphZFVVdUkKrqNsgIVolwnSlL60qudNRqd5bEIVHG4K
        nwlIA8+KUBmMHuxSnm9FOEIP4no55kr77isbcBG1zpz2xi/es4VYQw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcUxzYW9CQ1Qzb21vS2hv
        aVA2VUpjZ1J1c3lVL2t5ekhFOS9KKzJoZ0c4CjZZaENNV3laVmw4ZG5UTm9KZUty
        MWlvWTZHQ2hqNTc2Snk3VGhTOVVoQXcKLS0tIHFIYVJ1MUd2bms1MHhQazV6bFBL
        Mm5Ld1VreE55R1ZQQ3A3UW5KanEyWmsKJLxHlJIPGLKwO7BLDMMxCalwUdpBKOTO
        PByWqzYZWK61X+lnIAgFqJM26tt3INKJSMqPxn9IBAZiUOqmqG5w5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-29T20:43:11Z"
  mac: ENC[AES256_GCM,data:ez8uRHd4Ll7yNtL2iDZJScBSKgezk8ldjIZSjNP/WxkjC46UrYCUS8/8SYYFWBF1DQxzCkHsBbz+cuOHwvklkUBd4rY8LfFYfsgC1fu0/nACsZcV+MgQPQIU0OBLzdT0JrQ8XlkcnycEv4UPxEj01Npr6q+YCoVU30YCH98YT5M=,iv:awxAc1y3fiilWWMVCGjS5MYlE/X/7S/6F8YbugySk7o=,tag:BrbRlZemqb2HFMPe/orCLA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
