apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sop-secrets
spec:
  secretTemplates:
    - name: guardrail-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:zQcYNTqaer8PXbA/kOJSYecVnFE0mf0irVMDZ4dC4jTtFvO7kVrv7drLIe56pCDboN2nKUdDFUQ0DfT+N90u1h80Brq5QkUof6WWTw6jJiPMgYLrw6D4AsH4uc3952u1Xor2n4oFm59pvEZfCk1JZOc151oFmDsSUEuTbMmOP5wWIvUzyvMNPSsyszfPcwhUAUUpCFGEPXt16QP8A02iNgN2eCEUQ6awNNa3tFF9FLE3wgnyCnwlGW4WIb84NAA5QXr93ZSrAxK8h61wpIhytP0g04Ayqvhw7wSXMZ6K+giVfkz7P5xwNPX0T+jjqFiXRCQSLuaM6jW1hQTbpCC7/hHNwJ95W3y9Z8dA0ywbQ697GcfgP8S/lmUBMey//lsIja+j8GRATjhPTqQnNcKz8abWqi/6YLwPTrY1YMfd+ekAbAUEtJ5FER8FzoS0ovmekHGbQYBUNVMa9u06H0iflpHXz1JWDm8YOHWck5pYbB3R0cESgVyYDznQE0KZzP30VMidF7HPtLij/3hxUyKkUD53XSv6CG1SXe60ajzzTj0of9pQITYCRNBnK8Uwdil9pwff/baBSce3bjwLEJ/uu02mbmyfjtbSTOE8GBjFuIBvwZDQH5oi+ldxt3O6E2DLBuP8/p+ZIq6qAkQ=,iv:LoBh+DL1HZq35vLuPlDnA4WRnjRds/hEQeK3NXYHWfM=,tag:L+M4YKkuIJ34zNplC8HDaw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma01kKzdtcEJMWkdsajQ5
        Q0M5c0dSUDdwMmNZTUR6cTFHdCtrMFY3dHg0CmUxUmJlZ2tTYmhpWHhUTUZwVkpy
        bFY5Q2M1VWNmcHA0NUI5NjVHZTBZS2cKLS0tIGg0US8zZWxUT2hVVWhoT0gwMHAr
        Zi9aMUF5TXRpNy8rMjhmUkVvdlRSbFEKrmcyRhJzn6cIqSeyNHx/y0HSrj6eDQO7
        qHLeVF6CC/syMdCquizhiYtzxsLrDECRBM02MSGms10oMHfLuEW2ow==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeC9ERzRWbTlOeGV2V2FD
        cHR3d2FGdWxQNjJXNEpOZktzZmN5aFdwMlFvCnlOQUowcFlveVRxOSt4TStFdVlw
        OC9oK2dSV1NDRFR3TEtXZXJkcXpRMkkKLS0tIDdMb1dmS1E2Sk51THRROXJOUWFi
        eGs3YzdCaURqRm5OSEhFSzBSR2N3V1EKCLVLoSHscS//tPrC6faRcZopFBwCFoXb
        7XLdTMbCVYp/WSt324M2vYqlcnzZh7kWpoYn0mk+u4NrCv4rk1dHGA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-13T20:39:47Z"
  mac: ENC[AES256_GCM,data:bRZ4DbL0Laa6ZGLMbtvJaDEfP69viXHHWBd0cCTEZbCOvDKlWsq8SwjqeKYVTu068IA+3OzkqpMStAmaM3M1j/QMATyS+M0jtaUx25AZquL9PumPBgETQhN9DHRDYeafBef89tMXJoHhoIbRktSC4qIonhWHw4OTs6DfwDZ0ocw=,iv:sYhjHWf5ge//wBegRByPXsB6RXvLYGdDyAtktNDthbs=,tag:ISEgLgtK3gV3yrXPaRYTNg==,type:str]
  version: 3.13.0
