apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-valkey-secrets
spec:
  secretTemplates:
    - name: guardrail-valkey-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:5EZwnW0Wd4voisVQbvF/xk5RVqQT5WHyF30ZKBXoPQitm7VwRuFG3Kug4SqwIiJcMDcXtCb/s+4gcuyXYdNeflPQrOkp9Ekk8qCPng==,iv:XY+aI3l4FqGSq6rhIP9ej84eJ7LaVfA+W5yXoZ9oVjA=,tag:E6OBeBborW7DWuk0Vz1jig==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0M3I0bURXT0lCaVVQS3JT
        bGh4M21RbHppeVhjb1lWNmVKWXU2YVFKYWc0CjlzSlgvbUFLNnEvN0RzRE0xU3Er
        a2JUY3c1dnRHYXNnYnZ0Q1Y4UUIwajAKLS0tIDUvaG5SSmZ4MUdkY0ZUUnROREFs
        UFlRdHgzeGE4RmFSNUVpcGNBeHB6NTgKft6FcvuOJJOR45x4Zn9gVoW9YjTLuQAH
        07w4bMpBFFzpLWuYuJVsrCncCHCleVgZeB6XF8YudXFZxyr+97QMUQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVnFQZWxUZUtzU2o4cGxq
        T1BpTXgvWU9nMEkranpEall3anpVeExnRG4wClR1aDFGemhCSUR3bEJPbmY5c2F5
        ZjMyMTRlQm9ZVUtzbkZoUXN3Z1BWc0EKLS0tIDNMNHljOTRzamI2Tyt1alNLYUVX
        cE5aa1N5UFBNS3VtTmQ4YnNheEhobVEKuC1hhB89GyyZw95E2W3mQq74cJeopHeI
        /nG1Ey44e2uqjvDFSK3H1l12guTtceUfLUvzCikjzwf/1fdMU6YSQg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T20:59:59Z"
  mac: ENC[AES256_GCM,data:FeObtv1BzK/0vOeVB2S4IeVQQa7BDCbjHxsrRP4esGIec32XBZpZ+6K6iHHX/AOvnmED8V1dH0F6+CPJNGXToYR2FM3kA5Swp4OpElpLTrLyfQ3Mi+DZuWVjE6Gj6SPyTdYMCmoAKB9Dz9SXlNMFD+5/hcpQ0BQ7zor67fpgwj4=,iv:5/X9xNCDa8lY6h6yFXwI8rzmbqAQ1uef1IiXgXUtSHk=,tag:dO7rEaE3yibvXJ2P9ta/mg==,type:str]
  version: 3.13.0
