apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-valkey-secrets
spec:
  secretTemplates:
    - name: guardrail-valkey-secrets
      stringData:
        secrets: |
          valkey:
            uri: redis://default:%VALKEY_PASSWORD%@valkey:6379
