apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-valkey-secrets
spec:
  secretTemplates:
    - name: guardrail-valkey-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:H8fW3lPNSwTJXUav+J7IWR6e7XbtWixU7/qR7GCpZ345McYaAiQNX1uJ3IkKXrIYRcHLaWeyicznNK6xUU8Dm36MRPPXR4EHSXtw8g==,iv:AW5q8y7deLQTLYBPRDw4sbNGKvxOODWxSpDzKnmJSiQ=,tag:GiDvU6HXJ1vsxrls9+/jHg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZHV5U3JBd3dqSGZYT3JB
        MlY0UWF6bGdjRmpqdVVDdnhRZXpybHVjMkdJClNZeHBOU0hJM3BMR0Y0d0hmaG1H
        RmExeWJLdjh1VUJXQ0NsMHlyODRvOE0KLS0tIHBJZXFjWmNyc1BPSStxZTJIVERy
        Q3gzQ00vRVFGVE53MERDZVVxZXF6bTAKafNEbM41iy5P8e7Ep+UOUYPGG4fDs2Mk
        MTx7PhIGdjs2Gei07dRjv7QvAdRgJrR3zeEwVjeQoL4pE27+ZdgPlg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2d2c1aGxKMndEelp5SWN4
        YkM5VEQ3K2tkS0RqNjRaM0poY0xqMFlEVVdJCnBoRWVKR2lvQVNuY3hsM2twVnFD
        TC9QT0FwelYwcnJyMFRsNlRHZzIzSUEKLS0tIFF4WEZOTW0vUzgxVFBST1VyOEQz
        NVUxN1liZUhHZW42Y2tZbkFsNmxFU3cK82rnxm8kMQsolvKcCuAXCLbWk97sY6v2
        NiiLWUznzLnh4ECm3ekQ7nEY/dDb0AwcFM+kU4ute2CiyUOURJ/Osg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T19:50:11Z"
  mac: ENC[AES256_GCM,data:7ywfU7b151PVtgklWmMb1gH4GLkYszM7x0AiKCFxO7RalW9Oqe1kNmwwFf98jMf9WxlqTHmOaP2YGScEkyn1ihZLwmy6UKBBpuxG4l42R4ezzN5i4AIokr4S1aA5my2mgaxsReqEGFYTu1C7r1A7IDSP7Lip52/sA5TN4EWWxmo=,iv:axDPtxwOpb/d3mJpioA7OJkTkH+QaStHzqi+O5XfW2w=,tag:6KHWZoDfAcrFIQMeYjW2ug==,type:str]
  version: 3.13.0
