apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-valkey-secrets
spec:
  secretTemplates:
    - name: guardrail-valkey-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:ROfgliVbPmKiMe7TGE8YhUkKXuU5aCmEs8R7ZW/BvrNq36RQVb4CSvO9EFlxTf5Qk0JANsjh4OKsnDAKp8oM0OQz3iCYN7m+avbAMw==,iv:9ngd+uX3OS4b+ZHYCC7+Xrk0bzHB1OaVJIf/DMAWKa4=,tag:v/U8Um8jpc0lICRlh9PBRQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHekNiWm9qSGx2REFhM0hB
        OFNaNWNXQ0JyamFKa05PamU3VFh2bkpkMmg0CmFocEkrUzlIelBFU0M3Z2xzU0Z4
        R2NmVW04RCtvTDN3MHdyditIbitzT2cKLS0tIGpKOXFPV0orT3oySHpwbHFwSndl
        UVNoRDM5QWorZERxa3BGVEEzOFlOaFEKOFsgtzUkeUBRc5h5imcXzWVMUPLyFU8C
        h/Wn7dNVy+oXOPBalngIyuH2crQ8Tp+D4bd59kM6j2/LluwjTxwt+g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTm9ZU1RwTlRka1JzYm5Y
        SkVJeTdUcDBVSlhwVE56WjltVVM2SDd5WFUwCk1Jdk5JNlJXUjdYS3RNRFJpdTNF
        V1ZqZVExWHRqWVlMYXJ4V3ZWRnlBWFUKLS0tIGd1b2tVbm9BdTZkamtuT0tDY0RB
        Y3BrTmZuL0l0RXlqNXVVSnJEVGtFamMK+VjjsCi8DdD8QxEw9iLwZmYINiSEp1VX
        jjozc/ADsCUsd2AcQ3YiaWLEIoXtXgUkvg5S0T0KNfFfo7cBN8nbUg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T17:48:54Z"
  mac: ENC[AES256_GCM,data:JVNhV6PMLKxo5nzAwLQAZoo+KLdzicLE9d08FFOKcyWhIQANTVLVYIFvcOJwLDVck0j3/HmYhBSq2s60uAKwBaH9fn3SLv5kA/XA9m7WWKL8XcNCfPHRBE4ForQ5SE35QeRM5i7qWXNY5Zn8pakPU8vZjzxCwu0J8ZiiygIwGE0=,iv:YcpuU1uzUxUGDbR2KYzwwMNYpApQgqPMv5qtmwYLry8=,tag:zwmNdHwxkYqvUgdCQb6Otg==,type:str]
  version: 3.13.1
