apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-object-storage-secrets
spec:
  secretTemplates:
    - name: guardrail-object-storage-secrets
      stringData:
        secrets: |
          object_storage:
            access_key_id: "%GARAGE_ACCESS_KEY%"
            secret_access_key: "%GARAGE_SECRET_KEY%"
