apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-object-storage-secrets
spec:
  secretTemplates:
    - name: guardrail-object-storage-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:MALSEVkk5VBrmaALMblcCmW5pAMRDyefaSc2vQaAsmK2+T/m9KJFxnrrwGGQXPTLmBS5HUynTrrbJ8LOTWjTaz0SaUoD2MOb/hMxyuu3eySOfcYAfL34yAiRIsRNJTtPCQ4QCmWB4YXm1BYCJ20FZBc4YCzPv7OzGSxcmysseQlDM5j7W8+HMuPZ+2VYbTax2dsYrBdy+mu3AP/126I=,iv:PVyJh3cWDVfrzZ8Ev2Y/i07L8h24dTXUobjZz2np1zc=,tag:1B/gXLB6GHWiakQjDjD+rw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbXhQSUZMWWtKczFuMGU2
        K1hkNFpuZ0dMejVqQXBlY1VXaWYwYmJCS0hvCkVwUEVsajFUQnpzT2taVWEyR0tt
        ZDBVN0cxb0hSSzlyV1g0Q3JRemlmVncKLS0tIDZFQ0tnVmFIY3dIaGF6NVFYR1hp
        SWtoZ2N4OXVDUG5wOTFUTWNKbWlYQnMK7Zku0Xk/ieSIEKc/81cq/xnB2t/8b7UU
        D58jUtFG7u6d/pLBwEE7N6hRsr2M4CQW2qK/O4fcYftUaOpmFVtRyA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SlhhZVdBTnlWV3Juaytl
        YjhQK0VqbkdzNlc2eTJIeDdhOCtiRG1WREJrCkFrQ1ozd0Q5Ni9vYjh1L053N0NR
        cmVNRWpkeFFmVEhSQVQrOFFUbTRsNnMKLS0tIFk5bkJjOFdwaTVPTFp4bHNVRXlK
        MjR0NG9BQzBram1RR1RaS3VmWEZiK1UKTrOKGxDFf5iw2NFtwmwaY1Md1hteuPV9
        zIE25aXEXdC/rlpBUaQRAgk6FFp/miXQM0QkTIjlVKewOs52WgS2ng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T19:50:11Z"
  mac: ENC[AES256_GCM,data:xmZnb8DKJn/s677INSyR2rMjsKDMbfDtYTbE2Zt4VIMOWJazf0KMyl6p+Nbkqy7hdi5UWKCxGRiLUahVgVYtqq0sg8WGDMO67Tcq2BtVQiizXDJMyJRtx6n+0qtCnxdVNROj4BLHYoXN9y2cvUimYkh7xV/QKOFFnrnG2aNdYm8=,iv:PhU73NbCEXVckI0DU3Reb+kJal9EbF6bujjdhlV4hWc=,tag:uPN1k6ir1obdLJfvgfPM/Q==,type:str]
  version: 3.13.0
