apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-object-storage-secrets
spec:
  secretTemplates:
    - name: guardrail-object-storage-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:1cvynl9aL+Y1Ox3vpFlQHT1VyRiN4mil8HD15HaCAXyCOvbg8lZLRG5kszHtEu7ICFULq1XSPJHRH6+OYiK+QkcWZM/Z/TTPN8PPqxPKiQwRI1wT0RxQvJY/D+fU3DOIWvc5TJSC+8stmexhLe42l3mcgaEqVtue2Cey9EjhtAdeAhdJGzvPhkwgMLdhmGN9WQW1intdJAIFSeGl2Gg=,iv:WExxLSLvlUbwnF5yGBpvdDmf8hPPneZPw1N5aqxSC+E=,tag:tHpA7ZB1vM//G+1DW2ek/w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZ3NiSGVWYWo1UnU3R2xk
        ZnhSZ1FYVFZGL3BxaGU3OC9HTWJtcVh5QVg0Ck03L2VwNzBVSDVXektTWEZHOEIr
        eUpEVzBwMUx3eVZEbFhGbDB2MDVMOXcKLS0tIHlwdVNGYzhtYnJxMW03b3JsTkxI
        UGtNdXBQQkVwUFZoVi90azRDeC9pQ1kKd3ufIZDzKAL0Us2x6+CZtuAceQ4lHnui
        Eko+xAa/5UVyIodFjdAGatIts9+DOUV3VNEp8cij2ybWnlT/KPdPaw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TVBaejlwbkdBZmpQOXUv
        aGdIdUVIeCtSVVhmWkxQb1UwNHZITWxqWmhVCjVlSGg1VmVMa2xPUEpmZU45MkNF
        RTlRNnlWMG82cWNkZXR5djVGdEpCUE0KLS0tIG0wZnA3cmhMNVJRUzVPOEN0bGxB
        anZyT2pUWC9WRDVFN3pRbGxzUDRPK3MKZMsTiifeydJ4DaYu2tLqxSsYE7gzL53u
        EtazJ+FqOJInL9RTLad8tyhcRsECQaU2NSfbACfhz3ml2REBLmH8TA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-15T20:37:03Z"
  mac: ENC[AES256_GCM,data:hoyqcfNhaJ2TVAh0NmZpv1O+c+7mq1ultDvv8oN7TElObh659T35+zdycy2kxkapP+T9o7pkEf8xMIlI0DqnYkGBfE950tJigpYYY+f8auSn6z/YXUr5kHIwPITBModOAen4I62kowjMpHpxS0jy90wd2Z/2k+kYw77SeobWQ4I=,iv:hl1iBRTjdoz7VbbyFlhDXXdn7ItTGXZbQGgEqzfyjh8=,tag:PeXhWI9HgkeMV32xiRQtQA==,type:str]
  version: 3.13.0
