apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-object-storage-secrets
spec:
  secretTemplates:
    - name: guardrail-object-storage-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:OTOtmmBbaVsvu+xgJCDAHRjOR1lMt1mWHxtxI+pEOuWql7w+Xo4e5QELN10Udk4nooRS0J5QAnnuhOBhB9ubvE3+eac+8JGEVPyDLl6fV8piTXOlJHrANF/MEoLVR2MX45lETzyO2wi659Xk26vLx2HCgi5M3VzonrbkdAYSZajlapB9aiqhoMT1p/XxhPhgFh7nPy+lhbyrsDMlwFo=,iv:J//nQF05QlwSgoyhWUMBqFsehGT5ZDOfbdMy8Q7vlWs=,tag:yS+QaOh3EpNXgKKeMT+rfA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTmMxUUowa1BhRk13YWN6
        dWlsOWhpeDJBZXdkOGhhYVlua1FlTmZ4ZUVNCkRyV3NyOHBLbWEvZWZSVitPUnFE
        ay9UV3ErVTh5MCtYWTdHZzkxUlA0YXMKLS0tIE1kTmNUTjJCMnFxS3pOTVJhb1hz
        NTdQNTgva2R4Q3dESlZ3Z0o5cWxaaWcKlpM4Xyq6h/bh4sbENEPfEQZMgqWGeIFB
        I3G14EVbd3ILL0WsSsosiuB2S2O3n2ZEP4tgtjsQbtrAUsn75Aldjg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQy9PN3Rjd080U3FZRnY2
        b2UrTE5LWVE3c2dVZ3ZwWkJxQkppY3pyaXpRCm54dU1xVUs4TVBjaGl6ZlBuL1lR
        YjFMUmR2VzJJR0loUW9qejV0QmV1MWsKLS0tIFZwNm9KaW1lcmdMdHlsQlN5Vm55
        Q2ZIV01kMFpWZmo3b0pEL3BlNFpZNEUK0rJABDuocYbQSnbZYOKUi7VVdS/vrfhj
        7Gfz42XTQpw00zUuQMcbZAwgxFke97SHyuPZWArmVp0yerbVp8j2RQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T18:25:18Z"
  mac: ENC[AES256_GCM,data:agXOWYVKtkC9rzr880RBEJbIXyVsoTkEEeZwziyUcbfOVn3syQ7lfYaaW4ruiAIorIuQBy1gzVvZwylrLVwQbrORNbMSPJkNwq4+xKNhsiETfaHWEdm/mPv1NFs1CHjpBboQ/t9zO0E3nkDUCE83rCS85QSbpj6LGMvUOeeO2DI=,iv:eZya8OoFoRXCjceomMVyYris0Q+n7KPo5eJocN/es0E=,tag:v/3EG6QDtKcAuw/yQzBHyA==,type:str]
  version: 3.13.0
