apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-auth-secrets
spec:
  secretTemplates:
    - name: guardrail-auth-secrets
      stringData:
        secrets: |
          auth:
            oidc:
              client_secret: "%OIDC_CLIENT_SECRET%"
            jwk:
              private_key: |
                -----BEGIN PRIVATE KEY-----
                %JWK_PRIVATE_KEY_B64%
                -----END PRIVATE KEY-----
