apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-jwk-secrets
spec:
  secretTemplates:
    - name: guardrail-jwk-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:UwOyVEjYE0xSLf1etSqzkjczbrCyfUpGyKlOSlfDgR6sU2P4zukgbOoRLHncEYnFb+86N52XZdrG6AdQ76jRzJ68QXC59hVtqfYEyDejfYieeXvSEX44NfgS9fDTaPK18L7evwNQhSdnBVi2foIRGcyNqTtNR7bz/LroRzAEw+L4jJYAVnO9trYFOyvO31UBNC0oOoLzVdUI+RDY3O4pE4trHhKeKYGca9PAFdQ=,iv:NNvjlbCzWXWFEfGZOP3ylPI+WdORl3Oeu5/eAkO8J0Q=,tag:s9+xvZZzv1nU8/NtUxOiYg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrU29QMEthTXg2RCtTYWE5
        R2N2bGlPT01RRzhUcDRVQmNiWFJZd1pSa3hZClJ1Q20vZzJzSllmVTJwcFVNRWQy
        Ym05UHJJTFMxak5kZnJRaTNzUndUQWMKLS0tIHdzTFJMYUhNZTlCcWVkTDJESXg2
        RG9nT1lyajJvVmtoNGdMTk56eHl1TTQKm/HG0JASFqtucy9Beu5wGe7ChbiWjDjw
        6OGqqGvcrt1BsV/kCOwTyrAJSdjwT8eA5HGY9Tl8Z/sZX5FhgdkStg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQmVqMG9zeWZsb2pDK3FK
        ZHFaMTEvbUhReTFmSHl2cW0rMjNmeEZYRlFjCmhYS1FFZVl3bTJ4Q0NFVEEvdTR2
        akFtbWJXQWdoOEI3ak1lcXhlVys3L3cKLS0tIHh3N0RDOWgvMFY0SWprUnNrdFV4
        UlhUTzhvTGJPOVArSTBWaHFWMGt2Z1UKCQmVwjFOPb8Z4y9AxCVusepGRev4M53u
        ERVuLtQrhTcLoEaqBGdH+KYsTS30NGVIMvmFj49GBcXyCgSRLUAsvQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T19:50:12Z"
  mac: ENC[AES256_GCM,data:l9Hab9IXA4eFbkjGSjCxtSRzFCGLy4Hq4AeeHJ7uQZUQpDBFKpl3ukkKsScJCUwOJDWKne64xiKcEp4mKDsBwdGeK/nDfLQzCFA6rUIiznViILWBo5+ZJzqMFCcLVyDkfj6ylOPITJgEabhw76SnNWRUFGNhDE6ivO4+Af8829M=,iv:rtIqFl/BlZLIISw5c8MAEw1mXoJNSVKJeJfSam7uOfQ=,tag:3oSE88LricxI6o++aNP5LA==,type:str]
  version: 3.13.0
