apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-jwk-secrets
spec:
  secretTemplates:
    - name: guardrail-jwk-secrets
      stringData:
        secrets: |
          database:
            jwk:
              private_key: |
                -----BEGIN PRIVATE KEY-----
                %JWK_PRIVATE_KEY_B64%
                -----END PRIVATE KEY-----
