apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-oidc-secrets
spec:
  secretTemplates:
    - name: guardrail-oidc-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:SakikI0UaUbPK8db/3OdOrcW38S9xaA8TUI8ZQAeQlhkMl/UxzjdwlSMEOLxnTT5azc3fV3pSXuIsb5ugYOGDPY/64E=,iv:ExV/ViO2oCl37Rq7hNC1i4uXbrzN+SH2w/1A7kZMg8A=,tag:ElYXa3+TjrfHyf8GeLxQEA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUXpjTUtZUjRoRndSSWVt
        ODd1V0R1bXFpK2VFL052VEV2OFNXdmFUTWxJCmtYWEp5aHd6WmRNODVNNzBGaDVl
        SGVvWWZRcEpZWVkyY2o2alRlbGppVFkKLS0tIFNiM3dPY3BVb0dnbmI3SWx1Znp5
        bysyTWpMTldGdUxUemlWa0NWNVJyRjAKHj0knefbqiCg6AJuUbX+SSXYMedg2i3q
        BwEBM9X8/YxsZVWnafTV6bqCiMsSoDeo33S/bKY71ija5EvZXMkGvg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRmpHdHZFR1ZvdHowOExB
        dmpyNGJBN2N3aTlsTFpodVlPNWgyTmZUVzI0CmZ5ajcvdkg2N3dUZ1pmVWdlUmNH
        SjJYMEpyb29iTE5hNWlxNExwK0VrK00KLS0tIGhTMUZ4TU5HMzZGWHlvVWVqL3Jl
        WlVZMUtUMTRKaDNCdjNRQkp4eEl0TXMK5hML1O5kesloDSFTiahIWGLatfT/xkXf
        DAc8Sw19VepENu+JB5/hfJwCWgB2StO4q6kJpCngzrFvUo0E3YfdAA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T21:13:29Z"
  mac: ENC[AES256_GCM,data:B5vdez+2chQ5+9U+vDthTvzQcfJZljc8R6kpVxTOCXXiZGyq1N1TunAqLMDaqTqWOSBc2xk6x/OkebHe1kQqXcGEUEodfpk2gIbtucwUPG3laak2o3kuTe/MzoQoKXxY3onyoAv2KHnVCJqT8+VMkLJ5AwzT68/+oVfdhhm40sw=,iv:uZ36c56qLqJ4O0jh6somIEw8NjPaEk2hj7dZ2NaMH8U=,tag:1oLhiIpekWJmhELTxDq3Jg==,type:str]
  version: 3.13.0
