apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-oidc-secrets
spec:
  secretTemplates:
    - name: guardrail-oidc-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:Bf0KS4u9NyUtpVgxubxYqquYRA/8bpm1jyr1WGBNlb/hd/r+1rYrVja8H3alpT6qUFQXBfOn48y++Ag8Q/gx/Uzp2Ro=,iv:yOA3g2kz0se/Ctj+oGiDht/gDEUdYJGvYTfElMOyUT0=,tag:+Eh8rUBQ2P6dpv/vq0inEg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSW5hTVJKa1ZrV1FXNS9B
        UEZwQ2hQVitMNmlMSlNaZXh2ZElVTlVNSWhNClhlVDdpTHhFakh4WWdVanorM2RM
        Q1Fjb2pBaTlYZ2E3dTZsNGowcFBMUWsKLS0tIEdmYUhuNlo3OGlUYkN2c1ROU012
        anU1ZlVuc2FIUGFlQWdVT2JCa25kc1kKU99pSNQbNTNUjP7LcW+Eshmw3PBziPIa
        Vu0fdPxG3KwtKmVquuPnDF7WFhwlAGvDTw1f3moaIEeQqj2+Daj7Sg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRL0hlTktKTGNMRk12c0Mv
        and6VWZpVVMyU2ZTNTM4UmVXVS85aUJ0L0FRCndqcHNEandTREgyMkpiSWxxek1L
        SElvdFg1d21ieTIvWTF6MXE2czkxWTQKLS0tIG4vUFZQWkZpRVRvL1FHMU5MZE4w
        bkN1YzErZjZidUlKSDJqSWFDSXltcGMK2iu6+tE834rP4+AZnpvLytUHhYhnaHt6
        86o2HNexaOl8Hn1fHCBdAHP5BAwrZaknNCmOIozmzk7Um2XigCW2aw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-15T20:37:03Z"
  mac: ENC[AES256_GCM,data:epC4FEwjByIxqHAB6mykXtZcKsFvu45pg4MdWjKPjaU0+RZ9jmpansnPTYtIJMuIR+pYzIN1kMApuY/dfPxfQhBRENPe21Ld3ykcdRxn8Ulx/Ud3/6vNyowOtynuTGI5vvfZhxpfo4qIL75birkReoaegGoJLm1jx5MnRRj5X8o=,iv:mVN8uskB0cgfcLKGuIzms54sT+OzmZRKGvpNrTFOTN0=,tag:LZEvCib7E5KdTlTEcx9cZw==,type:str]
  version: 3.13.0
