apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-jwk-secrets
spec:
  secretTemplates:
    - name: guardrail-jwk-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:z5eaW6GSQbpzoEM1S0FZL9iPc/EU3t7WLq7NJOPOZ86fmSWVSrKbXqiXKDYuf2llpX4BGKkNTDdu9bKeDUp5sjkHdq41FFyyyf7zOhXqNnIb8X4wq/XB5JyzCaegtMqWzjvD9okCvBbEoTajvP/lTvhA7Bq5bGciyb/81l0Fm9QnEjxIJn95aC7tLLr1KMo/RRfSiFbZbcJ6qDzW7haWkUtSQ8QDL2tJZilgpbg=,iv:Xt5TRpcNXtF/vdLTj6bROt1MY97qxXaSAHg9WeTQDjo=,tag:KdQAR1Hx8kKp3ivexDotOw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbndQd0JNNld3STZldVlZ
        ZGdza3laVFVNSHFXTnR3U0VXR1lOcnRzV0NNCk9MZXgyYUVESGQ0dkIzem5QYUFw
        WGxibmtEUjBzVWllV29Zbkp6NTBvZWcKLS0tIHdaWDhUdWhYUlhGbldYT1RRTzVy
        NjVmK28zdzhwYVlkYUU3dkVQUmsrVzAKGgM6e1nqg7gFfl45U7I8yHYLaYVZqwGJ
        cQbu8WLDktcnASeG6zEcOp70VFDJ298/Bi9P38pJZnDVST1Vj3sIpg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvakRRRjBBSi9xUXk2YzN2
        WXJrMlA3Q1Y5Sml5czZDRFFWKzhVQXYvZ0ZnCmVQUFB5YzB2OE4zbm5iUUl5WW9G
        OHkvL3JvWVJWWThDK3VTRFcwY1lMMVEKLS0tIGE3QkM4d2lYMGFWcExEcWh3MkRj
        VENwU1o2MXQ0ZVhudmg4bTdRV2xjZXMKdAMvD1MCt8FsJh14JQN0DfNpTasAL5RK
        hJYypl0qKSoo6Mt5GBCtTMAF+ZiMxBZKtdYbFywgCrnLZfveDKzoHQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T20:59:59Z"
  mac: ENC[AES256_GCM,data:MqNnrEVhKNru6PFzw9u2VJfrZYad/EquWvxfFAXN8pW3b3dlTbeAc/XQyXvqyzif/FpIMXn7WpVDfiHgEG/3TokKvVwc61b9u4aEn1yaICKPbNT6Jm8wYfqEwvRdD46nIxwuLOZ7RTIvG3MWK7SnZtJiELZbHynoypaMJoJM9DI=,iv:L0GA3o6+LocJlEpfR6eKgOVN71pfLzzD2jqJny9117Y=,tag:MjUyqr3X4Jq51RH8Zbwjaw==,type:str]
  version: 3.13.0
