apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-oidc-secrets
spec:
  secretTemplates:
    - name: guardrail-oidc-secrets
      stringData:
        secrets: |
          oidc:
            client_secret: "%OIDC_CLIENT_SECRET%"
