apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-oidc-secrets
spec:
  secretTemplates:
    - name: guardrail-oidc-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:oVnuw4cvqIWLTqHm70kOL13tsomIuVIKJFEE46bSdtbx5l5tVGVeQpSoXBOOpLGSi51vY7G+oETX2Q==,iv:gbc+tYGIULCF/UWenNB+X580V2+pzqNTnAYWRK6Mp0E=,tag:9S1hrCAq+xaf04Ormov/8w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTWIzem9BZklWMCt2QTQ1
        WWNZa3NJL0pkQnNCZ1lKZlFiSzhYWjVUYmo0Cjk1ZGwzc3pjMVU5RDlmUWFScitZ
        Rit3UGJwVXZaSVJsdlhLMHFsSzU2dTQKLS0tIFg2K0tReDVYQWFRK3pudklZSzF2
        YnlKTFNGVU1VZTNXaGJKT3BibC9vSzAKQvVBnJlD09ffdi80oQpHG9HcdV7PunX5
        19JX0j45cXtp74PBTTfuYv1Z6oJy8XS4htYSEcJvAeeSag7fV7mowQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWG82ZEtqRXRka0VCZWdh
        akkxSlB5QTRIcC8xMUJWRFhXV2VwSndmalZrCnRPMUI2cWFhUEhoQmZVeEFvcmpq
        S3BJSEk0dmp2SHpQaFRndDFMMUg3OVEKLS0tIEN3bWljR0h5OFg4ZExueWVXTEVT
        Y1RhMG9tTWZtS3JiMTQ3ZmdtOE4zRFEKeZir+/Ir0XJEqrNDlWXdY1R7JEAL2szx
        xcYWaacwp9WZ47MoYRQB/eFIjnyko74U1L3/eUZF55pm51dfLLuAGg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T23:43:37Z"
  mac: ENC[AES256_GCM,data:8l6fhPFhXD+T6EzjRBf8mbaGif24735sgM4gGcjjqO77Jx63yq9X8csK8S3VqTFBctX4HLvIg5aSI1MQupD6DBGT6/weC1V8AUq0WCTAWZreBx+DPW+G6H/Pr3mohSOzXFpwcnCkSjZtteQG67DSZ1P30NBAXlHKOOesSSq14DU=,iv:nrYyDmKNGtXAJi0UwyBKdCCkULR7VvRvuHB2iAfl2GM=,tag:KKjmpl95VTlaDoF5wa9gvw==,type:str]
  version: 3.13.0
