apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-jwk-secrets
spec:
  secretTemplates:
    - name: guardrail-jwk-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:o9SetmwyoxIJxkDRE4PA98xcTmd1SUoZ+ods4fiKHRQtCR+tKuOtrX/lnbAaFxVpmYugvtwFAjI1kKX8kCsZgqQcvVqYT9GtfzBJ475ZHcqrK4+EjPwZmAE3Y3s7gCQvBLUYGxXg1uBsIQqr2bC1CWMzu02KAJidKzvkJZNzxa3/2MwX6VmXZ+1/JOK2xgG6GtrdFGaDHRP+n1Et8j0O/c9xaLy6GW2+Nugp314=,iv:jY67LubzcdfWp07yiBSOwD6k/JNQLWKjE99PEGK6rhQ=,tag:pGRVXrYbe4byVUUZ2FqH5A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWUt0bzJCY0Zjd1V2b0I1
        NWtVa0g3U0xRdVJ0TFJobHAwK0tzTEtEbkZNCmtpK3luK3h3aWlBWXRkMWYzZ0w5
        ajJCbjYwaVQzRzNZODYvQmJVMHY2TDQKLS0tIE55WU1qOHhSYUJyZzUvclZNN1Vm
        VkUyM0pHaW15YkRRaHV1NVJRRHhuM2cKGqmE4vi64UQuhtemO+POIfnyRhh0Fjao
        dtoEQwwXyCvlJzlPmS3g0odjX+a78D7HKCTS3zC9Rqz17ojGBMva/A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbE11NkYxK3RGL01JNGk1
        SWE5NG0rT1FYcTYzVTJ4U3Fsd2N3UHN2ampZCkRLd21VT3gzWEJNSExMUjIzNnRJ
        d0RUU2RLSjJvaDVHM0RDeG5vWUs0MnMKLS0tIGR2THVtOFRrR09qUGtOR1h3cFhl
        RTVueTMwbUpjTjQ0eDJiWUYvWWxSVFkKClydoLGwrSpJBbewnI5e+0bJ/PqgnRY4
        dB31jVin6bNPndrAGLW2Q8GIoiCVyqcCtBdtTOmMxNF321Nj+5iaug==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T21:13:29Z"
  mac: ENC[AES256_GCM,data:KkZrUlTCXDBovy7R1gaHQY3+FPf1amxYJEtbG1zxnhMcXxqXvcZYQYFE36EBg6p7d++RUbulpiSnh+fQnjhiSN1j1wFJg1mjiF3YMOJs7pJwjxBFdVs+5BvW2jkiGnKtC7FXXUwD+/IKTbgENv6q9Tz9eP3oMX7azdl+iUhG5Ww=,iv:fzIW4LjIFbIzGWEech0Kzj1RDN0a5IufxwmHBiWlLko=,tag:AL4+oNJedx4+sKFwSTicxw==,type:str]
  version: 3.13.0
