apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-provisioner-secrets
spec:
  secretTemplates:
    - name: guardrail-provisioner-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:trbXXU9L7CuEmDbm+fwh7U59i34vQ4HUavDurg9jjbzc3Qg8xCqQnELZtmv1i3fPOwOhTv60dxryotG9g1vPzXQmNq0DbYfV5/w=,iv:0jQzOWVsUoIwzJYAFf0VdRqB+udrsyxFuDxAJZGKSvI=,tag:Zoj9G211Isk0uUB9aRsjUg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbTJxWnVIOHlRYS90ajBS
        QUhqYnlVQnk2ZkRCcjlYK2srNEg4QlJOMkFRCmRhZVYydFBvamFlUU1RM08ybVlC
        Q1Q1bjZxOGxPZndoMy9XUTNPWUxKTWMKLS0tIE0zZmFHRkxpemQ0em5HNWp1NHE4
        MGNCSXNvaE5keVV4dUJxY1lBdUFpR0UKQmSnr3K5jZ9s/7ghr5GHIGwneUd1Hf3i
        0WLEnk2m1ojAp7SSaPbJ4y0Zv32Td+weWH55nfkQsxq5fmGyvN9Fwg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsL3M3bm5uNXE2amVnZUdq
        N3h3alBtSG56WlFBL2ZvVVZ3WmNqRE9hbGlFCjhxbDh4WGJCdDRESWhvMmdEb1Rr
        VGpkNVBacnNoSlZNZHdMNm1XS0hnUGsKLS0tIGZNUHdDbnFlOWhOdytFNDBnNnFm
        bnpvQm14ZEh2aDJQaEtrOHNWbTJsNm8K+FK0NvMYdWMVwcztCQmYb47vse0jtbwX
        2BTCwiCZIf5oBJ9vkyZFYD3FM03cHNmGT+2Wd7x2Ihqd6Hd9kr/JIQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-15T20:37:03Z"
  mac: ENC[AES256_GCM,data:iFxGE8w/odw4r7HBPEUYy++DBTFsiHAmsQk7h57aaq8MhfWV6vwxC4kVjt08QvqCudZPfpcPG0NzsKOPL4mx0z1izRoJ4bI9gpnO+iq9pZwpj4TJoliu4lVFfGzZR/qd1mArbutXj3evm/AI2w8wrxRdQJwyeqVvuSaollB2YHg=,iv:bA0iLo2rXvitUj8iZTKtIhtYKnaEkSLU+L4eDlv6w+E=,tag:yuetQPLM/TnRfpAuX32OHg==,type:str]
  version: 3.13.0
