apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-provisioner-secrets
spec:
  secretTemplates:
    - name: guardrail-provisioner-secrets
      stringData:
        secrets: |
          provisioner:
            pocket_id:
              api_key: "%POCKETID_STATIC_API_KEY%"
