apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-provisioner-secrets
spec:
  secretTemplates:
    - name: guardrail-provisioner-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:dw0H6ydvXNZ/kCSy4HHtfYr+JSKkMGPaIUQqzHnvS5fzaL7/vOpXwygr6McE62/9gDlLWvzGIteGW7cyl5QLJ3bNSjDPtN+p5cg=,iv:H38S6LULhmpM0qmmoo7ZL3e6/OJMf8QWhfs7umGmqro=,tag:tz3WsvKs//otxBsuFJepmw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYjhnaE0zLzUwci85ZVNp
        VldEYkFwNjJwdHZmZDluNjdhV2ZBRVJBcFJRCko5bW5Sam9WOHZPdTRPMmo3RGc5
        QUpEWXQyanAxdkovbUJSMGtSMzdyUTAKLS0tIFFFNDhJWGNnSGUzK0IvZFROSXM5
        WjBrMDVwQlY3aWtxeUQ5amZIVTNXRDQKtZE8zhJadVqYbR3/DOWmu2VuI61KOmOi
        kfMAxtbQN+V1x9XgZI5/yLCHdOW6nxwx9QY98zoYG38vz0CVQ8NhtA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkd3FpeVVRODc3LzM3bUI0
        cmZlOFVzenlnNWFrZ21NZVhuYSs0TmZSSzF3CkhBUlhvNUdhcHBvd2EzMTlXdHUy
        ZEo2ZlNHNUhhRGlINzArQmVYKzRxa2cKLS0tIDVHQWYyZysrbFN6ejdFQmcxK09v
        YnFTeWk5OEVDeEN2NXVHajV0aWhwdVUKIdehMn2mGbKXZoCIxblcvkfsG7BoQ6YD
        ghD+oZ+qt0rt4gRMQS2AFiOhFogXuMduAz+xU9zdwErKyoZqLQJJyw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T20:59:59Z"
  mac: ENC[AES256_GCM,data:OAmCPZzamsp8/Be01nTFUU/D+4yIJb1NhtJKVALeuqo/lZLAwUSG/CK8HVHnXALTCHsuQHcnq2bm5dWOTBK1XfpJ/WdbDJYFhtdQCPkgFJFx+MWA62GHem2kl4r7zCBYwunOCQ/vNHayAw6Jc1D79tEA8oPe5HAo9LMJbuchAM4=,iv:IIJ+TBd1WI6bFTOXaSC12o+lK7odTHmZxr9DT4vW78A=,tag:FUnMhf1fphXiXgNIu9fWcA==,type:str]
  version: 3.13.0
