apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-provisioner-secrets
spec:
  secretTemplates:
    - name: guardrail-provisioner-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:gR8XIh7OhVv2VysQMHHlnHCJKQAXkz4sjQ6RDK1IOxzjczDNovZBSkZcq/GzqPXGW+r9GSnyiP8OGDyEwGgEfYYL8DubiD6KWqA=,iv:PyQMXCR3KOFGbX5QGqY6VElSNnBA5psYlIsP5ZIT1xk=,tag:xacseJYsLoDD+wvY+uVaBw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbUZHQWtBdEFmTko0cEg3
        QVRubjk4QlorVU5mNVgxOHVwbjZzbm0rN1VrCjFTcXRGS0FQUkVsNGd3aWhHNkhB
        TFg2cExvM2RMNnRLaWNyUGpaNkpQancKLS0tICtrYk1HTmJQenlVT3hSM0ZpTzFn
        elVvc2VXVjhvdGlySkI4Y1BJeUpYV0UKOmNHSB6POJt+2WvR1VIxkMKkm18sY54J
        ZL1USbiL6j3PBm+SrpLEyvFMePk3kZJ48Cns1FqB5+MSeYDaYsQK4Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYzNIRFF6c21yTEN1RVpR
        NXhsVjhpMm0xbHdhdDQ5R1RvRHlrNmdOMVNRCjNyb2dYVWlVSTQ4UGF6ZUpiZzRN
        NDJtb0NVdHVpR1IwVG9lMlFVUGtMOXMKLS0tICt5V1YxSk8vajFRRVMraUh0R2My
        QTB2TjY1bERqc3NYTWdjY3h0bG91N1kKUaSixFgn7ww5XrTbOUoPo0bWsobtbHA8
        yOKmptzj2nE5PyQ+Ns6dPaChPL++ufp0QA9KXrsVsosKQ9/VAGuwwA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T18:25:19Z"
  mac: ENC[AES256_GCM,data:w3PnvaYpFCuMzYWPR9AF5EWITHxN5HBXeV6OV0XrtC3IugfbWeglv0RiFeTYj5yU+Cm0z5vbbH2Ur6EeM2LLKwikpZ6m9V7EnwW0mUJxJBhvTCrSfHRJvHPo5vg0yI4LglGJOvTzCgkaXWTXCQEsEe9BxlA1Hzj8ftv950xfuRw=,iv:uP8dGGKFeCWUXlzGH/kSuydp5SYdagj87Xbtb8VuEKM=,tag:3WI8TnFuKO+wmGa7/YwQqg==,type:str]
  version: 3.13.0
