apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-database-secrets
spec:
  secretTemplates:
    - name: guardrail-database-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:0ivc5cQTZlz5SByoE7yKU8l+orDUd7lK1emp6iANSgBA/W0yOzj143cg5vJrpkY4Cdp9AiufDJeJ+dtWqEXkkzDnBwPQCGZ1ZR/q,iv:JOv63UNiy+IKMICqfJWQ00lIIJHt5kV/paCaHfar6y4=,tag:+nCmxXZPD6PngY53eydP3A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQS1JtZmFFaE01SXMxNDZn
        U3A4UmoxWWpXVHBma3ArdU5rb2wxaittRlQwCnpWZmNYZ2tCVW1wR2d3c1hncWla
        SDdrMHVJS05ZQlpyNnFXSkFjMkJpLzgKLS0tIGZyMklQbHUrLzlRbDBXYUkzOThm
        alRNWW9OVjdsL3IxRG9QUFlINjBpckUKgzzFj3dKMs/2tTwUBP5b+ztJk70+FVE3
        kD5JJmnJp+iG7BtsDKlF8pBHuy4wYVMZQH/mnSwiRvV3NwvM/RUYYg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQkV3Mi81elBpRXFuRFNM
        OU1pdGZCTnQ2SDZSY2laMDdxTS9qTkpqb2dZCkVrZ1ZUL0w3K2JjU0FZaFpnaGUy
        OWpXU1BJU2FselkwZHV6bE45ZzQ1a1UKLS0tIDUrNmt1b0xnSnBwL3pMUThIVWcw
        MzB5eUhqWXZGSGJMVlVmVXRxUFVxSmsK2OEiV1NbD85qoObjrQw2oHTJ9M5i7m1M
        U8+ck01q6NfLegkuduKnrOG83yxgr8P11FbxeVkHipWRHbXKEb9wnA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T21:13:29Z"
  mac: ENC[AES256_GCM,data:sDitEbci2ME7Ks0aJK/Osl16/FsOUP3T1lmwflVf4PzplRlg1t3r4pAv0Kd1PwXD9PNJbG7NKt9kWEFzPFZTdaoUIvmkjYXDZGOsPTNpJW1SV8z2Zr5ErwKdQpG0TS8hAWRvyuWUir7wHlaZBrj+vHg6IPcKdwwUkPe09rEVwQM=,iv:yLjrh9aOF9DwdyLHBH+71Ifys9vtpXgNN8F0elF2pVo=,tag:3M4PhkFMCbGkg5eD/KHpHw==,type:str]
  version: 3.13.0
