apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-database-secrets
spec:
  secretTemplates:
    - name: guardrail-database-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:5N2atYyvrdRQjCIm5f7PnQRGkYjFbdbDJyBtA6nBOJBPdBgPHkHDfBdrwlcyz6blDlNo9a3yhP1StrXB6tUWCyFsKfjrA3w2y/Nb,iv:Qm5lvK9WoKLAyFFueiSUVScjHSnKPpce5J/ULz+Y7k0=,tag:VxEGAqBagharNicDypR1Yw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwallWeUN4QlB2K2Z3QWxQ
        N25FRnhERVY3VnJRT2JSZlA5cmltbG1jcHpvCmU0Z1VpVVE1ZFpHZ3ZJMGgzWHJp
        NGh1WG5HRlpPY3NmQjhPdWNGdndzUGcKLS0tIFlyRUpObGJ3bW44cmpEckxNdGtv
        ajVkS08zU3p2cjV1UytpVkMzSnZKVzQKIJnbSeB6CJ4HrsdFXh7jmcetA7JJtaUp
        4avSUVco9zuCCW+gIc2JEbGz3ttgLYyTa97tpDtfBfy4HIDFmyLGZQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1N1Q2SVJmdS81K2hxbjYv
        Y1c2N2VmNlFEQW40bmp2TUJJRGsxdzVOQndVCmg3KzNjOTZYUTdpV3NidXIzMVZI
        cUwxcHRRZXBSMTh3dDd5MmpIYW9HZlEKLS0tIEZIdEgrS2xrOU10VW9WRzVrNFBp
        RUY2dWM1ek5KMWNnbzFKVlpOYUwydXcKaDtKuRDr0cV4iZnDl5KNsUV7G1Jaq1Q6
        Dqom95n3oYFWY18uv2x7m9GYjqYV6UCobQIISP5ovkoMSVMcFAzbPg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T18:25:19Z"
  mac: ENC[AES256_GCM,data:XwiGqMgoOh4mlowe0qGT4i2W2PRynjT6wAQxgM9FXFy/iWQelthHOKp/Zjw3/MF26hWZbcTOiBN5y7m1WcHq2iXJWxkPnqWHb/jAP5Fd9cztYSr6n6qTVaD+Ea8StvNMMLiQa64+4I0jrCHtiuB90K5B5IDsoca32mVeMxGil9Y=,iv:L/9XEj8wVQihgxGMtux18sOQtf/nk0WZs6/1iVGQpOk=,tag:O+QatGdGlfOrZppgdixKWw==,type:str]
  version: 3.13.0
