apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-database-secrets
spec:
  secretTemplates:
    - name: guardrail-database-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:wI3E8ZH876SYgMb8Z4Rh90lpsdA89sK5fkpAB4xRUaQ7s2uyRVctyJjKue3EX8wN1g7V98fwLSw94xln4QQHsOdjpUllCNFj5iOk,iv:Mg3szes4Vc6xx55vRS+CJtwuLsCpz1bCZSYWprtAgl4=,tag:P0/vTE9X0BArtuuCRLEvWg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WDAyeFhCdGh1TVdrbFJr
        Mk1qbGF0b2RvYk5SU0VpOXZTK2hhUGtJWDAwCjBYN21sWllyYjd1b2JBdlllc2RX
        ZWhvNHlQQzJNR0RFN1NTb2NudENMMWsKLS0tIFpIMHljeU1XYzc3ODhDekptOTdw
        eXFjQjFRbXBuZ3dBb1dJaDI2N0FYUUEK+BhZNqESaGgeTmMpSW0H5wRJzBeyxcLB
        McAMM3Kzztn+QulmCSTJ/bLivHKYs1leMhDzlb6VWWJcO7ZNyLYvwA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeXZZVUt2SEN4Wi9Ed2M3
        TkpCdjgxeUkzU3AvNTVsczhQSkhvV1FrTEFrCnNXSHp4dUxKSzFjSGY1Q2MzeXE3
        WEtkVnJsc3ovVkpZdEsxb2dwTWlpSjAKLS0tIGxiZmhiSmNCc01WcG5zaGRvSEhs
        c1RGWWJGSFZkeXlWQzBFTHFNSlJoWWMKKv5+SWSAHiqZ8JlZjI+PPNuzQXd4elDg
        IncbJs5sTvy1B1r40Clx/j/Dj+FJuAD4POa3+Re3kISI2roZwrmjBA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T20:59:59Z"
  mac: ENC[AES256_GCM,data:UWd2gqvG3WK9YkL6IzpO3BEJaL2H21EA+el3A14TYvhHYkEniOZ8xhK2aXEF74vV4wItLykuQkVmeHfUCpQbxZpoT+/zuNnSeVYTsyg1rZa7VG2nk43lUTypZEA38LMB+WRmVn1SUVreXlstlDL3wm+M2hTwrw+JTdubdMK0Zj4=,iv:1AzOs6pI0mm/PwBPFBBuaP/ERLVsA6Y3MNuNPNdPTKw=,tag:dHQWey53yotIsWATLxH7Jg==,type:str]
  version: 3.13.0
