apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-database-secrets
spec:
  secretTemplates:
    - name: guardrail-database-secrets
      stringData:
        secrets: |
          database:
            username: admin
            password: "%SURREALDB_ROOT_PASSWORD%"
