apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-email-secrets
spec:
  secretTemplates:
    - name: guardrail-email-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:AoZavDKpQc68jIS1SIvlDT80ZP3Infyl+pXkHfH4/TXkBpw+aQJCMHEmSdTkFXj+ZW1oQd8ndFM=,iv:FzzhDZa2+xmXPegV96krvh/RgMB2xZ7oPBYrhttEF6A=,tag:gio7RfuapQH/fepNI2i/nw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFakVQRkVsSVZMVFVDTGZt
        Zk5SNXlZM05uVUlNejNpdTR3ZkZnbXRPSlY0CmRleHh0ejhDdUNjTWNKV01uMXQv
        WithQm9qZ3dOQ1VTdy83T3gzNUluMzgKLS0tIFlmTjVCUjZ2VklZRWRPRzN4SDBT
        U1diOFU3aGJMSmFGemMrSHYzUCtNUVUKBe12BD9e5yirirnXzrVypkunV0wINPLQ
        y1Z4iGQhWgVLIrFUQS/vtRBy7FY8Cm00M68CZcKKekU7hJcRtYvd/w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TnBhQTlTbEdKTER2MTdF
        Q1U1MXk4Ylk3b0cvSWN0ZVdDeGI0NlcxRlJFCjdrR0JwZU1BYlZNNXZEMjlOd0JD
        SjdCbXVnckl4R2hqY0YvN1ZhLzFWcDQKLS0tIDlyU3FTdEtOSUMzSm1SNXlmcmlT
        SDYrK1ZZK2V2eHFXcHhPWEpWaVBiS0UKr3RFGTrYXoCBVgARMFtBUa74QjjJkjIl
        HlT93LdzC/lnROlAv2YmP97Dc6qdP7VJ1RQiZCKEFU/lgHL5ZqK1OA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T21:13:29Z"
  mac: ENC[AES256_GCM,data:dKtyXnbtq4pesIF51iH81OmQ80iEAPRe5oI4PgzujudOEvHw2/mteZ/TCAui/KMiFPbB5WdJKyO6PfVNA4gHtk0Qmc44kZ0BpGh7vAWLkaJtnoh3ZDos+fi3nsWOUPH6bprWqOhGRxcWaVZGkMKwdIgxMj/5pGa2j/mOIlJy5Fo=,iv:tGTj/fcIsklrdXM4x4qxLmGDjo9SeKo8JFJgNHcGhRU=,tag:vGAT9r3IUZucNPcf7G5fDw==,type:str]
  version: 3.13.0
