apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-email-secrets
spec:
  secretTemplates:
    - name: guardrail-email-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:RKOM0HHDJVUOjrY/LHZ3cgUS3T/cuVzlnEs9tiF10BLBT1X3vwHJmfPs2TGJKkCx3TEhrIEjvBc=,iv:wpLedvKafQVenOPDZU3tSRpHM27B1avffgaCExdBqVs=,tag:6MDNksZ5fez/IV22Dhm4Lw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYnA4RnV5OHlQelJCQlJi
        RUdCL2R3MDV2N3o4LzFVcmNXOTRxZlY4RDE0CmpEL0VGeGl2aVArODNRZHJJNkNR
        TXRqcnlQZFJaek82U2p4MXZ3VEZhMVUKLS0tIG0zbGJYd3NmOVlsTUJicC96UTgz
        N2NTeHVNNjRNMFI5ZHREYVg3Mk5RY00K5syogfEqSp0NCS9wwQ/jc5ek5h6NmKS1
        f59R24a7GdvDH8+Vff6VH+MV4OgoWCqROC6tzyd8zpIsN5GZu4bSTg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1a2gwU0hiNE1HUGFFaHQv
        ektDSDNHZWM1ay9UbTFzUmI1NjZ1anpnOXpvCnRUdlh4WmphMDd1TENvQnc4WWIr
        Q1pvNGJxNUoySFRVR3lrOXY4bTJ0b1kKLS0tIEVySGhITEtWekhmaTJIT3NGbEw4
        ck9DTy9tYWx0ZE9DdnlyVzRmejNtaGMKMsqbZqPmiBRp45IUfsC/aCQbRlqwe5ve
        eEPLfi9kecBi/Xao0RsQbBqkIhZtF+BdAApB36Hr5tsqxa8N3vbIHg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T19:50:12Z"
  mac: ENC[AES256_GCM,data:hif2tEWVJCA7YHuMd3jF83uI9GZCOLcueb5thQLu8VYkTiTqE6d7oA5ZGXiBnJ0NY56Q4vcbhabK62YpKfj4682vkEVw/asOdbZnmqLLQXFKGbbMcdrK+CR/18xo+XGHmP3Wnzt5pKoXXLGzWr1t9fwC8oOublsvCmsvozlweOk=,iv:DvlExwCK6ZbRrDozstT8+xD0QWqx1zEnjMD+iC/dPXE=,tag:N1I+ni6kMHUUD33qS7HWyA==,type:str]
  version: 3.13.0
