apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-email-secrets
spec:
  secretTemplates:
    - name: guardrail-email-secrets
      stringData:
        secrets: |
          email:
            resend:
              key: "%RESEND_API_KEY%"
