apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-sops-email-secrets
spec:
  secretTemplates:
    - name: guardrail-email-secrets
      stringData:
        secrets: ENC[AES256_GCM,data:DdDsrrE+M6JupAE0i4Zw29i0EXJVtAjCoyEqmrnsjxQ/I95vzxpLnaUcXidVVBR00fIZrMKK4+ZxIGDacA==,iv:NXpsFEsX/ZOQKWd1gXHi+8UkRmrGd8UMQCg7kmzELjI=,tag:58ph4uG5yL45px2MY4ba0g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdllXOEZZaThKTWEzdy94
        TWVvT1dCYTVWYVNxdlN1ajNHMnk4TU9OUm1BCk1PRVlITmt4dTNNNzNLL3FlRit2
        bGhkQWJWWjBtTTdQRElRblRvaXdnTjgKLS0tIHVURHNWdVE3cWlkVSttNTE5bFQv
        Q3c3MnE2RU1qU0Rwcm1kQmdDM3MxRG8KADMh6v8YPeaOtAbQHfSuameEk2pAuky+
        bp3lqBj4BGa8r+tci7uT9FwpmcZpP9iUjjloNlpozhgq+O80RvKxJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjL0NJMWg2NjNQZVM1WTY0
        MVJtQjF1akRsc2VxbEhOOC9Fc1Z6eUEyVVVjCjNnMmxSLzJGTE85N08vSjg1YXNk
        RXZ6R0ZxMlkvekFlbmRXWGlRMEZLVlkKLS0tIHJUUEpSd3VObTkzMXJyYXE5V3Vz
        K2d5d20rZlV3N08rY3FkVklUdytEdkEKkyh4cwNMn3EnI2ukcu3NHtnUILqe6tn+
        SBvcEqtqlAoafjm5/T4EKjArzoqbknYKxphxnkdnBw2I27taYrJp0g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T17:48:54Z"
  mac: ENC[AES256_GCM,data:5QjAcAju+TDJZIXuCWs50skHIudpNlJqdv92gRtgzUtrm5CmM1O3VlL1S56uP9qNpcVmglMII49jJdx44Qg4oq3HsNe4Omdf6O0ONRm2dmmVBqPfcmHQc0qCI3dxQ60ohrmonNdenvSzuYa6aHC5Hz6sOXLxOsaLGlfuIwvFeJA=,iv:f8ALRiMhTvHFDge3+DtwyNN7gW/8G+vKzA9970kQqAw=,tag:3yRJGrISTsdIbNt8H6pgWg==,type:str]
  version: 3.13.1
