apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guardrail
resources:
  - 02-valkey-secrets.yaml
  - 03-object-storage-secrets.yaml
  - 04-auth-oidc-secrets.yaml
  - 04-auth-jwk-secrets.yaml
  - 05-provisioner-secrets.yaml
  - 06-database-secrets.yaml
  - 07-email-secrets.yaml

configMapGenerator:
  - name: guardrail-config
    files:
      - 01-database.yaml
      - 01-object-storage.yaml
    options:
      disableNameSuffixHash: true
