apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guardrail-ingestion-rolebinding
subjects:
- kind: ServiceAccount
  name: guardrail-ingestion-sa
  namespace: guardrail-dev
