apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workrave-apps-bootstrap
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: workrave.org/environment
              operator: In
              values:
                - production
                - home
  template:
    metadata:
      name: workrave-apps
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: '{{ if eq (index .metadata.labels "workrave.org/environment") "production" }}https://github.com/rcaelers/workrave-infra.git{{ else }}https://k3s.home.krandor.org/rcaelers/workrave-infra.git{{ end }}'
        targetRevision: '{{ if eq (index .metadata.labels "workrave.org/environment") "production" }}main{{ else }}staging{{ end }}'
        path: apps/app-of-apps
      destination:
        server: '{{ .server }}'
        namespace: argocd
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          jqPathExpressions:
            - .metadata.finalizers[]? | select(. == "post-delete-finalizer.argocd.argoproj.io" or . == "post-delete-finalizer.argocd.argoproj.io/cleanup" or . == "pre-delete-finalizer.argocd.argoproj.io" or . == "pre-delete-finalizer.argocd.argoproj.io/cleanup")
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
