apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-db-secrets
spec:
  secretTemplates:
    - name: guardrail-db-secrets
      stringData:
        GUARDRAIL_PASSWORD: ENC[AES256_GCM,data:vyc56U1Vk0OU6k5XiHmjUsI3mm+s6GwP,iv:q1FdpE2cWQLLUHBqxGJSM2v3hQtRMMt3Ffiy7iekODg=,tag:tyZf7BoAGK06xWiJLX/+7w==,type:str]
        AUTHENTICATOR_PASSWORD: ENC[AES256_GCM,data:bHs8qw8EdbkQRmmfsMWHvdUSB13YY9j8,iv:zbvlfSxrqItCUzzkAklMBxIbSway5oHsRIRQYD6lWbk=,tag:tyDb5FWe+o4nVQUpyX487Q==,type:str]
        WEBUSER_PASSWORD: ENC[AES256_GCM,data:z+UMibUBj5TGGcryIBwmAczDOCS0Aeo1,iv:6nw+CK2+gwOX3ALYXvROpshSw98oL3h5CmuZ7FgFrm0=,tag:xht1wFheTyOUuNYV8P+qcA==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOU02d0tqc3N4MDRzSWFa
        NTBMejN0SXBOYTFpV2hDT2FPL21kSTJoY0ZzCmdkSXhZaFl3cnVwS05XeGVJVDlw
        ZW9tUlpiWGNrNU1zeUllQUF1QVdKYXcKLS0tIHdwbTFhZDNtNENmZzBrT0JDWDRu
        bWV3NXgyN2NobUQzbXNPa2Y3UVZXUncKXeDDCADg7/1qpCvkB4hSGkOuoJj6uj+x
        tlb7CwO81CfABvtPOji99q8hCpH0SrChudFd18XU5suULqyrpddAGg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxY2tTa1QxYzNQbW56Znov
        RDQ2NThmV0tMS1duQmlEUS96Z0l6V1hMK0RFCndzcDdENHROZkZRRmpOb3VIQ3dL
        VkdPV2NFQ1FrTlMzVHBMUXMvM3BGZXcKLS0tIHd4MVlNbjY5T0NXRkN1R05hRGxn
        S3k3c2lLM1h3eXcxdm1rK1ppT1Bud0EK/lWGYml3S21m4tIgk9DemACVNwPxl9OV
        SZeieV1Kjbw+gmhwnkXnHsKecZlMJslb3znROiC6txWSNeLtginpZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T17:21:54Z"
  mac: ENC[AES256_GCM,data:Dq2KLCT5QmvCHugGSNj0tOpKzmca/T4jR5x7xZ7ELOkbZ0bjrGI/8Ushe1pxqc0GgFzj8ya70kts79420ie/2XbztnFAYVMjDK4kp+1I/IHUmfZlSs+ugIrqtkcKIp4XM2AcGbCvm5y3bX7BrQZd3tgw87eD9IATNXK2Lpj4ZSM=,iv:U5QXV9PGZwYdO4kHlboDFVkG7ZReC65XNM/4GYI9pM8=,tag:gtU/kOc/Q6ZHpIwcWUOO7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
