apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: guardrail-db-secrets
spec:
  secretTemplates:
    - name: guardrail-db-secrets
      stringData:
        GUARDRAIL_PASSWORD: ENC[AES256_GCM,data:fZD3c2fPELx9IjzF2glgzT0CCkOEw6yN,iv:DbqQTB9TTEfik21eF1uRx2cAgBDNCXxz3TLbLAJ9vfk=,tag:uSzOShwmOlg6jvLeqEzrvQ==,type:str]
        AUTHENTICATOR_PASSWORD: ENC[AES256_GCM,data:ysGgBHQe7D9lp2TzLAZuThn1bzh5lgnG,iv:8fea4IwW+QYG2E38H/VfTHn+CYGdKu5Z9uZzxGBVzx4=,tag:UGWmILhv54ZcgPZw8pigFA==,type:str]
        WEBUSER_PASSWORD: ENC[AES256_GCM,data:QA7K7RQKf6AUnSbi1PqT4QFJRtYazVKc,iv:ZqTW/X5Kt6owMscgdjjcla5hWGHT7BZA9N7sn36doa8=,tag:FazJz6UnZIsjr5DFvLh1zw==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZlI5bU9SelJUNTZOc2tT
        aVE2SHQ5cGJtUWFwaTJNYW13Zm9tUk8xSUZJCll0Vyt4cTVVODlkQWFlWTZFTnZn
        KzdMUWVpejBmRlp6MXFhSFlTM0J5b3MKLS0tIFRVN3RWbE1QbWJnTDR5QVcwdkEy
        SG9VZmVNMnlVZGY2MDczMGJTZ2hHalEKekCd08R1hYUv0ScbHb157P7faMsZCMVV
        SG8r9kMU2Bm0fg1h/8s3Igy4pRuOQ7FTm4oQtbcOWsnQ3lYCyDDVFw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbTFBaVhJMU1nTi9IdnFX
        QzczdjVkcVBHQUFCbzJjKythazJYc0lZMWlnCnozdHhFb283a01ydUVCSjNaQ3Qv
        bit1VDhyejgvU1dEcUxHZ3JVMTlkeFUKLS0tIFdGakR3dzAvajZRWUZUNW1MdmUz
        d0hLdVJ1RlZFYTZRQ1QrL2pUa1dyVU0KC0yI7/alD/5DQr6iJUcT1oysARLBfmoR
        Ay4GECEyuG/P/ndpzD5NGOCeUEG11uoJ5s462TRb+xhA872v8mrKaw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T22:15:11Z"
  mac: ENC[AES256_GCM,data:VLNZj3EN8RBNCrP1FTuTV9++sXyIPGpukBweRm5FMPrtFG1LsGL+xlSTbI9Tc9r7MK+EoJFZQ/tczAiIWRDevTxoBCqBwMjJU/u4J6Hk6Tadfa16KKMnIWO5lc7PPEVM0p4dtKRvX9AopmEJjY6mLg8lsx9U73ofop4/pp60+5E=,iv:fQoYG8jNgHpe/7vabKC17PDqykBvAFiGuRG6lTbStm8=,tag:+MQ7wtT8OBQW5FX9EEKy/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
