apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: postgresql-superuser-secrets
spec:
  secretTemplates:
    - name: postgresql-superuser-secrets
      stringData:
        username: ENC[AES256_GCM,data:kq43jXcJU/Y=,iv:w61MAHfghceOAXI3Za9i7TJuRJIzkhrlZijgFRDIxko=,tag:CSOe42lpHytS6l4hEW2ILw==,type:str]
        password: ENC[AES256_GCM,data:Pg8M6s9AhSBBflZdOPZ2yW1N+4bhMRvH,iv:2OOg3i1Rgj+aHLibqJZYh+wXquvcEQBrlyGe79umvx4=,tag:6SUT0APNRjI+sCvYJNEXIA==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3M3MvNDFRQWd1ZlBFMnFZ
        SjJtMFErUEkxVHlVR0RyRkZNeWFmS3N5SlRBCk9RRUhaTHFDTGg4YVo2STRTMGU3
        MVVjTmhHUXVoc25YRk1sbkkvcld3SWcKLS0tIDZVbnVRZUo3Nk1uMVBkMWg3VFRx
        MDdFU2JEV3hUQzlYaG5DNDJXWk9VUTQKCOiUrt4W7GF/CdR7Jm+RiATZoc24TuxH
        W8/a3ahzT9z7fPdVMm+Rbm+dU8fa1Q0y+yvM81XSxZ+wH9UWxrtq2w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcHVPSDl3dmVtbkN1TzJl
        WU1FbnV3cXMxc251b01TZXVoVndFSDRBVlU0ClovL2UrcVFsMjBTZ2NwYnVkUllp
        ckIzM0VLYVoxV0J6Y1NaVTlUbUova1EKLS0tIHZPRXZlMjJRZEo1cldlcjZYVERr
        aW0rR3FvK3ZQY0tRTGlVbWwxdkorTG8Ka6ePajnDYipWDsM1ZLfw6lErWMAXWOrQ
        BptQsIFKp5GZgD9VKFf4GBFqXAb4iOZtOLBFLkw2WV326qEGzUGenw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T17:21:53Z"
  mac: ENC[AES256_GCM,data:SDC3J6TokKu9+7fo1ruC1GOCOyLbktsxYMsVg16I4K0C/lJMBH3JKMxy+hEBPQ/jdW3/FVNEFbd6q5oqoNU7JT2x3jmOk3ZQjFbi56eYonkbHSN6mO6nTbdEbtMspaVQQxq0E+yZHxD1gsYlwYyiNxo9sYYwRHuwA7FLWss1Q+A=,iv:Cf+6jbl914PUlIiAo6JZ8r46z+t59qKJGovlY7oxPzo=,tag:cLX3S7hbZ/eoVICBkeQnfQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
