apiVersion: v1
kind: Secret
metadata:
    name: postgresql-superuser-secret
    namespace: guardrail-dev
stringData:
    username: ENC[AES256_GCM,data:L3ZoR6R96YA=,iv:+iZkmX5OwRK0rpTk0SSIkh8lOF8xecT/8Ywziw6grqU=,tag:If/dYLjh8wg4kLp7ed3Wnw==,type:str]
    password: ENC[AES256_GCM,data:TW9l1qu06QHANsWrSopBqI1xyFg4iEY3,iv:2w/w9DF/o1HfHwpTDcUabqixMlGPCWpDzhqTNMuaSw8=,tag:l/KZFpqCfWgpe9+D/o6dnA==,type:str]
sops:
    age:
        - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RVAwOUd3MkVzVHMveElF
            VXJYNWlhYldScXVGVFNwd0l0Z1U1VmVrWUc4CkF3cjdNY2o2eTkxMFZkRytoL3c3
            MWd2UWVvMHJKUlRLVTAralExaEIxRHMKLS0tIGszTmFJbkx4WFZUQ3FQaEc5Nzd6
            WjhHQWhKK1NQdnlDT2QvUTZtS1RiMzAKwojf9e0CvY8ZUEENyiqlo5+CsKhtyOOF
            zdbGMcfWL/9aIoPxE3OqvlDnFawfpJSmDYP8tiwHQ1/ao0HuF6QV9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RUthNm01R1lCdDZZRzdB
            Ti9Ba0xVS1JzZzVFbW5PZ0l4L1Fwd0lYeDFZClZDZmhxYlVtdWcrS0JNdmx6bVRF
            Vngyb1h4NjRUTmpOVCtrUFk0anhzODQKLS0tIE9STjhrRkZwN2hXOTEySVhBWUk3
            eU9iL1lpeTE5WEJPNTh0MDZHK1lyMGcKCNPgzEwK84Q4gdloztyg01caO0ZDgm46
            aNuWRx4cNOZEKEjemJbqUevbnmBGvVwOHrqMXHctmzzW6ePE9KkKkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T17:53:55Z"
    mac: ENC[AES256_GCM,data:pDdt0PwWwc6QPgjV/R5ZYMXi2KUFD1c8q30RzgH+HDsEtcMiUg0LMPJFyfgexPHGEkM/1vMDWoqDWlvOOlhjH4CP+8KyOW/lU6WDrVaFlj0UbFAEBEjaU9V/2/fyoZ7X+O6d75ka9/cqlZ2e3Nb9RtsLSgD/fSuXr8jwlVmht6o=,iv:O8f8QrRy6faspPPa2WfPg8FgldJKxHVIQUviVSaDKp4=,tag:qICMJjlFvROMYSymxvF76Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
