apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.tailc4583f.ts.net
  oidc.config: |
    name: PocketID
    issuer: https://auth.workrave.org
    clientID: argocd
    clientSecret: $oidc.pocket-id.clientSecret
    enablePKCEAuthentication: true
    requestedScopes:
      - openid
      - profile
      - email
      - groups
    requestedIDTokenClaims:
      groups:
        essential: true
