apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, admin, role:admin
    g, rob.caelers@gmail.com, role:admin
  policy.default: role:readonly
  scopes: '[groups, email]'
