apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guardrail-jobs-development
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "14"
spec:
  project: default
  source:
    repoURL: https://github.com/rcaelers/workrave-infra.git
    targetRevision: HEAD
    path: apps/guardrail-jobs/overlays/development
  destination:
    server: https://kubernetes.default.svc
    namespace: guardrail-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
