apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guardrail-jobs-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rcaelers/workrave-infra.git
    targetRevision: HEAD
    path: apps/guardrail-jobs/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: guardrail-jobs-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
