---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - argocd-config-app.yaml
  - sops-secrets-operator-app.yaml
  - tailscale-operator-app.yaml
  - tailscale-proxygroup-app.yaml
  - kyverno-app.yaml
  - guardrail-setup-kyverno-app.yaml
  - envoy-gateway-helm-app.yaml
  - envoy-gateway-app.yaml
  - cert-manager-app.yaml
  - victorialogs-app.yaml
  - fluent-bit-app.yaml
  - guardrail-resources-app.yaml
  - dev
  # - prod
  - tailnet-admin-app.yaml
