apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-guardrail-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  info:
    - name: errors
      value: "{{ range .status.conditions }}{{ .message }}{{ end }}"
spec:
  project: default
  source:
    repoURL: https://github.com/rcaelers/workrave-infra.git
    targetRevision: HEAD
    path: apps/minio/overlays/development
    kustomize:
      buildOptions: "--enable-helm"
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
