apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-guardrail-prd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/rcaelers/workrave-infra.git
    targetRevision: HEAD
    path: apps/minio/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
