apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-prd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/workrave-infra.git
    targetRevision: HEAD
    path: apps/postgresql/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql-prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
