apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 10-foundation.yaml
  - 20-observability.yaml
  - 25-envoy-gateway-helm.yaml
  - 30-cert-manager.yaml
  - 32-cert-manager-linode-webhook.yaml
  - 35-envoy-gateway.yaml
  - 40-data-plane.yaml
  - 50-guardrail-setup.yaml
  - 60-guardrail-services.yaml
  - 65-guardrail-web.yaml
  - 70-final.yaml
