apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - rate-limit.yaml
  - network-policy.yaml
  - service-account.yaml
  - role.yaml
patches:
  - path: rolebinding-patch.yaml
  - path: database-env-patch.yaml
images:
  - name: ghcr.io/rcaelers/guardrail-server
    newTag: "db7abce"
