apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guardrail
resources:
  - ../../base
configMapGenerator:
  - name: pocket-id-config
    options:
      disableNameSuffixHash: true
    envs:
      - config.env
