apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: pocket-id-sop-secrets
spec:
  secretTemplates:
    - name: pocket-id-secrets
      stringData:
        ENCRYPTION_KEY: ENC[AES256_GCM,data:7Valjpb/bW6j2v5qjX7MCFlhg/u23d/aWhyq2mpKPqiKF3sJmaB+HTCGRIE=,iv:+Gxuc6BFju2rMoZ94DSnHo8hUFMj0KjYeQN2Dtqmh7M=,tag:sRtUDkYdNK53KqY0peAgUA==,type:str]
        STATIC_API_KEY: ENC[AES256_GCM,data:hSdslVbuo8PJpu8AyI0Ly9FNHVO0HhwyJFVh/VvlYuQ=,iv:Pd4a8WE8XF3WBpMrxiy8IORTxAncVjMpOR8BBxh8tI0=,tag:V3gcMSYKaYP/WgPTp9iCNQ==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwelJRQzIrN0Qwd1Z3VDNY
        Q29xQllTK2VhQ252dWo0QzEwVm5UUEp4S2djCmwrSDlYUFhnQlhGTzdZTzBTV2FC
        Y1I3ZEo0OTVMQ0YzZFExN0dsSUNXelkKLS0tIGI2RXhwWVZuSmdlbzRURFNCQ1BF
        QmlrLzNGblFodE1saGppUFNWZ2hydUEKvGoEkVdUtHSbG7hDVMwDxYbFmTqDSpu7
        CnRbdgUt0izAUp4nYbt9w+9GUlEfyEGSZVj1V1LdPj0sZh5xfg3Ukg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cTZ2SEZmRytkRlBzY09T
        WnJ6NGNMUHZUWG9GM29uZzM1SW5kWXo1b3pNCmM5T3E1MmgwSGpoNENhWGkrdk5R
        MWFsT0FONktjcHBJcnpocFBSSXN5T0kKLS0tIFFhWjNBQjBoejlPZ290TldCRWll
        SFIzdlhpUzZWbDR4MkNJbHcvYTRFTlUKUUYDzs644B1kt9824rvCQULX5mFj4A5P
        I3JiECbkpEeYgQ7HoqU+rWyPDnXqXGJNINrwQZIzUi6P4btS+Gt26w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T15:29:49Z"
  mac: ENC[AES256_GCM,data:bRR7z0p8pXD8Q1e4T/uiqYs2qcFH+Wadj2tcmnrLfTr30fBU33JX8rsyhsvKkfC9DhubcxcgJKRonKEKrvXoK5AE9z9sYFm/dtKYqd6RS9Ns5g6sQVb9DpsO/vtyo9q2IYE8TLEH3kJbUtxFSSmK+LxEZzG0Yy+KKDEoDFg0mDw=,iv:GXRwdtjVFQgkz70pBM+qMKZTr3j7REmB5oDW3xj7cjA=,tag:7C22DSuiIF6YMzc4bInwsQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
