apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: pocket-id-sop-secrets
spec:
  secretTemplates:
    - name: pocket-id-secrets
      stringData:
        ENCRYPTION_KEY: ENC[AES256_GCM,data:g0Fmx3PbjqqwBmC0qO2XQjDlihEW8/loAYKdANEDyU0lGaiorFasKbX1rtU=,iv:zFop0YiOflWXRclCy7o5Hn8ZoqtqXdckE6wwWs8TDPs=,tag:Hro8PMMdi1jjUUGQLkc4lA==,type:str]
        STATIC_API_KEY: ENC[AES256_GCM,data:xgRjj9B6WhcwdDuqLaMlvXLAuCGYuBkGik+RmNV8WWA=,iv:laZtA3S0mdhY/4skS2KzmGK+4irvEv2fRpky3AfO9Ok=,tag:EXvLi25x7AaNfYofQk0JKg==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OVdlR05IMjJDb1A4ZjA1
        aGZWdnNsUDN2QloyVGV3ZThaUUpHbEorN1gwCnZyL2p2dS82dEVLTFVZTm8xYXpp
        Q3N6UGphWlB4eTZtaXl1UHEwUHJ1MEkKLS0tIEVTY3AxaysxV0U5UFNMdGw2dE53
        cTl3ZklrYVA3VVlnemc4NUhocHhUb28K7QsI5cfUvWIKJWXKQA4PbanNNlUByz3M
        zaLbD3pUFsGnMFM59bQLR++8z2t6GlxdRijwZGGTUaXj0+F3cJw5Qw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cmZiZUZWOUpuMEV6Sm4r
        M0pFc2VJQ0pJaXpIZUluMXArZWdiU0ovUnlnCmRuaFdOZXRhUWtDaUg5cm9PeGp1
        MURuS1V2M1pwUk8vVXMvNEhNOHpxaHMKLS0tIFdBVHI5ZUExVnpIWUQ1Qjg3bnJ3
        US9SZzBJck9pM3U0czRkVmdpZkx2dFkKzRW72NLRLbxBOJegKmcQDyXe8Obdv6Ku
        eVMk3yxVdS6BYnezZW0+/W3ENtiS2hSfGV7iAW76u6TsbMbnSur2qg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T13:48:44Z"
  mac: ENC[AES256_GCM,data:5v1VvF0Pb2dSkhPojUMXiZ9XQzKL7Xq9dbgUvn5iV2WnsoV0IC3H+k3eMVILMSnMSAAHaBC2O2SfostP1PaCOoYro+5OXBjNTXLOzfw8TtMBJ2NqP+ll4wWQgMKWOqfZzXj22wGly7YBfDBi/IVQaHygPacpNUuYzfkyTTxaQT4=,iv:3kQ5DhQPZqvBeT1DDNAXJKXUNTVDOM41YcuJSJSIGAY=,tag:NClR09V7s2UNqnTC0Vtdow==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
