apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

helmCharts:
  - name: longhorn
    repo: https://longhorn.github.io/charts
    version: 1.10.0
    releaseName: longhorn
    valuesFile: values.yaml
