apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-tailnet
  annotations:
    tailscale.com/tags: tag:k8s,tag:shared-longhorn
spec:
  defaultBackend:
    service:
      name: longhorn-frontend
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
        - longhorn
