apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sops
  namespace: flux-system
spec:
  interval: 1h
  releaseName: sops
  targetNamespace: sops
  install:
    createNamespace: true
  chart:
    spec:
      chart: sops-secrets-operator
      version: 0.28.0
      sourceRef:
        kind: HelmRepository
        name: sops-secrets-operator
        namespace: flux-system
  values:
    extraEnv:
      - name: SOPS_AGE_KEY_FILE
        value: /etc/sops-age-key-file/keys.txt
    secretsAsFiles:
      - mountPath: /etc/sops-age-key-file/
        name: sops-age-key-file
        secretName: sops-age-key-file
