apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sops

helmCharts:
  - name: sops-secrets-operator
    repo: https://isindir.github.io/sops-secrets-operator
    version: 0.23.1
    releaseName: sops
    valuesFile: values.yaml
