apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sops-secrets-operator

helmCharts:
  - name: sops-secrets-operator
    repo: https://isindir.github.io/sops-secrets-operator
    version: 0.15.0
    releaseName: sops-secrets-operator
    valuesFile: values.yaml
