apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guardrail
resources:
  - valkey-secrets.yaml
  - network-policy.yaml
helmCharts:
  - name: valkey
    repo: https://valkey.io/valkey-helm/
    version: 0.10.0
    releaseName: valkey
    valuesFile: values.yaml

patches:
  - target:
      kind: Deployment
      name: valkey
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value:
          secret.reloader.stakater.com/reload: "valkey-secrets"
