apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: valkey-secrets
spec:
  secretTemplates:
    - name: valkey-secrets
      stringData:
        VALKEY_PASSWORD: %VALKEY_PASSWORD% 
