apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: valkey-secrets
spec:
  secretTemplates:
    - name: valkey-secrets
      stringData:
        VALKEY_PASSWORD: ENC[AES256_GCM,data:3QjnjMrrUm6Z+jIqi4gUq78hB7iirXKV,iv:Nt5ba5vtSRvk03K6YUEtIrQBppIqiA9jmEeAu+Bhtjo=,tag:10QNExZzAHhKpKOY83BBMQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVGQ2VCtWUFpuMExVaEp6
        Qkt3M1hleXN6QzFuMGtRTTJZY0Q4NzB0ejJ3Ci9zSC9mWjdMcTNVdStUOTE3VVVS
        UW4xRmlwbHZaZmNVRGx0aWhoc2RIK0kKLS0tIENTS0JnZGViU3hMaVV1K3pSSno1
        ejdpWW4zb1c3RjlKckx5dGd1ei9IODQKJkpghCKNRpJGhlWo+2PdmVWrTooL9AaG
        9HSVy4H7dkWlcSMsSmb6fVxjhhlMiPKnQyL+OgRL4J3iqo1kCj7o0Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSmE1dW9IZU9pSmF2aXBz
        aUl4eGUzVHhJem1vM213TXIxQUhwZW1OcWdJCnpiV0pyL0ZJNFBXaGQ0SUFwWkxi
        czYwbVRqbmNnUDVuSE9zU3VKWG5uSDgKLS0tIDdjaHhHTXRYVC95T1hrOC9URFBk
        ZHhlNEM5Q21YbTl2TmE5YzBKd0lzbG8K2CljFZlgiMCZPJzoG1ysnGfWa/F1R38u
        YvaXtWGsvComkLosqr5b3dO/PlA0KTIJlAWpWsh1V1GxJFGXIeD7Sw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-13T20:39:48Z"
  mac: ENC[AES256_GCM,data:15ZJ9DNcB3vZrWaw5V+W67wD+UKZlrMKXp6xgUzqeCrIj0B5ufEBkspLTle1+zoRPm0ZqrkIgIHpk+GtbVBFFUDs/g8Q7ZtzBHfhOfBrbAu/Iv9cUdoQ0W8OhTCk/LQm25ofikMkp4UL+9NkBhls7FRA3PxXr2F5Njk4De9yU9c=,iv:dqPFPPzu31vD9pVpy1NlgoBnzoibYg8Y3Q6tCzLBrbo=,tag:5HZHfgXqssXrCp3u6fGAUg==,type:str]
  version: 3.13.0
