apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: valkey-secrets
spec:
  secretTemplates:
    - name: valkey-secrets
      stringData:
        VALKEY_PASSWORD: ENC[AES256_GCM,data:mFkRYrTccWXDeIyrAoX7D1Yx4d3rn9k38EeUvBPrdOY=,iv:XpAWUi8F74r5fGHZlRTnhGXRbeyB1Yib7GhiejCzCcQ=,tag:vAbAwrYrD5NDmHSv2OZe2g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESUFsZGx0LzUrQkFqWWFp
        aWMvbnZyYzYrclRKK3N1bFJXWlZicHhjWFdnCi8vWlhYZUptOVBHOFhTRDZwQmlu
        cjVWS1R5dXluVURkYlR1d29LL3J6MWMKLS0tIFZIb0lZd2hmYlpoV3B1QlFDdm9N
        SFJIN3hTQnRmUm53U21jZTRsWmk5ZncKUsNHpafJ/m0tkpobXRIOFGDQwqJFlvZq
        9V/ofHMqEEwAT7qPXVE8D3MN8bBhYZ1NSBcBYbDQyDzD9qcwrdxRWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dGJocy90NEtMWW02SXls
        VHB6Zkh6bGdJTWFwZTlmWC8vTExPY0NwMDJJCnNEWWlSYzZ0dXN2TkY2ZnhwQUxI
        dzVrczloRTk0V0NPSGZFVzhmak5ZSWcKLS0tIDlTRzRVMW5sZDVidWZQY2o4YWcz
        TkcxSVpmNFg4akRXVHFrUlBPby9ld0EKDUQthLK15O9IRjzDwJZzgn1YiZ2v8bhj
        Zgti9Zx8TOnCFbXPfcmR5kfTdiDC0G7Og5OcstERCnTUVhANwOY4IQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-15T20:37:03Z"
  mac: ENC[AES256_GCM,data:fR0pX1mz1bCWqkS2P5o/1Evv3DGkJJUzICiIqC3ayAW5++lSKqvgewZGtvI2jeV4ZrtriekI/tNn09bQDA1RzliF6iXmMuc1bvbVvK3LZZkV5JISpA0iPY31j4oDIeD/56dHehO11v0ZjEhcDF2D43wD5Mr9PQSe1ubjlkgrlTg=,iv:2ptKuv5C7m8tL+ugv+02RzRjLwDuzzXwlbrLCXbXSrI=,tag:gBXSre1N5SPZgxSz3ml5kg==,type:str]
  version: 3.13.0
