apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: valkey-secrets
spec:
  secretTemplates:
    - name: valkey-secrets
      stringData:
        VALKEY_PASSWORD: ENC[AES256_GCM,data:iSATZKn/2YoBsgKMp7RVicfWAr7S0Rit0KMuf2WlMZU=,iv:ulvmouPR8llY/9d4aDwCyDKiiUctuv/iqO0BiF5OOq8=,tag:B5QODh0EYGhB2E6MPN3WnQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVzkzUy9kaGpaMS9IQ3RB
        ZHdIZ24zMVdJc0lQVXdBM3lHZisxdzdQL25vCkhubVJiMHNGcW9pUGxSV3l5d2ZU
        K1F3OW1mRGhOZ3RpRlJnM2xYM0dESXcKLS0tIGJwTFlUSytCaWozRnBtY2x3Mk1V
        NGwzYnJVTHNmWHNoaEF3L0taOGlHS1UKW4ZQMLa/D0eSD2ljV67syPzUdb2HKkBi
        N3Ze+ObZFODRFm8LUv1yBp43UMMWFQ2EVDnHP/q2ACVWsbbLhxB8aA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeG1tWFNHb0tEM2tlMjZN
        bWVOekVZdzh5aTNmSHI0R3dJU0I3UkduSndRCm9lcjNycXAvdjRUdWhrL1p0RElP
        Qzk5SHc5MjVVVHI5WlhCanBMZk1UeFUKLS0tIHh2dlFTcDQ0TzJpL3pLaEZ1YTJ1
        VHFoWDM0cUxFVkkzbDRwb09CanNuYWcKcgaVuVEg8CP7VnS1bl8/UvfVVla0CozE
        aX9pWxWf75rFIBJNMBY9ih0fVRkzr+IT8VGFH5Pd7kgoR6FO1GbZpw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T20:59:59Z"
  mac: ENC[AES256_GCM,data:SYgTgvY1l9xwn6aB0wQYMdYBsXiH+eB5nwmBPqYwEsQYOOGKHzn+5omrlk7D7IxiWEP1b+p6ZKKCvIThn9c9B4Fi96WjGIXv4jPq5UA7rXBSXUGXXpP15SNPTpCUyLtCGwJFqQUqxLOoGCliXNwgdG/7R3PEWELEihJvOmwQP7U=,iv:u+GT2Ny4Hb29d/IXndEsTzobwD6ob9/4N8Jz+j7duOY=,tag:3BHlrit7blJ9rC1gAYFzKw==,type:str]
  version: 3.13.0
