# Fill in client_id and client_secret, then encrypt this file in place:
# sops -e -i apps/tailscale-operator/base/operator-oauth-secrets.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: operator-oauth
spec:
  secretTemplates:
    - name: operator-oauth
      stringData:
        client_id: ENC[AES256_GCM,data:BW8vS/JClcoh7Pok95k456w=,iv:eb/+O2CsK5TYjN4oUX0oEjd1fEo08Xi+b/9+PtsXr6s=,tag:+QMAZgxPk9vWuAEtHZadpA==,type:str]
        client_secret: ENC[AES256_GCM,data:BGf83Fbede81R/emSh0tPB2E8RJtqEBcpnTHjl17bNg6jwXw8rlMApM027a0YbddxhxSfA5dor/M3KIVOFVXvg==,iv:qU006+9NDEtINv1e9gKt3VdH2GDFMryoMnJEHBw5mxQ=,tag:rR3l7v3aFsMq7rypya5kbw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueG1xcnFZUS96dkRPU2RB
        US80NmY1S0dKQmE1K0k4ajNEMU9wVzR5YzJVCjB1c1RmeSswUEJZMUQ3VTFsVzVI
        ZTNvYWVwWWljRGJtTVpUQUh6anJrQncKLS0tIDJmeks2ZjVaY1BnUnh2U1Z6eVVx
        NzMxbE8reHh6RmVCMmN0N2tGcUIxNU0K8Sct+DOoFvhgy8M8R9O2NvswYv/cOqAX
        ndMBhuHnbKk4LOf7oAeG8amLjr9K4i2ipcctkV1YrQBPTiLUAVzEjQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRXEvL1FDY3dxcSt4Z2w2
        UlJCUVpINVQyV0hFUWIwWUlYbnIxU3N4RDFFCkxEU3JFZ0drVzAxLzF2ZVlnOXNE
        djFkcCswQnRNbGU2K2JYalY5eHkrMG8KLS0tIHdaNGtQSDU2UXluNnZ2WTV3ZWF0
        L2t2ZkJhODlUZUlkVDdBRy9lazl5MjQKCoN4K+GGEXUJC3/u3r6gHC11reloC7HW
        Lng4l0FWXpAnAnIumN9Aw92gfYtUDubXsDu5biLsBlyFsVSmJR/URA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-13T20:39:48Z"
  mac: ENC[AES256_GCM,data:XYNY+YF6iN9VJYXuvr97RxEjIKtT8CAq4b8tgJtSJaNxJw6w+Hsc+5w8q0Td2turCmxbXmyfnBMUSHSr5DFphEgX7kK24TOBfgErrXVyC2ZOsA/rxXPD9Vp3Vyc4IxvxNv59ApUIescCwI7VLLMqtnjnKDN4ZHV6wM5iGosj2Nk=,iv:zXkcLReus0d4KALdW+IE7lH8AdIdk9Rf8DTCxBH70jI=,tag:fUzzXdXETSs8j0iEi8LTqw==,type:str]
  version: 3.13.0
