# Fill in client_id and client_secret, then encrypt this file in place:
# sops -e -i apps/tailscale-operator/base/operator-oauth-secrets.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: operator-oauth
spec:
  secretTemplates:
    - name: operator-oauth
      stringData:
        client_id: ENC[AES256_GCM,data:T+/XLutOlEsLmnKd+gnbO9A=,iv:66s1WLpOf+Khulat+pzgzipz5B+JofzfrzMC6bZm21c=,tag:9ZCDbeP0Qpq4xbKAlJDmJA==,type:str]
        client_secret: ENC[AES256_GCM,data:bysptd0Q9+/yOTaeOVjqjb1qxdWtcqS95wXu/wca5fErCGFDxjIIyl+yNiTbo6dJJa/n1oBNkIunXuT9QJfb4g==,iv:RVAqMlA/F9JdC0LQ/6cGu0RbVCwoVgwI5tKhtl8UMZU=,tag:vjwc7vEP1fwIyqVOvx5Alg==,type:str]
sops:
  age:
    - recipient: age1srj8ngwukh6qn4z068mraqtr6gy8t7cq3xatut6zdx26e34uwupqj6r6rt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVanliL2M2WkJ6UjBBcFRj
        Rzk4MWFxUjU0RzlWU1NHT2dEUXpCcjhsMFdBClBBbzU0d0o1dmcrVzBVTXpKMjZH
        UlV4bzBYdk1USjdGbzZDeVdZMmk3Zm8KLS0tIGxDamtSL2tMUVNPMHp6dGVrZHE2
        N255SVREVDQvQmoxYk5ic1llRUl2R2sKIrPp4veQVSIkwN0cOu60fNeqntu3xo5V
        VBIMX7Y/ayugQDJayq9/TGuWkbrj5RPur+NHHZqkxttwO9ulZUQr5w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1et9ccr46ezg0ragmeas208aanrqw95v3hnd3j623lkwmgq32nedqpl5z3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYlNGdGl5OVg0dXJjUXRk
        amppUDB4MEk4cWQ1ZUdJWGtlZHJxNkplSnk4Cm5kK0pYZjdJRUJOQXNlZ3U0RUc1
        MSt0MHYybFdVb0VQVWpybXBteFJUZmMKLS0tIHZjbU0wRURDOFFxNzhaQU85K3hQ
        VmR5UkIzbXBBdGQ2aElsTElDbmVJNlEKQ/ENOL3vBp0i5uwZL2hZobBaCeYLX5hn
        AfpKdhg3M0FEcKleQW/N94/PKhpn+NbhlA6LiytFLsv1WV92UjYp0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-29T16:00:56Z"
  mac: ENC[AES256_GCM,data:eijTsQAUoxTMgxbLKiSy33EwN3k7ZAF7/x74JJNtUmfqNlLPyXS9q+EnUrp3iaENvmpY3SQ2NCVaZqPnDdkWn+gMEsZnoYWCdC5qDJjQXsFkJ1FAv92T7wvUJg+q3fhu1b5tJc27MKTQ4yvLs3bYSqKA5fvGCTrjTSeyZiaCNYs=,iv:jhi2F//e0eihX4HUiyOWjtBxQ27N3X0HNflYYhAjRP8=,tag:67lQSTnMdGVpweE8+aFsQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
