operatorConfig:
  defaultTags:
    - tag:k8s-operator
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

proxyConfig:
  defaultTags: tag:k8s
  image:
    repository: tailscale/tailscale
    tag: v1.98.9

apiServerProxyConfig:
  mode: "false"
